package com.dreammaster.scripts;

import static gregtech.api.enums.Mods.CompactKineticGenerators;
import static gregtech.api.enums.Mods.GTPlusPlus;
import static gregtech.api.enums.Mods.GregTech;
import static gregtech.api.enums.Mods.IndustrialCraft2;
import static gregtech.api.enums.Mods.NewHorizonsCoreMod;
import static gregtech.api.util.GT_ModHandler.getModItem;

import java.util.Arrays;
import java.util.List;

import fox.spiteful.avaritia.crafting.ExtremeCraftingManager;

public class ScriptCompactKineticGenerators implements IScriptLoader {

    @Override
    public String getScriptName() {
        return "Compact Kinetic Generators";
    }

    @Override
    public List<String> getDependencies() {
        return Arrays.asList(CompactKineticGenerators.ID, GTPlusPlus.ID, IndustrialCraft2.ID);
    }

    @Override
    public void loadRecipes() {
        addShapedRecipe(
                getModItem(CompactKineticGenerators.ID, "IridiumBlade", 1, 0, missing),
                new Object[] { "plateAlloyIridium", "plateAlloyIridium", "plateAlloyIridium", "plateAlloyIridium",
                        "ringOsmium", "plateAlloyIridium", "plateAlloyIridium", "plateAlloyIridium",
                        "plateAlloyIridium" });
        addShapedRecipe(
                getModItem(CompactKineticGenerators.ID, "IridiumRotor", 1, 0, missing),
                new Object[] { getModItem(GTPlusPlus.ID, "itemIridiumShaft", 1, 0, missing),
                        getModItem(CompactKineticGenerators.ID, "IridiumBlade", 1, 0, missing),
                        "craftingToolHardHammer",
                        getModItem(CompactKineticGenerators.ID, "IridiumBlade", 1, 0, missing), "ringChrome",
                        getModItem(CompactKineticGenerators.ID, "IridiumBlade", 1, 0, missing), "craftingToolWrench",
                        getModItem(CompactKineticGenerators.ID, "IridiumBlade", 1, 0, missing),
                        getModItem(GTPlusPlus.ID, "itemIridiumShaft", 1, 0, missing) });

        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 0, missing),
                "---------",
                "---------",
                "--aabaa--",
                "--cdedc--",
                "--bfgfb--",
                "--chehc--",
                "--aabaa--",
                "---------",
                "---------",
                'a',
                "plateTripleTungstenSteel",
                'b',
                getModItem(IndustrialCraft2.ID, "blockKineticGenerator", 1, 0, missing),
                'c',
                "itemCasingTungstenSteel",
                'd',
                "gearGtSmallDesh",
                'e',
                "cableGt02Tungsten",
                'f',
                "circuitElite",
                'g',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 14, missing),
                'h',
                getModItem(GregTech.ID, "gt.metaitem.01", 1, 32603, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 1, missing),
                "---------",
                "---------",
                "--aabaa--",
                "--cdedc--",
                "--bfgfb--",
                "--chehc--",
                "--aabaa--",
                "---------",
                "---------",
                'a',
                "plateTripleIridium",
                'b',
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 0, missing),
                'c',
                "itemCasingIridium",
                'd',
                "gearGtSmallOriharukon",
                'e',
                "wireGt04HSSG",
                'f',
                "circuitMaster",
                'g',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 15, missing),
                'h',
                getModItem(GregTech.ID, "gt.metaitem.01", 1, 32604, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 2, missing),
                "---------",
                "---------",
                "--aabaa--",
                "--cdedc--",
                "--bfgfb--",
                "--chehc--",
                "--aabaa--",
                "---------",
                "---------",
                'a',
                "plateTripleNaquadah",
                'b',
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 1, missing),
                'c',
                getModItem(NewHorizonsCoreMod.ID, "item.IridiumAlloyItemCasing", 1, 0, missing),
                'd',
                "gearGtSmallDraconium",
                'e',
                "cableGt04VanadiumGallium",
                'f',
                "circuitUltimate",
                'g',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 16, missing),
                'h',
                getModItem(GregTech.ID, "gt.metaitem.01", 1, 32606, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 3, missing),
                "---------",
                "---------",
                "--aabaa--",
                "--cdedc--",
                "--bfgfb--",
                "--chehc--",
                "--aabaa--",
                "---------",
                "---------",
                'a',
                "plateTripleNeutronium",
                'b',
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 2, missing),
                'c',
                "itemCasingNeutronium",
                'd',
                "gearGtSmallElectrumFlux",
                'e',
                "cableGt08Duranium",
                'f',
                "circuitSuperconductor",
                'g',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 17, missing),
                'h',
                getModItem(GregTech.ID, "gt.metaitem.01", 1, 32607, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 4, missing),
                "---------",
                "---------",
                "--aabaa--",
                "--cdedc--",
                "--bfgfb--",
                "--chehc--",
                "--aabaa--",
                "---------",
                "---------",
                'a',
                "plateTripleTungstenSteel",
                'b',
                getModItem(IndustrialCraft2.ID, "blockKineticGenerator", 1, 4, missing),
                'c',
                "itemCasingTungstenSteel",
                'd',
                getModItem(GregTech.ID, "gt.metaitem.01", 1, 32613, missing),
                'e',
                "cableGt02Tungsten",
                'f',
                "circuitElite",
                'g',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 14, missing),
                'h',
                "gearGtSmallDesh");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 5, missing),
                "---------",
                "---------",
                "--aabaa--",
                "--cdedc--",
                "--bfgfb--",
                "--chehc--",
                "--aabaa--",
                "---------",
                "---------",
                'a',
                "plateTripleIridium",
                'b',
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 4, missing),
                'c',
                "itemCasingIridium",
                'd',
                getModItem(GregTech.ID, "gt.metaitem.01", 1, 32614, missing),
                'e',
                "wireGt04HSSG",
                'f',
                "circuitMaster",
                'g',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 15, missing),
                'h',
                "gearGtSmallOriharukon");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 6, missing),
                "---------",
                "---------",
                "--aabaa--",
                "--cdedc--",
                "--bfgfb--",
                "--chehc--",
                "--aabaa--",
                "---------",
                "---------",
                'a',
                "plateTripleNaquadah",
                'b',
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 5, missing),
                'c',
                getModItem(NewHorizonsCoreMod.ID, "item.IridiumAlloyItemCasing", 1, 0, missing),
                'd',
                getModItem(GregTech.ID, "gt.metaitem.01", 1, 32615, missing),
                'e',
                "cableGt04VanadiumGallium",
                'f',
                "circuitUltimate",
                'g',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 16, missing),
                'h',
                "gearGtSmallDraconium");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 7, missing),
                "---------",
                "---------",
                "--aabaa--",
                "--cdedc--",
                "--bfgfb--",
                "--chehc--",
                "--aabaa--",
                "---------",
                "---------",
                'a',
                "plateTripleNeutronium",
                'b',
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 6, missing),
                'c',
                "itemCasingNeutronium",
                'd',
                getModItem(GregTech.ID, "gt.metaitem.01", 1, 32616, missing),
                'e',
                "cableGt08Duranium",
                'f',
                "circuitSuperconductor",
                'g',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 17, missing),
                'h',
                "gearGtSmallElectrumFlux");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 8, missing),
                "---------",
                "---------",
                "--aabaa--",
                "--cdedc--",
                "--fghgf--",
                "--cijic--",
                "--aabaa--",
                "---------",
                "---------",
                'a',
                "plateTripleTungstenSteel",
                'b',
                getModItem(GTPlusPlus.ID, "itemTungstenSteelShaft", 1, 0, missing),
                'c',
                "rotorTungstenSteel",
                'd',
                "gearDesh",
                'e',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 14, missing),
                'f',
                "cableGt02Tungsten",
                'g',
                "circuitElite",
                'h',
                getModItem(IndustrialCraft2.ID, "blockGenerator", 1, 9, missing),
                'i',
                getModItem(GregTech.ID, "gt.metaitem.01", 1, 32603, missing),
                'j',
                getModItem(GregTech.ID, "gt.metaitem.01", 1, 32540, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 9, missing),
                "---------",
                "---------",
                "--aabaa--",
                "--cdedc--",
                "--fghgf--",
                "--cijic--",
                "--aabaa--",
                "---------",
                "---------",
                'a',
                "plateTripleIridium",
                'b',
                getModItem(GTPlusPlus.ID, "itemTungstenSteelShaft", 1, 0, missing),
                'c',
                "rotorIridium",
                'd',
                "gearOriharukon",
                'e',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 15, missing),
                'f',
                "wireGt04HSSG",
                'g',
                "circuitMaster",
                'h',
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 8, missing),
                'i',
                getModItem(GregTech.ID, "gt.metaitem.01", 1, 32604, missing),
                'j',
                getModItem(GregTech.ID, "gt.metaitem.01", 1, 32545, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 10, missing),
                "---------",
                "---------",
                "--aabaa--",
                "--cdedc--",
                "--fghgf--",
                "--cijic--",
                "--aabaa--",
                "---------",
                "---------",
                'a',
                "plateTripleNaquadah",
                'b',
                getModItem(GTPlusPlus.ID, "itemIridiumShaft", 1, 0, missing),
                'c',
                "rotorOsmium",
                'd',
                "gearDraconium",
                'e',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 16, missing),
                'f',
                "cableGt04VanadiumGallium",
                'g',
                "circuitUltimate",
                'h',
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 9, missing),
                'i',
                getModItem(GregTech.ID, "gt.metaitem.01", 1, 32606, missing),
                'j',
                getModItem(GregTech.ID, "gt.metaitem.01", 1, 32550, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 11, missing),
                "---------",
                "---------",
                "--aabaa--",
                "--cdedc--",
                "--fghgf--",
                "--cijic--",
                "--aabaa--",
                "---------",
                "---------",
                'a',
                "plateTripleNeutronium",
                'b',
                getModItem(GTPlusPlus.ID, "itemIridiumShaft", 1, 0, missing),
                'c',
                "rotorNeutronium",
                'd',
                "gearElectrumFlux",
                'e',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 17, missing),
                'f',
                "cableGt08Duranium",
                'g',
                "circuitSuperconductor",
                'h',
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 10, missing),
                'i',
                getModItem(GregTech.ID, "gt.metaitem.01", 1, 32607, missing),
                'j',
                getModItem(GregTech.ID, "gt.metaitem.01", 1, 32555, missing));

    }
}
