package com.dreammaster.scripts;

import static com.dreammaster.scripts.IngredientFactory.getModItem;
import static gregtech.api.enums.Mods.AE2Stuff;
import static gregtech.api.enums.Mods.AppliedEnergistics2;

import java.util.Arrays;
import java.util.List;

import gregtech.api.enums.ItemList;

public class ScriptAE2Stuff implements IScriptLoader {

    @Override
    public String getScriptName() {
        return "AE2Stuff";
    }

    @Override
    public List<String> getDependencies() {
        return Arrays.asList(AE2Stuff.ID, AppliedEnergistics2.ID);
    }

    @Override
    public void loadRecipes() {

        // AUTOGENERATED

        addShapedRecipe(
                getModItem(AE2Stuff.ID, "Encoder", 1, 0),
                "plateTitanium",
                getModItem(AppliedEnergistics2.ID, "item.ItemMultiPart", 1, 340),
                "plateTitanium",
                getModItem(AppliedEnergistics2.ID, "item.ItemMultiMaterial", 1, 23),
                getModItem(AppliedEnergistics2.ID, "tile.BlockCraftingUnit", 1, 0),
                getModItem(AppliedEnergistics2.ID, "item.ItemMultiMaterial", 1, 23),
                "plateTitanium",
                getModItem(AppliedEnergistics2.ID, "item.ItemMultiPart", 1, 16),
                "plateTitanium");
        addShapedRecipe(
                getModItem(AE2Stuff.ID, "Grower", 1, 0),
                getModItem(AppliedEnergistics2.ID, "tile.BlockQuartzGrowthAccelerator", 1, 0),
                getModItem(AppliedEnergistics2.ID, "item.ItemMultiMaterial", 1, 22),
                getModItem(AppliedEnergistics2.ID, "tile.BlockQuartzGrowthAccelerator", 1, 0),
                getModItem(AppliedEnergistics2.ID, "tile.BlockQuartzGrowthAccelerator", 1, 0),
                "chestIron",
                getModItem(AppliedEnergistics2.ID, "tile.BlockQuartzGrowthAccelerator", 1, 0),
                getModItem(AppliedEnergistics2.ID, "tile.BlockQuartzGrowthAccelerator", 1, 0),
                getModItem(AppliedEnergistics2.ID, "item.ItemMultiMaterial", 1, 24),
                getModItem(AppliedEnergistics2.ID, "tile.BlockQuartzGrowthAccelerator", 1, 0));
        addShapedRecipe(
                getModItem(AE2Stuff.ID, "Wireless", 1, 0),
                "crystalPureFluix",
                "plateTitanium",
                "crystalPureFluix",
                getModItem(AppliedEnergistics2.ID, "item.ItemMultiMaterial", 1, 24),
                getModItem(AppliedEnergistics2.ID, "item.ItemMultiMaterial", 1, 41),
                getModItem(AppliedEnergistics2.ID, "item.ItemMultiMaterial", 1, 24),
                "crystalPureFluix",
                "plateTitanium",
                "crystalPureFluix");
        addShapedRecipe(
                getModItem(AE2Stuff.ID, "WirelessKit", 1, 0),
                getModItem(AppliedEnergistics2.ID, "item.ItemMultiMaterial", 1, 41),
                "plateTitanium",
                getModItem(AppliedEnergistics2.ID, "item.ItemMultiMaterial", 1, 41),
                getModItem(AppliedEnergistics2.ID, "item.ItemMultiMaterial", 1, 24),
                getModItem(AppliedEnergistics2.ID, "item.ItemMultiPart", 1, 180),
                getModItem(AppliedEnergistics2.ID, "item.ItemMultiMaterial", 1, 24),
                "crystalPureFluix",
                getModItem(AppliedEnergistics2.ID, "item.ItemMultiPart", 1, 16),
                "crystalPureFluix");
        addShapedRecipe(
                getModItem(AE2Stuff.ID, "AdvWirelessKit", 1, 0),
                ItemList.Sensor_ZPM,
                getModItem(AppliedEnergistics2.ID, "item.ItemMultiMaterial", 1, 23),
                ItemList.Sensor_ZPM,
                "crystalPureFluix",
                getModItem(AE2Stuff.ID, "WirelessKit", 1, 0),
                "crystalPureFluix",
                "plateTitanium",
                getModItem(AppliedEnergistics2.ID, "item.ItemMultiMaterial", 1, 23),
                "plateTitanium");
        addShapedRecipe(
                getModItem(AE2Stuff.ID, "Visualiser", 1, 0),
                "crystalPureFluix",
                getModItem(AppliedEnergistics2.ID, "item.ToolNetworkTool", 1, 0),
                "crystalPureFluix",
                "screwTitanium",
                getModItem(AppliedEnergistics2.ID, "item.ItemMultiMaterial", 1, 41),
                "screwTitanium",
                "craftingToolScrewdriver",
                getModItem(AppliedEnergistics2.ID, "item.ItemMultiMaterial", 1, 24),
                "craftingToolWrench");
        addShapedRecipe(
                getModItem(AE2Stuff.ID, "Inscriber", 1, 0),
                "plateTungstenSteel",
                getModItem(AppliedEnergistics2.ID, "item.ItemMultiMaterial", 1, 24),
                "plateTungstenSteel",
                getModItem(AppliedEnergistics2.ID, "item.ItemMultiMaterial", 1, 22),
                getModItem(AppliedEnergistics2.ID, "tile.BlockInscriber", 1, 0),
                getModItem(AppliedEnergistics2.ID, "item.ItemMultiMaterial", 1, 22),
                "plateTungstenSteel",
                getModItem(AppliedEnergistics2.ID, "item.ItemMultiMaterial", 1, 24),
                "plateTungstenSteel");

    }
}
