package com.dreammaster.scripts;

import static gregtech.api.util.GT_ModHandler.getModItem;

import java.util.Arrays;
import java.util.List;

import gregtech.api.enums.Mods;

public class ScriptAE2Stuff implements IScriptLoader {

    @Override
    public String getScriptName() {
        return "AE2Stuff";
    }

    @Override
    public List<String> getDependencies() {
        return Arrays.asList(Mods.AE2Stuff.ID);
    }

    @Override
    public void loadRecipes() {

        // AUTOGENERATED

        addShapedRecipe(
                getModItem("ae2stuff", "Encoder", 1, 0, missing),
                new Object[] { "plateTitanium",
                        getModItem("appliedenergistics2", "item.ItemMultiPart", 1, 340, missing), "plateTitanium",
                        getModItem("appliedenergistics2", "item.ItemMultiMaterial", 1, 23, missing),
                        getModItem("appliedenergistics2", "tile.BlockCraftingUnit", 1, 0, missing),
                        getModItem("appliedenergistics2", "item.ItemMultiMaterial", 1, 23, missing), "plateTitanium",
                        getModItem("appliedenergistics2", "item.ItemMultiPart", 1, 16, missing), "plateTitanium" });
        addShapedRecipe(
                getModItem("ae2stuff", "Grower", 1, 0, missing),
                new Object[] { getModItem("appliedenergistics2", "tile.BlockQuartzGrowthAccelerator", 1, 0, missing),
                        getModItem("appliedenergistics2", "item.ItemMultiMaterial", 1, 22, missing),
                        getModItem("appliedenergistics2", "tile.BlockQuartzGrowthAccelerator", 1, 0, missing),
                        getModItem("appliedenergistics2", "tile.BlockQuartzGrowthAccelerator", 1, 0, missing),
                        "chestIron",
                        getModItem("appliedenergistics2", "tile.BlockQuartzGrowthAccelerator", 1, 0, missing),
                        getModItem("appliedenergistics2", "tile.BlockQuartzGrowthAccelerator", 1, 0, missing),
                        getModItem("appliedenergistics2", "item.ItemMultiMaterial", 1, 24, missing),
                        getModItem("appliedenergistics2", "tile.BlockQuartzGrowthAccelerator", 1, 0, missing) });
        addShapedRecipe(
                getModItem("ae2stuff", "Wireless", 1, 0, missing),
                new Object[] { "crystalPureFluix", "plateTitanium", "crystalPureFluix",
                        getModItem("appliedenergistics2", "item.ItemMultiMaterial", 1, 24, missing),
                        getModItem("appliedenergistics2", "item.ItemMultiMaterial", 1, 41, missing),
                        getModItem("appliedenergistics2", "item.ItemMultiMaterial", 1, 24, missing), "crystalPureFluix",
                        "plateTitanium", "crystalPureFluix" });
        addShapedRecipe(
                getModItem("ae2stuff", "WirelessKit", 1, 0, missing),
                new Object[] { getModItem("appliedenergistics2", "item.ItemMultiMaterial", 1, 41, missing),
                        "plateTitanium", getModItem("appliedenergistics2", "item.ItemMultiMaterial", 1, 41, missing),
                        getModItem("appliedenergistics2", "item.ItemMultiMaterial", 1, 24, missing),
                        getModItem("appliedenergistics2", "item.ItemMultiPart", 1, 180, missing),
                        getModItem("appliedenergistics2", "item.ItemMultiMaterial", 1, 24, missing), "crystalPureFluix",
                        getModItem("appliedenergistics2", "item.ItemMultiPart", 1, 16, missing), "crystalPureFluix" });
        addShapedRecipe(
                getModItem("ae2stuff", "Visualiser", 1, 0, missing),
                new Object[] { "crystalPureFluix",
                        getModItem("appliedenergistics2", "item.ToolNetworkTool", 1, 0, missing), "crystalPureFluix",
                        "screwTitanium", getModItem("appliedenergistics2", "item.ItemMultiMaterial", 1, 41, missing),
                        "screwTitanium", "craftingToolScrewdriver",
                        getModItem("appliedenergistics2", "item.ItemMultiMaterial", 1, 24, missing),
                        "craftingToolWrench" });
        addShapedRecipe(
                getModItem("ae2stuff", "Inscriber", 1, 0, missing),
                new Object[] { "plateTungstenSteel",
                        getModItem("appliedenergistics2", "item.ItemMultiMaterial", 1, 24, missing),
                        "plateTungstenSteel",
                        getModItem("appliedenergistics2", "item.ItemMultiMaterial", 1, 22, missing),
                        getModItem("appliedenergistics2", "tile.BlockInscriber", 1, 0, missing),
                        getModItem("appliedenergistics2", "item.ItemMultiMaterial", 1, 22, missing),
                        "plateTungstenSteel",
                        getModItem("appliedenergistics2", "item.ItemMultiMaterial", 1, 24, missing),
                        "plateTungstenSteel" });

    }
}
