package com.dreammaster.scripts;

import static com.dreammaster.scripts.IngredientFactory.createItemStack;
import static com.dreammaster.scripts.IngredientFactory.getModItem;
import static gregtech.api.enums.Mods.AvaritiaAddons;
import static gregtech.api.enums.Mods.BloodArsenal;
import static gregtech.api.enums.Mods.BloodMagic;
import static gregtech.api.enums.Mods.Botania;
import static gregtech.api.enums.Mods.BuildCraftTransport;
import static gregtech.api.enums.Mods.DraconicEvolution;
import static gregtech.api.enums.Mods.EnderIO;
import static gregtech.api.enums.Mods.EtFuturumRequiem;
import static gregtech.api.enums.Mods.ExtraUtilities;
import static gregtech.api.enums.Mods.Forestry;
import static gregtech.api.enums.Mods.IndustrialCraft2;
import static gregtech.api.enums.Mods.Minecraft;
import static gregtech.api.enums.Mods.OpenBlocks;
import static gregtech.api.enums.Mods.OpenComputers;
import static gregtech.api.enums.Mods.ProjectRedIntegration;
import static gregtech.api.enums.Mods.Railcraft;
import static gregtech.api.enums.Mods.Thaumcraft;
import static gregtech.api.enums.Mods.TinkerConstruct;
import static gregtech.api.enums.Mods.TinkersGregworks;
import static gregtech.api.recipe.RecipeMaps.assemblerRecipes;
import static gregtech.api.recipe.RecipeMaps.blastFurnaceRecipes;
import static gregtech.api.recipe.RecipeMaps.hammerRecipes;
import static gregtech.api.recipe.RecipeMaps.packagerRecipes;
import static gregtech.api.util.GTModHandler.RecipeBits.BITS;
import static gregtech.api.util.GTRecipeBuilder.MINUTES;
import static gregtech.api.util.GTRecipeBuilder.SECONDS;
import static gregtech.api.util.GTRecipeBuilder.TICKS;

import java.util.Arrays;
import java.util.List;

import net.minecraft.item.ItemStack;
import net.minecraftforge.fluids.FluidRegistry;
import net.minecraftforge.fluids.FluidStack;

import com.dreammaster.item.NHItemList;

import fox.spiteful.avaritia.compat.ticon.Tonkers;
import fox.spiteful.avaritia.crafting.ExtremeCraftingManager;
import gregtech.api.enums.GTValues;
import gregtech.api.enums.ItemList;
import gregtech.api.enums.Materials;
import gregtech.api.enums.OrePrefixes;
import gregtech.api.enums.TierEU;
import gregtech.api.util.GTModHandler;
import gregtech.api.util.GTOreDictUnificator;
import tconstruct.tools.TinkerTools;

public class ScriptDraconicEvolution implements IScriptLoader {

    @Override
    public String getScriptName() {
        return "Draconic Evolution";
    }

    @Override
    public List<String> getDependencies() {
        return Arrays.asList(
                AvaritiaAddons.ID,
                BloodArsenal.ID,
                BloodMagic.ID,
                Botania.ID,
                BuildCraftTransport.ID,
                DraconicEvolution.ID,
                EnderIO.ID,
                EtFuturumRequiem.ID,
                ExtraUtilities.ID,
                Forestry.ID,
                IndustrialCraft2.ID,
                OpenBlocks.ID,
                OpenComputers.ID,
                ProjectRedIntegration.ID,
                Railcraft.ID,
                Thaumcraft.ID,
                TinkerConstruct.ID,
                TinkersGregworks.ID);
    }

    @Override
    public void loadRecipes() {
        addShapedRecipe(
                getModItem(DraconicEvolution.ID, "magnet", 1, 0),
                "blockSteelMagnetic",
                "ingotSteelMagnetic",
                "ingotSteelMagnetic",
                null,
                null,
                ItemList.Battery_RE_LV_Lithium.get(1L),
                "blockSteelMagnetic",
                "ingotSteelMagnetic",
                "ingotSteelMagnetic");
        addShapedRecipe(
                getModItem(DraconicEvolution.ID, "draconiumChest", 1, 0),
                "plateObsidian",
                getModItem(EnderIO.ID, "blockCapBank", 1, 1),
                "plateObsidian",
                getModItem(EtFuturumRequiem.ID, "blast_furnace", 1, 0),
                getModItem(AvaritiaAddons.ID, "CompressedChest", 1, 0),
                ItemList.Cover_Crafting.get(1L),
                "plateObsidian",
                "plateObsidian",
                "plateObsidian");
        addShapelessRecipe(
                getModItem(DraconicEvolution.ID, "safetyMatch", 1, 1000),
                ItemList.Tool_Matches.get(1L),
                "dustDraconium");
        addShapedRecipe(
                getModItem(DraconicEvolution.ID, "xRayBlock", 8, 0),
                getModItem(Minecraft.ID, "glass_pane", 1, 0),
                GTOreDictUnificator.get(OrePrefixes.plate, Materials.Thaumium, 1L),
                getModItem(Minecraft.ID, "glass_pane", 1, 0),
                GTOreDictUnificator.get(OrePrefixes.plate, Materials.Thaumium, 1L),
                GTOreDictUnificator.get(OrePrefixes.gemFlawless, Materials.Diamond, 1L),
                GTOreDictUnificator.get(OrePrefixes.plate, Materials.Thaumium, 1L),
                getModItem(Minecraft.ID, "glass_pane", 1, 0),
                GTOreDictUnificator.get(OrePrefixes.plate, Materials.Thaumium, 1L),
                getModItem(Minecraft.ID, "glass_pane", 1, 0));

        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "teleporterMKI", 1, 0),
                "----a----",
                "---bbb---",
                "--baaab--",
                "abacdcaba",
                "-badedab-",
                "-bacdcab-",
                "-bbaaabb-",
                "-aabbbaa-",
                "a-------a",
                'a',
                "plateDenseDraconium",
                'b',
                "plateDenseNaquadahAlloy",
                'c',
                ItemList.Circuit_Chip_UHPIC.get(1L),
                'd',
                "plateEuropium",
                'e',
                getModItem(DraconicEvolution.ID, "draconicCore", 1, 0));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "teleporterMKII", 1, 0),
                "---aaa---",
                "-aabcbaa-",
                "-adefeda-",
                "aghaiahga",
                "acaigiaca",
                "abaaiaaba",
                "-agefega-",
                "-aabcbaa-",
                "---aaa---",
                'a',
                "plateDenseDraconium",
                'b',
                "plateDenseDraconiumAwakened",
                'c',
                new ItemStack(TinkerTools.largePlate, 1, Tonkers.infinityMetalId),
                'd',
                ItemList.Field_Generator_UV.get(1L),
                'e',
                ItemList.Emitter_UV.get(1L),
                'f',
                "blockAmericium",
                'g',
                getModItem(DraconicEvolution.ID, "teleporterMKI", 1, 0),
                'h',
                ItemList.Sensor_UV.get(1L),
                'i',
                getModItem(DraconicEvolution.ID, "awakenedCore", 1, 0));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "draconiumFluxCapacitor", 1, 0),
                "---------",
                "----a----",
                "--abcba--",
                "--badab--",
                "-acdedca-",
                "--badab--",
                "--abcba--",
                "----a----",
                "---------",
                'a',
                "plateDraconium",
                'b',
                "wireGt02Superconductor",
                'c',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 0),
                'd',
                createItemStack(EnderIO.ID, "blockCapBank", 1, 3, "{type:\"VIBRANT\",storedEnergyRF:0}"),
                'e',
                getModItem(DraconicEvolution.ID, "wyvernCore", 1, 0));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "wyvernSword", 1, 0),
                "-------aa",
                "------aba",
                "-----aca-",
                "----ada--",
                "-e-ada---",
                "--efa----",
                "--ce-----",
                "-c--e----",
                "c--------",
                'a',
                "plateDraconium",
                'b',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 0),
                'c',
                "ingotDraconium",
                'd',
                getModItem(DraconicEvolution.ID, "wyvernCore", 1, 0),
                'e',
                "ingotNeutronium",
                'f',
                getModItem(BloodMagic.ID, "energySword", 1, 0));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "wyvernPickaxe", 1, 0),
                "-aaabaaa-",
                "accdedcca",
                "aa--f--aa",
                "----f----",
                "----f----",
                "----f----",
                "----f----",
                "----f----",
                "----f----",
                'a',
                "plateDraconium",
                'b',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 0),
                'c',
                "ingotDraconium",
                'd',
                getModItem(DraconicEvolution.ID, "wyvernCore", 1, 0),
                'e',
                getModItem(BloodMagic.ID, "boundPickaxe", 1, 0),
                'f',
                "ingotNeutronium");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "wyvernShovel", 1, 0),
                "------aab",
                "-----acda",
                "------aca",
                "-----e-a-",
                "----e----",
                "---e-----",
                "--e------",
                "-e-------",
                "e--------",
                'a',
                "plateDraconium",
                'b',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 0),
                'c',
                getModItem(DraconicEvolution.ID, "wyvernCore", 1, 0),
                'd',
                getModItem(BloodMagic.ID, "boundShovel", 1, 0),
                'e',
                "ingotNeutronium");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "wyvernBow", 1, 0),
                "---ab----",
                "--a-c----",
                "-a--c----",
                "a---c----",
                "d---e----",
                "a---c----",
                "-a--c----",
                "--a-c----",
                "---ab----",
                'a',
                "plateDraconium",
                'b',
                getModItem(DraconicEvolution.ID, "wyvernCore", 1, 0),
                'c',
                "ingotNeutronium",
                'd',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 0),
                'e',
                getModItem(BloodArsenal.ID, "bound_bow", 1, 0));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "wyvernHelm", 1, 0),
                "--aaaaa--",
                "-abbcbba-",
                "-a-ded-a-",
                "-abbbbba-",
                "-abbbbba-",
                "-ab---ba-",
                "---------",
                "---------",
                "---------",
                'a',
                "plateNeutronium",
                'b',
                "plateDraconium",
                'c',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 0),
                'd',
                getModItem(DraconicEvolution.ID, "wyvernCore", 1, 0),
                'e',
                getModItem(BloodMagic.ID, "sanguineHelmet", 1, 0));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "wyvernChest", 1, 0),
                "-aa---aa-",
                "aaa---aaa",
                "aaa---aaa",
                "-abbbbba-",
                "-abbcbba-",
                "-abdedba-",
                "-abbbbba-",
                "-abbbbba-",
                "--aaaaa--",
                'a',
                "plateNeutronium",
                'b',
                "plateDraconium",
                'c',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 0),
                'd',
                getModItem(DraconicEvolution.ID, "wyvernCore", 1, 0),
                'e',
                getModItem(BloodMagic.ID, "sanguineRobe", 1, 0));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "wyvernLeggs", 1, 0),
                "aaaaaaaaa",
                "abbbcbbba",
                "abaadaaba",
                "aba---aba",
                "aea---aea",
                "aba---aba",
                "aba---aba",
                "aba---aba",
                "aaa---aaa",
                'a',
                "plateNeutronium",
                'b',
                "plateDraconium",
                'c',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 0),
                'd',
                getModItem(BloodMagic.ID, "sanguinePants", 1, 0),
                'e',
                getModItem(DraconicEvolution.ID, "wyvernCore", 1, 0));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "wyvernBoots", 1, 0),
                "-aaabaaa-",
                "-acadaca-",
                "-aca-aca-",
                "-aca-aca-",
                "aeca-acea",
                "aaaa-aaaa",
                "---------",
                "---------",
                "---------",
                'a',
                "plateNeutronium",
                'b',
                getModItem(BloodMagic.ID, "sanguineBoots", 1, 0),
                'c',
                "plateDraconium",
                'd',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 0),
                'e',
                getModItem(DraconicEvolution.ID, "wyvernCore", 1, 0));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "draconiumFluxCapacitor", 1, 1),
                "---------",
                "----a----",
                "--abcba--",
                "--badab--",
                "-aedfdea-",
                "--badab--",
                "--abeba--",
                "----a----",
                "---------",
                'a',
                "plateDraconiumAwakened",
                'b',
                "wireGt04Superconductor",
                'c',
                getModItem(DraconicEvolution.ID, "awakenedCore", 1, 0),
                'd',
                NHItemList.EnrichedNaquadriaSunnariumAlloy.get(1),
                'e',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 1),
                'f',
                getModItem(DraconicEvolution.ID, "draconiumFluxCapacitor", 1, 0));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "draconicSword", 1, 0),
                "-------aa",
                "------aba",
                "-----aca-",
                "----ada--",
                "-e-ada---",
                "--efa----",
                "--ce-----",
                "-c--e----",
                "c--------",
                'a',
                "plateDraconiumAwakened",
                'b',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 1),
                'c',
                "ingotDraconiumAwakened",
                'd',
                getModItem(DraconicEvolution.ID, "awakenedCore", 1, 0),
                'e',
                "ingotDraconium",
                'f',
                getModItem(DraconicEvolution.ID, "wyvernSword", 1, 0));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "draconicPickaxe", 1, 0),
                "-aaabaaa-",
                "accdedcca",
                "aa--f--aa",
                "----f----",
                "----f----",
                "----f----",
                "----f----",
                "----f----",
                "----f----",
                'a',
                "plateDraconiumAwakened",
                'b',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 1),
                'c',
                "ingotDraconiumAwakened",
                'd',
                getModItem(DraconicEvolution.ID, "awakenedCore", 1, 0),
                'e',
                getModItem(DraconicEvolution.ID, "wyvernPickaxe", 1, 0),
                'f',
                "ingotDraconium");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "draconicShovel", 1, 0),
                "------aab",
                "-----acda",
                "------aca",
                "-----e-a-",
                "----e----",
                "---e-----",
                "--e------",
                "-e-------",
                "e--------",
                'a',
                "plateDraconiumAwakened",
                'b',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 1),
                'c',
                getModItem(DraconicEvolution.ID, "awakenedCore", 1, 0),
                'd',
                getModItem(DraconicEvolution.ID, "wyvernShovel", 1, 0),
                'e',
                "ingotDraconium");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "draconicBow", 1, 0),
                "---ab----",
                "--a-c----",
                "-a--c----",
                "a---c----",
                "d---e----",
                "a---c----",
                "-a--c----",
                "--a-c----",
                "---ab----",
                'a',
                "plateDraconiumAwakened",
                'b',
                getModItem(DraconicEvolution.ID, "awakenedCore", 1, 0),
                'c',
                "ingotDraconium",
                'd',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 1),
                'e',
                getModItem(DraconicEvolution.ID, "wyvernBow", 1, 0));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "draconicHelm", 1, 0),
                "--aaaaa--",
                "-abbcbba-",
                "-a-ded-a-",
                "-abbbbba-",
                "-abbbbba-",
                "-ab---ba-",
                "---------",
                "---------",
                "---------",
                'a',
                "plateDraconium",
                'b',
                "plateDraconiumAwakened",
                'c',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 1),
                'd',
                getModItem(DraconicEvolution.ID, "awakenedCore", 1, 0),
                'e',
                getModItem(DraconicEvolution.ID, "wyvernHelm", 1, 0));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "draconicChest", 1, 0),
                "-aa---aa-",
                "aaa---aaa",
                "aaa---aaa",
                "-abbbbba-",
                "-abbcbba-",
                "-abdedba-",
                "-abbbbba-",
                "-abbbbba-",
                "--aaaaa--",
                'a',
                "plateDraconium",
                'b',
                "plateDraconiumAwakened",
                'c',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 1),
                'd',
                getModItem(DraconicEvolution.ID, "awakenedCore", 1, 0),
                'e',
                getModItem(DraconicEvolution.ID, "wyvernChest", 1, 0));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "draconicLeggs", 1, 0),
                "aaaaaaaaa",
                "abbbcbbba",
                "abaadaaba",
                "aba---aba",
                "aea---aea",
                "aba---aba",
                "aba---aba",
                "aba---aba",
                "aaa---aaa",
                'a',
                "plateDraconium",
                'b',
                "plateDraconiumAwakened",
                'c',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 1),
                'd',
                getModItem(DraconicEvolution.ID, "wyvernLeggs", 1, 0),
                'e',
                getModItem(DraconicEvolution.ID, "awakenedCore", 1, 0));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "draconicBoots", 1, 0),
                "-aaabaaa-",
                "-acadaca-",
                "-aca-aca-",
                "-aca-aca-",
                "aeca-acea",
                "aaaa-aaaa",
                "---------",
                "---------",
                "---------",
                'a',
                "plateDraconium",
                'b',
                getModItem(DraconicEvolution.ID, "wyvernBoots", 1, 0),
                'c',
                "plateDraconiumAwakened",
                'd',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 1),
                'e',
                getModItem(DraconicEvolution.ID, "awakenedCore", 1, 0));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "draconicAxe", 1, 0),
                "-a-------",
                "abaaa----",
                "acdc-----",
                "-ae------",
                "--e------",
                "--e------",
                "--e------",
                "--e------",
                "--e------",
                'a',
                "plateDraconiumAwakened",
                'b',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 1),
                'c',
                getModItem(DraconicEvolution.ID, "awakenedCore", 1, 0),
                'd',
                getModItem(BloodMagic.ID, "boundAxe", 1, 0),
                'e',
                "ingotDraconium");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "draconicHoe", 1, 0),
                "-aaaa----",
                "b--aaa---",
                "----aaac-",
                "-----dea-",
                "-----cda-",
                "----c----",
                "---c-----",
                "--c------",
                "-c-------",
                'a',
                "plateDraconiumAwakened",
                'b',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 1),
                'c',
                "ingotDraconium",
                'd',
                getModItem(DraconicEvolution.ID, "awakenedCore", 1, 0),
                'e',
                getModItem(BloodArsenal.ID, "bound_sickle", 1, 0));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "draconicDistructionStaff", 1, 0),
                "---aba---",
                "-aacdcaa-",
                "a--efg--a",
                "----f----",
                "----f----",
                "----f----",
                "----f----",
                "----f----",
                "----f----",
                'a',
                "plateDraconiumAwakened",
                'b',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 1),
                'c',
                getModItem(DraconicEvolution.ID, "awakenedCore", 1, 0),
                'd',
                getModItem(DraconicEvolution.ID, "draconicShovel", 1, 0),
                'e',
                getModItem(DraconicEvolution.ID, "draconicPickaxe", 1, 0),
                'f',
                "ingotDraconiumAwakened",
                'g',
                getModItem(DraconicEvolution.ID, "draconicSword", 1, 0));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "energyInfuser", 1, 0),
                "---------",
                "----a----",
                "---bcb---",
                "---ded---",
                "---efe---",
                "--bdedb--",
                "--ggcgg--",
                "---------",
                "---------",
                'a',
                "craftingToolScrewdriver",
                'b',
                "screwDraconium",
                'c',
                getModItem(DraconicEvolution.ID, "particleGenerator", 1, 0),
                'd',
                getModItem(DraconicEvolution.ID, "infusedObsidian", 1, 0),
                'e',
                getModItem(DraconicEvolution.ID, "wyvernCore", 1, 0),
                'f',
                getModItem(DraconicEvolution.ID, "draconiumFluxCapacitor", 1, 0),
                'g',
                "blockDraconium");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "particleGenerator", 1, 0),
                "---------",
                "---abcba-",
                "---b---b-",
                "-abcba-c-",
                "-b-bdb-b-",
                "-c-abcba-",
                "-b---b---",
                "-abcba---",
                "---------",
                'a',
                getModItem(Minecraft.ID, "obsidian", 1, 0),
                'b',
                "stickBlaze",
                'c',
                "itemVibrantCrystal",
                'd',
                getModItem(Minecraft.ID, "comparator", 1, 0));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "magnet", 1, 1),
                "---------",
                "---------",
                "-abbbbb--",
                "------b--",
                "------b--",
                "------b--",
                "-cbbbbb--",
                "---------",
                "---------",
                'a',
                getModItem(DraconicEvolution.ID, "magnet", 1, 0),
                'b',
                "ingotNeodymiumMagnetic",
                'c',
                getModItem(EnderIO.ID, "itemMagnet", 1, 0));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "reactorCraftingPart", 1, 1),
                "---------",
                "---------",
                "---------",
                "-abbbbba-",
                "-cbbbbbc-",
                "-abbbbba-",
                "---------",
                "---------",
                "---------",
                'a',
                "plateDraconiumAwakened",
                'b',
                NHItemList.EngravedEnergyChip.get(),
                'c',
                getModItem(DraconicEvolution.ID, "wyvernCore", 1, 0));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "reactorCraftingPart", 1, 2),
                "---------",
                "---------",
                "---------",
                "-abbbbba-",
                "-cbbbbbc-",
                "-abbbbba-",
                "---------",
                "---------",
                "---------",
                'a',
                "plateDraconium",
                'b',
                NHItemList.EngravedDiamondCrystalChip.get(),
                'c',
                getModItem(DraconicEvolution.ID, "draconicCore", 1, 0));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "reactorCraftingPart", 1, 3),
                "---------",
                "---------",
                "-aabbbbb-",
                "-accccc--",
                "-deeeefg-",
                "-accccc--",
                "-aabbbbb-",
                "---------",
                "---------",
                'a',
                "stickLongDraconium",
                'b',
                getModItem(DraconicEvolution.ID, "reactorCraftingPart", 1, 2),
                'c',
                getModItem(DraconicEvolution.ID, "reactorCraftingPart", 1, 1),
                'd',
                getModItem(DraconicEvolution.ID, "draconium", 1, 2),
                'e',
                ItemList.Casing_Fusion_Coil.get(1L),
                'f',
                getModItem(DraconicEvolution.ID, "wyvernCore", 1, 0),
                'g',
                "plateDraconium");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "reactorCraftingPart", 1, 4),
                "---------",
                "---aba---",
                "--aacaa--",
                "-aadedaa-",
                "-bcefecb-",
                "-aadedaa-",
                "--aacaa--",
                "---aba---",
                "---------",
                'a',
                "stickRoseGold",
                'b',
                getModItem(DraconicEvolution.ID, "reactorCraftingPart", 1, 2),
                'c',
                getModItem(DraconicEvolution.ID, "wyvernCore", 1, 0),
                'd',
                getModItem(DraconicEvolution.ID, "reactorCraftingPart", 1, 1),
                'e',
                "lensNetherStar",
                'f',
                "lensDiamond");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "reactorCraftingPart", 1, 0),
                "aaaaaaaaa",
                "aa-----aa",
                "a-aaaaa-a",
                "a-abbba-a",
                "a-abcba-a",
                "a-abbba-a",
                "a-aaaaa-a",
                "aa-----aa",
                "aaaaaaaaa",
                'a',
                "plateBlackPlutonium",
                'b',
                "plateDraconiumAwakened",
                'c',
                getModItem(DraconicEvolution.ID, "awakenedCore", 1, 0));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "reactorStabilizer", 1, 0),
                "---------",
                "---------",
                "-abbbbba-",
                "-bcdbdcb-",
                "-efghifb-",
                "-bcdbdcb-",
                "-abbbbba-",
                "---------",
                "---------",
                'a',
                "plateBlackPlutonium",
                'b',
                "plateDraconiumAwakened",
                'c',
                NHItemList.EngravedManyullynCrystalChip.get(1),
                'd',
                getModItem(DraconicEvolution.ID, "draconiumFluxCapacitor", 1, 1),
                'e',
                getModItem(DraconicEvolution.ID, "reactorCraftingPart", 1, 0),
                'f',
                getModItem(DraconicEvolution.ID, "chaoticCore", 1, 0),
                'g',
                getModItem(DraconicEvolution.ID, "reactorCraftingPart", 1, 4),
                'h',
                "blockCosmicNeutronium",
                'i',
                getModItem(DraconicEvolution.ID, "reactorCraftingPart", 1, 3));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "reactorCore", 1, 0),
                "---------",
                "---aaa---",
                "--abcba--",
                "-abcdcba-",
                "-acdedca-",
                "-abcdcba-",
                "--abcba--",
                "---aaa---",
                "---------",
                'a',
                "plateDraconiumAwakened",
                'b',
                "blockDraconium",
                'c',
                getModItem(DraconicEvolution.ID, "draconium", 1, 2),
                'd',
                "blockDraconiumAwakened",
                'e',
                getModItem(DraconicEvolution.ID, "chaosShard", 1, 0));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "draconium", 1, 1),
                "---------",
                "---------",
                "--abcba--",
                "--bdedb--",
                "--cecec--",
                "--bdedb--",
                "--abcba--",
                "---------",
                "---------",
                'a',
                createItemStack(DraconicEvolution.ID, "mobSoul", 1, 0, "{Name:\"Any\"}"),
                'b',
                "plateDraconium",
                'c',
                getModItem(DraconicEvolution.ID, "wyvernCore", 1, 0),
                'd',
                "blockDraconium",
                'e',
                getModItem(DraconicEvolution.ID, "draconium", 1, 2));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "teleporterStand", 1, 0),
                "---------",
                "---------",
                "--abcba--",
                "---aaa---",
                "----d----",
                "----d----",
                "----d----",
                "---ede---",
                "--aaaaa--",
                'a',
                "slabStone",
                'b',
                "stickBlaze",
                'c',
                getModItem(DraconicEvolution.ID, "teleporterMKI", 1, 0),
                'd',
                getModItem(DraconicEvolution.ID, "infusedObsidian", 1, 0),
                'e',
                "stone");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "dislocatorReceptacle", 1, 0),
                "---------",
                "---------",
                "--abcba--",
                "--bdbdb--",
                "--cbebc--",
                "--bdbdb--",
                "--abcba--",
                "---------",
                "---------",
                'a',
                "plateSilver",
                'b',
                "plateDraconium",
                'c',
                getModItem(DraconicEvolution.ID, "draconicCore", 1, 0),
                'd',
                getModItem(DraconicEvolution.ID, "infusedObsidian", 1, 0),
                'e',
                getModItem(DraconicEvolution.ID, "teleporterStand", 1, 0));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "energyStorageCore", 1, 0),
                "---------",
                "---------",
                "--aabaa--",
                "--aacaa--",
                "--bcdcb--",
                "--aacaa--",
                "--aabaa--",
                "---------",
                "---------",
                'a',
                "plateDraconium",
                'b',
                getModItem(DraconicEvolution.ID, "draconiumFluxCapacitor", 1, 0),
                'c',
                getModItem(DraconicEvolution.ID, "wyvernCore", 1, 0),
                'd',
                getModItem(DraconicEvolution.ID, "draconium", 1, 2));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "energyPylon", 1, 0),
                "---------",
                "---------",
                "--abcba--",
                "--bcdcb--",
                "--cdedc--",
                "--bcdcb--",
                "--abcba--",
                "---------",
                "---------",
                'a',
                "gemEnderEye",
                'b',
                "plateEmerald",
                'c',
                "plateDiamond",
                'd',
                getModItem(DraconicEvolution.ID, "draconicCore", 1, 0),
                'e',
                "blockDraconium");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "energyCrystal", 1, 0),
                "---------",
                "----a----",
                "----b----",
                "---bbb---",
                "---aca---",
                "---bbb---",
                "----b----",
                "----a----",
                "---------",
                'a',
                "gemExquisiteDiamond",
                'b',
                "plateDraconium",
                'c',
                getModItem(DraconicEvolution.ID, "draconicCore", 1, 0));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "energyCrystal", 1, 1),
                "---------",
                "----a----",
                "----b----",
                "---cdc---",
                "---beb---",
                "---cdc---",
                "----b----",
                "----a----",
                "---------",
                'a',
                "plateDraconiumAwakened",
                'b',
                getModItem(DraconicEvolution.ID, "draconicCore", 1, 0),
                'c',
                "gemExquisiteRuby",
                'd',
                getModItem(DraconicEvolution.ID, "wyvernCore", 1, 0),
                'e',
                getModItem(DraconicEvolution.ID, "energyCrystal", 1, 0));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "wrench", 1, 0),
                "-----a---",
                "----aa---",
                "----ab---",
                "----abbaa",
                "---ccaaa-",
                "--ccc----",
                "-ccc-----",
                "ccc------",
                "dc-------",
                'a',
                "plateDraconium",
                'b',
                "plateDiamond",
                'c',
                "stickBlaze",
                'd',
                getModItem(DraconicEvolution.ID, "draconicCore", 1, 0));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "generator", 1, 3),
                "---------",
                "---------",
                "--abbba--",
                "--bcdcb--",
                "--befeb--",
                "--abbba--",
                "---------",
                "---------",
                "---------",
                'a',
                "plateSteel",
                'b',
                "ingotBrickNether",
                'c',
                ItemList.Battery_Hull_LV.get(1L),
                'd',
                getModItem(DraconicEvolution.ID, "draconicCore", 1, 0),
                'e',
                getModItem(BuildCraftTransport.ID, "item.buildcraftPipe.pipepowercobblestone", 1, 0),
                'f',
                "craftingIronFurnace");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "playerDetectorAdvanced", 1, 0),
                "---------",
                "---------",
                "---------",
                "--abcba--",
                "--adeda--",
                "--abcba--",
                "---------",
                "---------",
                "---------",
                'a',
                "plateDraconium",
                'b',
                "gemEnderEye",
                'c',
                getModItem(Minecraft.ID, "compass", 1, 0),
                'd',
                getModItem(Minecraft.ID, "skull", 1, 1),
                'e',
                getModItem(DraconicEvolution.ID, "playerDetector", 1, 0));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "weatherController", 1, 0),
                "---------",
                "---------",
                "--abcda--",
                "--aefea--",
                "--aghga--",
                "--aaaaa--",
                "---------",
                "---------",
                "---------",
                'a',
                "plateDraconium",
                'b',
                getModItem(DraconicEvolution.ID, "rainSensor", 1, 0),
                'c',
                getModItem(OpenBlocks.ID, "bigbutton", 1, 0),
                'd',
                getModItem(Minecraft.ID, "daylight_detector", 1, 0),
                'e',
                getModItem(DraconicEvolution.ID, "draconicCore", 1, 0),
                'f',
                getModItem(Forestry.ID, "factory", 1, 7),
                'g',
                "stickBlaze",
                'h',
                "gemExquisiteEmerald");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "sunDial", 1, 0),
                "---------",
                "---------",
                "--aabaa--",
                "--ccdcc--",
                "--cefec--",
                "--cghgc--",
                "--ccccc--",
                "---------",
                "---------",
                'a',
                "plateDraconium",
                'b',
                getModItem(Minecraft.ID, "dragon_egg", 1, 0),
                'c',
                "plateDraconiumAwakened",
                'd',
                getModItem(DraconicEvolution.ID, "dragonHeart", 1, 0),
                'e',
                getModItem(DraconicEvolution.ID, "wyvernCore", 1, 0),
                'f',
                getModItem(DraconicEvolution.ID, "chaosShard", 1, 0),
                'g',
                getModItem(DraconicEvolution.ID, "awakenedCore", 1, 0),
                'h',
                getModItem(DraconicEvolution.ID, "weatherController", 1, 0));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "grinder", 1, 3),
                "---------",
                "---------",
                "--aaaaa--",
                "--abcba--",
                "--adeda--",
                "--aaaaa--",
                "---------",
                "---------",
                "---------",
                'a',
                "plateDraconium",
                'b',
                getModItem(Thaumcraft.ID, "ItemSwordElemental", 1, 0),
                'c',
                getModItem(EnderIO.ID, "blockKillerJoe", 1, 0),
                'd',
                ItemList.Electric_Motor_IV.get(1L),
                'e',
                getModItem(EnderIO.ID, "blockCapBank", 1, 3));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "flowGate", 1, 6),
                "---------",
                "---------",
                "--aaaaa--",
                "--aabaa--",
                "--cdedc--",
                "--aabaa--",
                "--aaaaa--",
                "---------",
                "---------",
                'a',
                "plateDraconium",
                'b',
                getModItem(DraconicEvolution.ID, "draconicCore", 1, 0),
                'c',
                "pipeHugeNeutronium",
                'd',
                getModItem(ProjectRedIntegration.ID, "projectred.integration.gate", 1, 26),
                'e',
                getModItem(DraconicEvolution.ID, "wyvernCore", 1, 0));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "flowGate", 1, 0),
                "---------",
                "---------",
                "--aaaaa--",
                "--aabaa--",
                "--cdedc--",
                "--aabaa--",
                "--aaaaa--",
                "---------",
                "---------",
                'a',
                "plateDraconium",
                'b',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 0),
                'c',
                getModItem(EnderIO.ID, "itemPowerConduit", 1, 2),
                'd',
                getModItem(ProjectRedIntegration.ID, "projectred.integration.gate", 1, 26),
                'e',
                getModItem(DraconicEvolution.ID, "wyvernCore", 1, 0));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "reactorEnergyInjector", 1, 0),
                "---------",
                "---------",
                "--a-b-a--",
                "--acbca--",
                "--dcecd--",
                "--fffff--",
                "--fffff--",
                "---------",
                "---------",
                'a',
                getModItem(DraconicEvolution.ID, "reactorCraftingPart", 1, 2),
                'b',
                "plateDraconiumAwakened",
                'c',
                getModItem(DraconicEvolution.ID, "reactorCraftingPart", 1, 1),
                'd',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 0),
                'e',
                getModItem(DraconicEvolution.ID, "wyvernCore", 1, 0),
                'f',
                "plateDraconium");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "upgradeModifier", 1, 0),
                "---------",
                "---------",
                "--aaaaa--",
                "--abcba--",
                "--acdca--",
                "--abcba--",
                "--aaaaa--",
                "---------",
                "---------",
                'a',
                "plateDraconium",
                'b',
                "gearDraconium",
                'c',
                getModItem(DraconicEvolution.ID, "draconicCore", 1, 0),
                'd',
                ItemList.Electric_Motor_IV.get(1L));

        GTValues.RA.stdBuilder()
                .itemInputs(
                        GTOreDictUnificator.get(OrePrefixes.plate, Materials.Stone, 4),
                        getModItem(DraconicEvolution.ID, "draconiumDust", 1, 0))
                .itemOutputs(getModItem(DraconicEvolution.ID, "infoTablet", 1, 0)).duration(20 * SECONDS)
                .eut(TierEU.RECIPE_HV).addTo(assemblerRecipes);
        GTValues.RA.stdBuilder()
                .itemInputs(
                        getModItem(DraconicEvolution.ID, "energyCrystal", 1, 0),
                        getModItem(DraconicEvolution.ID, "particleGenerator", 2, 0))
                .itemOutputs(getModItem(DraconicEvolution.ID, "energyCrystal", 1, 4))
                .fluidInputs(FluidRegistry.getFluidStack("molten.enderium", 864)).duration(1 * MINUTES)
                .eut(TierEU.RECIPE_EV / 2).addTo(assemblerRecipes);
        GTValues.RA.stdBuilder()
                .itemInputs(
                        getModItem(DraconicEvolution.ID, "energyCrystal", 1, 1),
                        getModItem(DraconicEvolution.ID, "particleGenerator", 2, 0))
                .itemOutputs(getModItem(DraconicEvolution.ID, "energyCrystal", 1, 5))
                .fluidInputs(FluidRegistry.getFluidStack("molten.enderium", 864)).duration(2 * MINUTES)
                .eut(TierEU.RECIPE_IV / 2).addTo(assemblerRecipes);
        GTValues.RA.stdBuilder()
                .itemInputs(getModItem(Minecraft.ID, "arrow", 1, 0), getModItem(Minecraft.ID, "ender_pearl", 1, 0))
                .itemOutputs(getModItem(DraconicEvolution.ID, "enderArrow", 1, 0)).duration(10 * SECONDS)
                .eut(TierEU.RECIPE_HV).addTo(assemblerRecipes);
        GTValues.RA.stdBuilder()
                .itemInputs(
                        getModItem(Railcraft.ID, "detector", 1, 5),
                        getModItem(DraconicEvolution.ID, "draconicCore", 1, 0))
                .itemOutputs(getModItem(DraconicEvolution.ID, "playerDetector", 1, 0)).duration(10 * SECONDS)
                .eut(TierEU.RECIPE_HV).addTo(assemblerRecipes);
        GTValues.RA.stdBuilder()
                .itemInputs(
                        getModItem(ProjectRedIntegration.ID, "projectred.integration.gate", 1, 16),
                        GTOreDictUnificator.get(OrePrefixes.plate, Materials.Draconium, 1L))
                .itemOutputs(getModItem(DraconicEvolution.ID, "rainSensor", 1, 0)).duration(10 * SECONDS)
                .eut(TierEU.RECIPE_HV).addTo(assemblerRecipes);
        GTValues.RA.stdBuilder().itemInputs(
                getModItem(Botania.ID, "tinyPlanetBlock", 1, 0),
                getModItem(ExtraUtilities.ID, "greenscreen", 64, 3),
                getModItem(ExtraUtilities.ID, "greenscreen", 64, 11),
                getModItem(ExtraUtilities.ID, "greenscreen", 64, 13),
                getModItem(OpenComputers.ID, "hologram2", 1, 0),
                createItemStack(ExtraUtilities.ID, "microblocks", 1, 3, "{mat:\"tile.extrautils:decorativeBlock1_5\"}"))
                .fluidInputs(new FluidStack(FluidRegistry.getFluid("water"), 10000))
                .itemOutputs(getModItem(DraconicEvolution.ID, "earth", 1, 0)).duration(6 * SECONDS).eut(200)
                .addTo(assemblerRecipes);
        GTValues.RA.stdBuilder()
                .itemInputs(getModItem(Minecraft.ID, "obsidian", 1, 0), getModItem(Minecraft.ID, "blaze_powder", 1, 0))
                .itemOutputs(getModItem(DraconicEvolution.ID, "infusedObsidian", 1, 0))
                .fluidInputs(FluidRegistry.getFluidStack("molten.draconium", 144)).duration(1 * MINUTES)
                .eut(TierEU.RECIPE_EV).specialValue(7500).addTo(blastFurnaceRecipes);
        GTValues.RA.stdBuilder().itemInputs(getModItem(DraconicEvolution.ID, "chaosShard", 1, 0))
                .itemOutputs(getModItem(DraconicEvolution.ID, "chaosFragment", 9, 2)).duration(5 * SECONDS)
                .eut(TierEU.RECIPE_HV).addTo(hammerRecipes);
        GTValues.RA.stdBuilder().itemInputs(getModItem(DraconicEvolution.ID, "chaosFragment", 1, 2))
                .itemOutputs(getModItem(DraconicEvolution.ID, "chaosFragment", 9, 1)).duration(2 * SECONDS + 10 * TICKS)
                .eut(TierEU.RECIPE_HV).addTo(hammerRecipes);
        GTValues.RA.stdBuilder().itemInputs(getModItem(DraconicEvolution.ID, "chaosFragment", 1, 1))
                .itemOutputs(getModItem(DraconicEvolution.ID, "chaosFragment", 9, 0)).duration(1 * SECONDS + 5 * TICKS)
                .eut(TierEU.RECIPE_HV).addTo(hammerRecipes);
        GTValues.RA.stdBuilder()
                .itemInputs(
                        getModItem(DraconicEvolution.ID, "safetyMatch", 16, 1000),
                        GTOreDictUnificator.get(OrePrefixes.plateDouble, Materials.Paper, 1L))
                .itemOutputs(getModItem(DraconicEvolution.ID, "safetyMatch", 1, 0)).duration(3 * SECONDS + 4 * TICKS)
                .eut(TierEU.RECIPE_LV / 2).addTo(packagerRecipes);

        GTModHandler.addCraftingRecipe(
                getModItem(DraconicEvolution.ID, "dislocatorInhibitor", 1, 0),
                BITS,
                new Object[] { "PSP", "BMB", "PSP", 'P', "plateSteelMagnetic", 'S',
                        getModItem(TinkerConstruct.ID, "heavyPlate", 1, 6), 'B',
                        getModItem(EnderIO.ID, "blockDarkIronBars", 1, 0), 'M',
                        getModItem(DraconicEvolution.ID, "magnet", 1, 0) });

    }
}
