package com.dreammaster.scripts;

import static gregtech.api.enums.Mods.AvaritiaAddons;
import static gregtech.api.enums.Mods.BloodArsenal;
import static gregtech.api.enums.Mods.BloodMagic;
import static gregtech.api.enums.Mods.BuildCraftTransport;
import static gregtech.api.enums.Mods.DraconicEvolution;
import static gregtech.api.enums.Mods.EnderIO;
import static gregtech.api.enums.Mods.Forestry;
import static gregtech.api.enums.Mods.GregTech;
import static gregtech.api.enums.Mods.IndustrialCraft2;
import static gregtech.api.enums.Mods.Minecraft;
import static gregtech.api.enums.Mods.NewHorizonsCoreMod;
import static gregtech.api.enums.Mods.OpenBlocks;
import static gregtech.api.enums.Mods.ProjectRedIntegration;
import static gregtech.api.enums.Mods.Railcraft;
import static gregtech.api.enums.Mods.Thaumcraft;
import static gregtech.api.enums.Mods.TinkersGregworks;
import static gregtech.api.util.GT_ModHandler.addShapelessCraftingRecipe;
import static gregtech.api.util.GT_ModHandler.getModItem;
import static gregtech.api.util.GT_Recipe.GT_Recipe_Map.sAssemblerRecipes;
import static gregtech.api.util.GT_Recipe.GT_Recipe_Map.sBlastRecipes;
import static gregtech.api.util.GT_Recipe.GT_Recipe_Map.sBoxinatorRecipes;
import static gregtech.api.util.GT_Recipe.GT_Recipe_Map.sHammerRecipes;

import java.util.Arrays;
import java.util.List;

import net.minecraftforge.fluids.FluidRegistry;

import fox.spiteful.avaritia.crafting.ExtremeCraftingManager;
import gregtech.api.enums.GT_Values;

public class ScriptDraconicEvolution implements IScriptLoader {

    @Override
    public String getScriptName() {
        return "Draconic Evolution";
    }

    @Override
    public List<String> getDependencies() {
        return Arrays.asList(
                DraconicEvolution.ID,
                AvaritiaAddons.ID,
                BloodArsenal.ID,
                BloodMagic.ID,
                BuildCraftTransport.ID,
                EnderIO.ID,
                Forestry.ID,
                IndustrialCraft2.ID,
                OpenBlocks.ID,
                ProjectRedIntegration.ID,
                Railcraft.ID,
                Thaumcraft.ID,
                TinkersGregworks.ID);
    }

    @Override
    public void loadRecipes() {
        addShapedRecipe(
                getModItem(DraconicEvolution.ID, "magnet", 1, 0, missing),
                new Object[] { "blockSteelMagnetic", "ingotSteelMagnetic", "ingotSteelMagnetic", null, null,
                        getModItem(GregTech.ID, "gt.metaitem.01", 1, 32518, missing), "blockSteelMagnetic",
                        "ingotSteelMagnetic", "ingotSteelMagnetic" });
        addShapedRecipe(
                getModItem(DraconicEvolution.ID, "draconiumChest", 1, 0, missing),
                new Object[] { "plateObsidian", getModItem(EnderIO.ID, "blockCapBank", 1, 1, missing), "plateObsidian",
                        getModItem(IndustrialCraft2.ID, "blockMachine", 1, 1, missing),
                        getModItem(AvaritiaAddons.ID, "CompressedChest", 1, 0, missing),
                        getModItem(GregTech.ID, "gt.metaitem.01", 1, 32744, missing), "plateObsidian", "plateObsidian",
                        "plateObsidian" });
        addShapelessCraftingRecipe(
                getModItem(DraconicEvolution.ID, "safetyMatch", 1, 1000, missing),
                new Object[] { getModItem(GregTech.ID, "gt.metaitem.01", 1, 32471, missing), "dustDraconium" });
        addShapedRecipe(
                getModItem(DraconicEvolution.ID, "xRayBlock", 8, 0, missing),
                new Object[] { getModItem(Minecraft.ID, "glass_pane", 1, 0, missing),
                        getModItem(GregTech.ID, "gt.metaitem.01", 1, 17330, missing),
                        getModItem(Minecraft.ID, "glass_pane", 1, 0, missing),
                        getModItem(GregTech.ID, "gt.metaitem.01", 1, 17330, missing),
                        getModItem(GregTech.ID, "gt.metaitem.02", 1, 29500, missing),
                        getModItem(GregTech.ID, "gt.metaitem.01", 1, 17330, missing),
                        getModItem(Minecraft.ID, "glass_pane", 1, 0, missing),
                        getModItem(GregTech.ID, "gt.metaitem.01", 1, 17330, missing),
                        getModItem(Minecraft.ID, "glass_pane", 1, 0, missing) });

        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "teleporterMKI", 1, 0, missing),
                "----a----",
                "---bbb---",
                "--baaab--",
                "abacdcaba",
                "-badedab-",
                "-bacdcab-",
                "-bbaaabb-",
                "-aabbbaa-",
                "a-------a",
                'a',
                "plateDenseDraconium",
                'b',
                "plateDenseNaquadahAlloy",
                'c',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32059, missing),
                'd',
                "plateEuropium",
                'e',
                getModItem(DraconicEvolution.ID, "draconicCore", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "teleporterMKII", 1, 0, missing),
                "---aaa---",
                "-aabcbaa-",
                "-adefeda-",
                "aghaiahga",
                "acaigiaca",
                "abaaiaaba",
                "-agefega-",
                "-aabcbaa-",
                "---aaa---",
                'a',
                "plateDenseDraconium",
                'b',
                "plateDenseDraconiumAwakened",
                'c',
                createItemStack(
                        TinkersGregworks.ID,
                        "tGregToolPartLargePlate",
                        1,
                        1669,
                        "{material:\"Infinity\"}",
                        missing),
                'd',
                getModItem(GregTech.ID, "gt.metaitem.01", 1, 32677, missing),
                'e',
                getModItem(GregTech.ID, "gt.metaitem.01", 1, 32687, missing),
                'f',
                "blockAmericium",
                'g',
                getModItem(DraconicEvolution.ID, "teleporterMKI", 1, 0, missing),
                'h',
                getModItem(GregTech.ID, "gt.metaitem.01", 1, 32697, missing),
                'i',
                getModItem(DraconicEvolution.ID, "awakenedCore", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "draconiumFluxCapacitor", 1, 0, missing),
                "---------",
                "----a----",
                "--abcba--",
                "--badab--",
                "-acdedca-",
                "--badab--",
                "--abcba--",
                "----a----",
                "---------",
                'a',
                "plateDraconium",
                'b',
                "wireGt02Superconductor",
                'c',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 0, missing),
                'd',
                createItemStack(EnderIO.ID, "blockCapBank", 1, 3, "{type:\"VIBRANT\",storedEnergyRF:0}", missing),
                'e',
                getModItem(DraconicEvolution.ID, "wyvernCore", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "wyvernSword", 1, 0, missing),
                "-------aa",
                "------aba",
                "-----aca-",
                "----ada--",
                "-e-ada---",
                "--efa----",
                "--ce-----",
                "-c--e----",
                "c--------",
                'a',
                "plateDraconium",
                'b',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 0, missing),
                'c',
                "ingotDraconium",
                'd',
                getModItem(DraconicEvolution.ID, "wyvernCore", 1, 0, missing),
                'e',
                "ingotNeutronium",
                'f',
                getModItem(BloodMagic.ID, "energySword", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "wyvernPickaxe", 1, 0, missing),
                "-aaabaaa-",
                "accdedcca",
                "aa--f--aa",
                "----f----",
                "----f----",
                "----f----",
                "----f----",
                "----f----",
                "----f----",
                'a',
                "plateDraconium",
                'b',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 0, missing),
                'c',
                "ingotDraconium",
                'd',
                getModItem(DraconicEvolution.ID, "wyvernCore", 1, 0, missing),
                'e',
                getModItem(BloodMagic.ID, "boundPickaxe", 1, 0, missing),
                'f',
                "ingotNeutronium");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "wyvernShovel", 1, 0, missing),
                "------aab",
                "-----acda",
                "------aca",
                "-----e-a-",
                "----e----",
                "---e-----",
                "--e------",
                "-e-------",
                "e--------",
                'a',
                "plateDraconium",
                'b',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 0, missing),
                'c',
                getModItem(DraconicEvolution.ID, "wyvernCore", 1, 0, missing),
                'd',
                getModItem(BloodMagic.ID, "boundShovel", 1, 0, missing),
                'e',
                "ingotNeutronium");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "wyvernBow", 1, 0, missing),
                "---ab----",
                "--a-c----",
                "-a--c----",
                "a---c----",
                "d---e----",
                "a---c----",
                "-a--c----",
                "--a-c----",
                "---ab----",
                'a',
                "plateDraconium",
                'b',
                getModItem(DraconicEvolution.ID, "wyvernCore", 1, 0, missing),
                'c',
                "ingotNeutronium",
                'd',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 0, missing),
                'e',
                getModItem(BloodArsenal.ID, "bound_bow", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "wyvernHelm", 1, 0, missing),
                "--aaaaa--",
                "-abbcbba-",
                "-a-ded-a-",
                "-abbbbba-",
                "-abbbbba-",
                "-ab---ba-",
                "---------",
                "---------",
                "---------",
                'a',
                "plateNeutronium",
                'b',
                "plateDraconium",
                'c',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 0, missing),
                'd',
                getModItem(DraconicEvolution.ID, "wyvernCore", 1, 0, missing),
                'e',
                getModItem(BloodMagic.ID, "sanguineHelmet", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "wyvernChest", 1, 0, missing),
                "-aa---aa-",
                "aaa---aaa",
                "aaa---aaa",
                "-abbbbba-",
                "-abbcbba-",
                "-abdedba-",
                "-abbbbba-",
                "-abbbbba-",
                "--aaaaa--",
                'a',
                "plateNeutronium",
                'b',
                "plateDraconium",
                'c',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 0, missing),
                'd',
                getModItem(DraconicEvolution.ID, "wyvernCore", 1, 0, missing),
                'e',
                getModItem(BloodMagic.ID, "sanguineRobe", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "wyvernLeggs", 1, 0, missing),
                "aaaaaaaaa",
                "abbbcbbba",
                "abaadaaba",
                "aba---aba",
                "aea---aea",
                "aba---aba",
                "aba---aba",
                "aba---aba",
                "aaa---aaa",
                'a',
                "plateNeutronium",
                'b',
                "plateDraconium",
                'c',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 0, missing),
                'd',
                getModItem(BloodMagic.ID, "sanguinePants", 1, 0, missing),
                'e',
                getModItem(DraconicEvolution.ID, "wyvernCore", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "wyvernBoots", 1, 0, missing),
                "-aaabaaa-",
                "-acadaca-",
                "-aca-aca-",
                "-aca-aca-",
                "aeca-acea",
                "aaaa-aaaa",
                "---------",
                "---------",
                "---------",
                'a',
                "plateNeutronium",
                'b',
                getModItem(BloodMagic.ID, "sanguineBoots", 1, 0, missing),
                'c',
                "plateDraconium",
                'd',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 0, missing),
                'e',
                getModItem(DraconicEvolution.ID, "wyvernCore", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "draconiumFluxCapacitor", 1, 1, missing),
                "---------",
                "----a----",
                "--abcba--",
                "--badab--",
                "-aedfdea-",
                "--badab--",
                "--abeba--",
                "----a----",
                "---------",
                'a',
                "plateDraconiumAwakened",
                'b',
                "wireGt04Superconductor",
                'c',
                getModItem(DraconicEvolution.ID, "awakenedCore", 1, 0, missing),
                'd',
                getModItem(NewHorizonsCoreMod.ID, "item.EnrichedNaquadriaSunnariumAlloy", 1, 0, missing),
                'e',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 1, missing),
                'f',
                getModItem(DraconicEvolution.ID, "draconiumFluxCapacitor", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "draconicSword", 1, 0, missing),
                "-------aa",
                "------aba",
                "-----aca-",
                "----ada--",
                "-e-ada---",
                "--efa----",
                "--ce-----",
                "-c--e----",
                "c--------",
                'a',
                "plateDraconiumAwakened",
                'b',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 1, missing),
                'c',
                "ingotDraconiumAwakened",
                'd',
                getModItem(DraconicEvolution.ID, "awakenedCore", 1, 0, missing),
                'e',
                "ingotDraconium",
                'f',
                getModItem(DraconicEvolution.ID, "wyvernSword", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "draconicPickaxe", 1, 0, missing),
                "-aaabaaa-",
                "accdedcca",
                "aa--f--aa",
                "----f----",
                "----f----",
                "----f----",
                "----f----",
                "----f----",
                "----f----",
                'a',
                "plateDraconiumAwakened",
                'b',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 1, missing),
                'c',
                "ingotDraconiumAwakened",
                'd',
                getModItem(DraconicEvolution.ID, "awakenedCore", 1, 0, missing),
                'e',
                getModItem(DraconicEvolution.ID, "wyvernPickaxe", 1, 0, missing),
                'f',
                "ingotDraconium");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "draconicShovel", 1, 0, missing),
                "------aab",
                "-----acda",
                "------aca",
                "-----e-a-",
                "----e----",
                "---e-----",
                "--e------",
                "-e-------",
                "e--------",
                'a',
                "plateDraconiumAwakened",
                'b',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 1, missing),
                'c',
                getModItem(DraconicEvolution.ID, "awakenedCore", 1, 0, missing),
                'd',
                getModItem(DraconicEvolution.ID, "wyvernShovel", 1, 0, missing),
                'e',
                "ingotDraconium");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "draconicBow", 1, 0, missing),
                "---ab----",
                "--a-c----",
                "-a--c----",
                "a---c----",
                "d---e----",
                "a---c----",
                "-a--c----",
                "--a-c----",
                "---ab----",
                'a',
                "plateDraconiumAwakened",
                'b',
                getModItem(DraconicEvolution.ID, "awakenedCore", 1, 0, missing),
                'c',
                "ingotDraconium",
                'd',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 1, missing),
                'e',
                getModItem(DraconicEvolution.ID, "wyvernBow", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "draconicHelm", 1, 0, missing),
                "--aaaaa--",
                "-abbcbba-",
                "-a-ded-a-",
                "-abbbbba-",
                "-abbbbba-",
                "-ab---ba-",
                "---------",
                "---------",
                "---------",
                'a',
                "plateDraconium",
                'b',
                "plateDraconiumAwakened",
                'c',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 1, missing),
                'd',
                getModItem(DraconicEvolution.ID, "awakenedCore", 1, 0, missing),
                'e',
                getModItem(DraconicEvolution.ID, "wyvernHelm", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "draconicChest", 1, 0, missing),
                "-aa---aa-",
                "aaa---aaa",
                "aaa---aaa",
                "-abbbbba-",
                "-abbcbba-",
                "-abdedba-",
                "-abbbbba-",
                "-abbbbba-",
                "--aaaaa--",
                'a',
                "plateDraconium",
                'b',
                "plateDraconiumAwakened",
                'c',
                getModItem(DraconicEvolution.ID, "awakenedCore", 1, 0, missing),
                'd',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 1, missing),
                'e',
                getModItem(DraconicEvolution.ID, "wyvernChest", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "draconicLeggs", 1, 0, missing),
                "aaaaaaaaa",
                "abbbcbbba",
                "abaadaaba",
                "aba---aba",
                "aea---aea",
                "aba---aba",
                "aba---aba",
                "aba---aba",
                "aaa---aaa",
                'a',
                "plateDraconium",
                'b',
                "plateDraconiumAwakened",
                'c',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 1, missing),
                'd',
                getModItem(DraconicEvolution.ID, "wyvernLeggs", 1, 0, missing),
                'e',
                getModItem(DraconicEvolution.ID, "awakenedCore", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "draconicBoots", 1, 0, missing),
                "-aaabaaa-",
                "-acadaca-",
                "-aca-aca-",
                "-aca-aca-",
                "aeca-acea",
                "aaaa-aaaa",
                "---------",
                "---------",
                "---------",
                'a',
                "plateDraconium",
                'b',
                getModItem(DraconicEvolution.ID, "wyvernBoots", 1, 0, missing),
                'c',
                "plateDraconiumAwakened",
                'd',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 1, missing),
                'e',
                getModItem(DraconicEvolution.ID, "awakenedCore", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "draconicAxe", 1, 0, missing),
                "-a-------",
                "abaaa----",
                "acdc-----",
                "-ae------",
                "--e------",
                "--e------",
                "--e------",
                "--e------",
                "--e------",
                'a',
                "plateDraconiumAwakened",
                'b',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 1, missing),
                'c',
                getModItem(DraconicEvolution.ID, "awakenedCore", 1, 0, missing),
                'd',
                getModItem(BloodMagic.ID, "boundAxe", 1, 0, missing),
                'e',
                "ingotDraconium");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "draconicHoe", 1, 0, missing),
                "-aaaa----",
                "b--aaa---",
                "----aaac-",
                "-----dea-",
                "-----cda-",
                "----c----",
                "---c-----",
                "--c------",
                "-c-------",
                'a',
                "plateDraconiumAwakened",
                'b',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 1, missing),
                'c',
                "ingotDraconium",
                'd',
                getModItem(DraconicEvolution.ID, "awakenedCore", 1, 0, missing),
                'e',
                getModItem(BloodArsenal.ID, "bound_sickle", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "draconicDistructionStaff", 1, 0, missing),
                "---aba---",
                "-aacdcaa-",
                "a--efg--a",
                "----f----",
                "----f----",
                "----f----",
                "----f----",
                "----f----",
                "----f----",
                'a',
                "plateDraconiumAwakened",
                'b',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 1, missing),
                'c',
                getModItem(DraconicEvolution.ID, "awakenedCore", 1, 0, missing),
                'd',
                getModItem(DraconicEvolution.ID, "draconicShovel", 1, 0, missing),
                'e',
                getModItem(DraconicEvolution.ID, "draconicPickaxe", 1, 0, missing),
                'f',
                "ingotDraconiumAwakened",
                'g',
                getModItem(DraconicEvolution.ID, "draconicSword", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "energyInfuser", 1, 0, missing),
                "---------",
                "----a----",
                "---bcb---",
                "---ded---",
                "---efe---",
                "--bdedb--",
                "--ggcgg--",
                "---------",
                "---------",
                'a',
                "craftingToolScrewdriver",
                'b',
                "screwDraconium",
                'c',
                getModItem(DraconicEvolution.ID, "particleGenerator", 1, 0, missing),
                'd',
                getModItem(DraconicEvolution.ID, "infusedObsidian", 1, 0, missing),
                'e',
                getModItem(DraconicEvolution.ID, "wyvernCore", 1, 0, missing),
                'f',
                getModItem(DraconicEvolution.ID, "draconiumFluxCapacitor", 1, 0, missing),
                'g',
                "blockDraconium");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "particleGenerator", 1, 0, missing),
                "---------",
                "---abcba-",
                "---b---b-",
                "-abcba-c-",
                "-b-bdb-b-",
                "-c-abcba-",
                "-b---b---",
                "-abcba---",
                "---------",
                'a',
                getModItem(Minecraft.ID, "obsidian", 1, 0, missing),
                'b',
                "stickBlaze",
                'c',
                "itemVibrantCrystal",
                'd',
                getModItem(Minecraft.ID, "comparator", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "magnet", 1, 1, missing),
                "---------",
                "---------",
                "-abbbbb--",
                "------b--",
                "------b--",
                "------b--",
                "-cbbbbb--",
                "---------",
                "---------",
                'a',
                getModItem(DraconicEvolution.ID, "magnet", 1, 0, missing),
                'b',
                "ingotNeodymiumMagnetic",
                'c',
                getModItem(EnderIO.ID, "itemMagnet", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "reactorCraftingPart", 1, 1, missing),
                "---------",
                "---------",
                "---------",
                "-abbbbba-",
                "-cbbbbbc-",
                "-abbbbba-",
                "---------",
                "---------",
                "---------",
                'a',
                "plateDraconiumAwakened",
                'b',
                getModItem(NewHorizonsCoreMod.ID, "item.EngravedEnergyChip", 1, 0, missing),
                'c',
                getModItem(DraconicEvolution.ID, "wyvernCore", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "reactorCraftingPart", 1, 2, missing),
                "---------",
                "---------",
                "---------",
                "-abbbbba-",
                "-cbbbbbc-",
                "-abbbbba-",
                "---------",
                "---------",
                "---------",
                'a',
                "plateDraconium",
                'b',
                getModItem(NewHorizonsCoreMod.ID, "item.EngravedDiamondCrystalChip", 1, 0, missing),
                'c',
                getModItem(DraconicEvolution.ID, "draconicCore", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "reactorCraftingPart", 1, 3, missing),
                "---------",
                "---------",
                "-aabbbbb-",
                "-accccc--",
                "-deeeefg-",
                "-accccc--",
                "-aabbbbb-",
                "---------",
                "---------",
                'a',
                "stickLongDraconium",
                'b',
                getModItem(DraconicEvolution.ID, "reactorCraftingPart", 1, 2, missing),
                'c',
                getModItem(DraconicEvolution.ID, "reactorCraftingPart", 1, 1, missing),
                'd',
                getModItem(DraconicEvolution.ID, "draconium", 1, 2, missing),
                'e',
                getModItem(GregTech.ID, "gt.blockcasings4", 1, 7, missing),
                'f',
                getModItem(DraconicEvolution.ID, "wyvernCore", 1, 0, missing),
                'g',
                "plateDraconium");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "reactorCraftingPart", 1, 4, missing),
                "---------",
                "---aba---",
                "--aacaa--",
                "-aadedaa-",
                "-bcefecb-",
                "-aadedaa-",
                "--aacaa--",
                "---aba---",
                "---------",
                'a',
                "stickRoseGold",
                'b',
                getModItem(DraconicEvolution.ID, "reactorCraftingPart", 1, 2, missing),
                'c',
                getModItem(DraconicEvolution.ID, "wyvernCore", 1, 0, missing),
                'd',
                getModItem(DraconicEvolution.ID, "reactorCraftingPart", 1, 1, missing),
                'e',
                "lensNetherStar",
                'f',
                "lensDiamond");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "reactorCraftingPart", 1, 0, missing),
                "aaaaaaaaa",
                "aa-----aa",
                "a-aaaaa-a",
                "a-abbba-a",
                "a-abcba-a",
                "a-abbba-a",
                "a-aaaaa-a",
                "aa-----aa",
                "aaaaaaaaa",
                'a',
                "plateBlackPlutonium",
                'b',
                "plateDraconiumAwakened",
                'c',
                getModItem(DraconicEvolution.ID, "awakenedCore", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "reactorStabilizer", 1, 0, missing),
                "---------",
                "---------",
                "-abbbbba-",
                "-bcdbdcb-",
                "-efghifb-",
                "-bcdbdcb-",
                "-abbbbba-",
                "---------",
                "---------",
                'a',
                "plateBlackPlutonium",
                'b',
                "plateDraconiumAwakened",
                'c',
                getModItem(NewHorizonsCoreMod.ID, "item.EngravedManyullynCrystalChip", 1, 0, missing),
                'd',
                getModItem(DraconicEvolution.ID, "draconiumFluxCapacitor", 1, 1, missing),
                'e',
                getModItem(DraconicEvolution.ID, "reactorCraftingPart", 1, 0, missing),
                'f',
                getModItem(DraconicEvolution.ID, "chaoticCore", 1, 0, missing),
                'g',
                getModItem(DraconicEvolution.ID, "reactorCraftingPart", 1, 4, missing),
                'h',
                "blockCosmicNeutronium",
                'i',
                getModItem(DraconicEvolution.ID, "reactorCraftingPart", 1, 3, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "reactorCore", 1, 0, missing),
                "---------",
                "---aaa---",
                "--abcba--",
                "-abcdcba-",
                "-acdedca-",
                "-abcdcba-",
                "--abcba--",
                "---aaa---",
                "---------",
                'a',
                "plateDraconiumAwakened",
                'b',
                "blockDraconium",
                'c',
                getModItem(DraconicEvolution.ID, "draconium", 1, 2, missing),
                'd',
                "blockDraconiumAwakened",
                'e',
                getModItem(DraconicEvolution.ID, "chaosShard", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "draconium", 1, 1, missing),
                "---------",
                "---------",
                "--abcba--",
                "--bdedb--",
                "--cecec--",
                "--bdedb--",
                "--abcba--",
                "---------",
                "---------",
                'a',
                createItemStack(DraconicEvolution.ID, "mobSoul", 1, 0, "{Name:\"Any\"}", missing),
                'b',
                "plateDraconium",
                'c',
                getModItem(DraconicEvolution.ID, "wyvernCore", 1, 0, missing),
                'd',
                "blockDraconium",
                'e',
                getModItem(DraconicEvolution.ID, "draconium", 1, 2, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "teleporterStand", 1, 0, missing),
                "---------",
                "---------",
                "--abcba--",
                "---aaa---",
                "----d----",
                "----d----",
                "----d----",
                "---ede---",
                "--aaaaa--",
                'a',
                "slabStone",
                'b',
                "stickBlaze",
                'c',
                getModItem(DraconicEvolution.ID, "teleporterMKI", 1, 0, missing),
                'd',
                getModItem(DraconicEvolution.ID, "infusedObsidian", 1, 0, missing),
                'e',
                "stone");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "dislocatorReceptacle", 1, 0, missing),
                "---------",
                "---------",
                "--abcba--",
                "--bdbdb--",
                "--cbebc--",
                "--bdbdb--",
                "--abcba--",
                "---------",
                "---------",
                'a',
                "plateSilver",
                'b',
                "plateDraconium",
                'c',
                getModItem(DraconicEvolution.ID, "draconicCore", 1, 0, missing),
                'd',
                getModItem(DraconicEvolution.ID, "infusedObsidian", 1, 0, missing),
                'e',
                getModItem(DraconicEvolution.ID, "teleporterStand", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "energyStorageCore", 1, 0, missing),
                "---------",
                "---------",
                "--aabaa--",
                "--aacaa--",
                "--bcdcb--",
                "--aacaa--",
                "--aabaa--",
                "---------",
                "---------",
                'a',
                "plateDraconium",
                'b',
                getModItem(DraconicEvolution.ID, "draconiumFluxCapacitor", 1, 0, missing),
                'c',
                getModItem(DraconicEvolution.ID, "wyvernCore", 1, 0, missing),
                'd',
                getModItem(DraconicEvolution.ID, "draconium", 1, 2, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "energyPylon", 1, 0, missing),
                "---------",
                "---------",
                "--abcba--",
                "--bcdcb--",
                "--cdedc--",
                "--bcdcb--",
                "--abcba--",
                "---------",
                "---------",
                'a',
                "gemEnderEye",
                'b',
                "plateEmerald",
                'c',
                "plateDiamond",
                'd',
                getModItem(DraconicEvolution.ID, "draconicCore", 1, 0, missing),
                'e',
                "blockDraconium");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "energyCrystal", 1, 0, missing),
                "---------",
                "----a----",
                "----b----",
                "---bbb---",
                "---aca---",
                "---bbb---",
                "----b----",
                "----a----",
                "---------",
                'a',
                "gemExquisiteDiamond",
                'b',
                "plateDraconium",
                'c',
                getModItem(DraconicEvolution.ID, "draconicCore", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "energyCrystal", 1, 1, missing),
                "---------",
                "----a----",
                "----b----",
                "---cdc---",
                "---beb---",
                "---cdc---",
                "----b----",
                "----a----",
                "---------",
                'a',
                "plateDraconiumAwakened",
                'b',
                getModItem(DraconicEvolution.ID, "draconicCore", 1, 0, missing),
                'c',
                "gemExquisiteRuby",
                'd',
                getModItem(DraconicEvolution.ID, "wyvernCore", 1, 0, missing),
                'e',
                getModItem(DraconicEvolution.ID, "energyCrystal", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "wrench", 1, 0, missing),
                "-----a---",
                "----aa---",
                "----ab---",
                "----abbaa",
                "---ccaaa-",
                "--ccc----",
                "-ccc-----",
                "ccc------",
                "dc-------",
                'a',
                "plateDraconium",
                'b',
                "plateDiamond",
                'c',
                "stickBlaze",
                'd',
                getModItem(DraconicEvolution.ID, "draconicCore", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "generator", 1, 3, missing),
                "---------",
                "---------",
                "--abbba--",
                "--bcdcb--",
                "--befeb--",
                "--abbba--",
                "---------",
                "---------",
                "---------",
                'a',
                "plateSteel",
                'b',
                "ingotBrickNether",
                'c',
                getModItem(GregTech.ID, "gt.metaitem.01", 1, 32500, missing),
                'd',
                getModItem(DraconicEvolution.ID, "draconicCore", 1, 0, missing),
                'e',
                getModItem(BuildCraftTransport.ID, "item.buildcraftPipe.pipepowercobblestone", 1, 0, missing),
                'f',
                "craftingIronFurnace");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "playerDetectorAdvanced", 1, 0, missing),
                "---------",
                "---------",
                "---------",
                "--abcba--",
                "--adeda--",
                "--abcba--",
                "---------",
                "---------",
                "---------",
                'a',
                "plateDraconium",
                'b',
                "gemEnderEye",
                'c',
                getModItem(Minecraft.ID, "compass", 1, 0, missing),
                'd',
                getModItem(Minecraft.ID, "skull", 1, 1, missing),
                'e',
                getModItem(DraconicEvolution.ID, "playerDetector", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "weatherController", 1, 0, missing),
                "---------",
                "---------",
                "--abcda--",
                "--aefea--",
                "--aghga--",
                "--aaaaa--",
                "---------",
                "---------",
                "---------",
                'a',
                "plateDraconium",
                'b',
                getModItem(DraconicEvolution.ID, "rainSensor", 1, 0, missing),
                'c',
                getModItem(OpenBlocks.ID, "bigbutton", 1, 0, missing),
                'd',
                getModItem(Minecraft.ID, "daylight_detector", 1, 0, missing),
                'e',
                getModItem(DraconicEvolution.ID, "draconicCore", 1, 0, missing),
                'f',
                getModItem(Forestry.ID, "factory", 1, 7, missing),
                'g',
                "stickBlaze",
                'h',
                "gemExquisiteEmerald");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "sunDial", 1, 0, missing),
                "---------",
                "---------",
                "--aabaa--",
                "--ccdcc--",
                "--cefec--",
                "--cghgc--",
                "--ccccc--",
                "---------",
                "---------",
                'a',
                "plateDraconium",
                'b',
                getModItem(Minecraft.ID, "dragon_egg", 1, 0, missing),
                'c',
                "plateDraconiumAwakened",
                'd',
                getModItem(DraconicEvolution.ID, "dragonHeart", 1, 0, missing),
                'e',
                getModItem(DraconicEvolution.ID, "wyvernCore", 1, 0, missing),
                'f',
                getModItem(DraconicEvolution.ID, "chaosShard", 1, 0, missing),
                'g',
                getModItem(DraconicEvolution.ID, "awakenedCore", 1, 0, missing),
                'h',
                getModItem(DraconicEvolution.ID, "weatherController", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "grinder", 1, 3, missing),
                "---------",
                "---------",
                "--aaaaa--",
                "--abcba--",
                "--adeda--",
                "--aaaaa--",
                "---------",
                "---------",
                "---------",
                'a',
                "plateDraconium",
                'b',
                getModItem(Thaumcraft.ID, "ItemSwordElemental", 1, 0, missing),
                'c',
                getModItem(EnderIO.ID, "blockKillerJoe", 1, 0, missing),
                'd',
                getModItem(GregTech.ID, "gt.metaitem.01", 1, 32604, missing),
                'e',
                getModItem(EnderIO.ID, "blockCapBank", 1, 3, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "flowGate", 1, 6, missing),
                "---------",
                "---------",
                "--aaaaa--",
                "--aabaa--",
                "--cdedc--",
                "--aabaa--",
                "--aaaaa--",
                "---------",
                "---------",
                'a',
                "plateDraconium",
                'b',
                getModItem(DraconicEvolution.ID, "draconicCore", 1, 0, missing),
                'c',
                "pipeHugeNeutronium",
                'd',
                getModItem(ProjectRedIntegration.ID, "projectred.integration.gate", 1, 26, missing),
                'e',
                getModItem(DraconicEvolution.ID, "wyvernCore", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "flowGate", 1, 0, missing),
                "---------",
                "---------",
                "--aaaaa--",
                "--aabaa--",
                "--cdedc--",
                "--aabaa--",
                "--aaaaa--",
                "---------",
                "---------",
                'a',
                "plateDraconium",
                'b',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 0, missing),
                'c',
                getModItem(EnderIO.ID, "itemPowerConduit", 1, 2, missing),
                'd',
                getModItem(ProjectRedIntegration.ID, "projectred.integration.gate", 1, 26, missing),
                'e',
                getModItem(DraconicEvolution.ID, "wyvernCore", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "reactorEnergyInjector", 1, 0, missing),
                "---------",
                "---------",
                "--a-b-a--",
                "--acbca--",
                "--dcecd--",
                "--fffff--",
                "--fffff--",
                "---------",
                "---------",
                'a',
                getModItem(DraconicEvolution.ID, "reactorCraftingPart", 1, 2, missing),
                'b',
                "plateDraconiumAwakened",
                'c',
                getModItem(DraconicEvolution.ID, "reactorCraftingPart", 1, 1, missing),
                'd',
                getModItem(DraconicEvolution.ID, "draconiumEnergyCore", 1, 0, missing),
                'e',
                getModItem(DraconicEvolution.ID, "wyvernCore", 1, 0, missing),
                'f',
                "plateDraconium");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(DraconicEvolution.ID, "upgradeModifier", 1, 0, missing),
                "---------",
                "---------",
                "--aaaaa--",
                "--abcba--",
                "--acdca--",
                "--abcba--",
                "--aaaaa--",
                "---------",
                "---------",
                'a',
                "plateDraconium",
                'b',
                "gearDraconium",
                'c',
                getModItem(DraconicEvolution.ID, "draconicCore", 1, 0, missing),
                'd',
                getModItem(GregTech.ID, "gt.metaitem.01", 1, 32604, missing));

        GT_Values.RA.stdBuilder()
                .itemInputs(
                        getModItem(GregTech.ID, "gt.metaitem.01", 4, 17299, missing),
                        getModItem(DraconicEvolution.ID, "draconiumDust", 1, 0, missing))
                .itemOutputs(getModItem(DraconicEvolution.ID, "infoTablet", 1, 0, missing)).noFluidInputs()
                .noFluidOutputs().duration(400).eut(480).addTo(sAssemblerRecipes);
        GT_Values.RA.stdBuilder()
                .itemInputs(
                        getModItem(DraconicEvolution.ID, "energyCrystal", 1, 0, missing),
                        getModItem(DraconicEvolution.ID, "particleGenerator", 2, 0, missing))
                .itemOutputs(getModItem(DraconicEvolution.ID, "energyCrystal", 1, 4, missing))
                .fluidInputs(FluidRegistry.getFluidStack("molten.enderium", 864)).noFluidOutputs().duration(1200)
                .eut(1024).addTo(sAssemblerRecipes);
        GT_Values.RA.stdBuilder()
                .itemInputs(
                        getModItem(DraconicEvolution.ID, "energyCrystal", 1, 1, missing),
                        getModItem(DraconicEvolution.ID, "particleGenerator", 2, 0, missing))
                .itemOutputs(getModItem(DraconicEvolution.ID, "energyCrystal", 1, 5, missing))
                .fluidInputs(FluidRegistry.getFluidStack("molten.enderium", 864)).noFluidOutputs().duration(2400)
                .eut(4096).addTo(sAssemblerRecipes);
        GT_Values.RA.stdBuilder()
                .itemInputs(
                        getModItem(Minecraft.ID, "arrow", 1, 0, missing),
                        getModItem(Minecraft.ID, "ender_pearl", 1, 0, missing))
                .itemOutputs(getModItem(DraconicEvolution.ID, "enderArrow", 1, 0, missing)).noFluidInputs()
                .noFluidOutputs().duration(200).eut(480).addTo(sAssemblerRecipes);
        GT_Values.RA.stdBuilder()
                .itemInputs(
                        getModItem(Railcraft.ID, "detector", 1, 5, missing),
                        getModItem(DraconicEvolution.ID, "draconicCore", 1, 0, missing))
                .itemOutputs(getModItem(DraconicEvolution.ID, "playerDetector", 1, 0, missing)).noFluidInputs()
                .noFluidOutputs().duration(200).eut(480).addTo(sAssemblerRecipes);
        GT_Values.RA.stdBuilder()
                .itemInputs(
                        getModItem(ProjectRedIntegration.ID, "projectred.integration.gate", 1, 16, missing),
                        getModItem(GregTech.ID, "gt.metaitem.01", 1, 17975, missing))
                .itemOutputs(getModItem(DraconicEvolution.ID, "rainSensor", 1, 0, missing)).noFluidInputs()
                .noFluidOutputs().duration(200).eut(480).addTo(sAssemblerRecipes);
        GT_Values.RA.stdBuilder()
                .itemInputs(
                        getModItem(Minecraft.ID, "obsidian", 1, 0, missing),
                        getModItem(Minecraft.ID, "blaze_powder", 1, 0, missing))
                .itemOutputs(getModItem(DraconicEvolution.ID, "infusedObsidian", 1, 0, missing))
                .fluidInputs(FluidRegistry.getFluidStack("molten.draconium", 144)).noFluidOutputs().duration(1200)
                .eut(1920).specialValue(7500).addTo(sBlastRecipes);
        GT_Values.RA.stdBuilder().itemInputs(getModItem(DraconicEvolution.ID, "chaosShard", 1, 0, missing))
                .itemOutputs(getModItem(DraconicEvolution.ID, "chaosFragment", 9, 2, missing)).noFluidInputs()
                .noFluidOutputs().duration(100).eut(480).addTo(sHammerRecipes);
        GT_Values.RA.stdBuilder().itemInputs(getModItem(DraconicEvolution.ID, "chaosFragment", 1, 2, missing))
                .itemOutputs(getModItem(DraconicEvolution.ID, "chaosFragment", 9, 1, missing)).noFluidInputs()
                .noFluidOutputs().duration(50).eut(480).addTo(sHammerRecipes);
        GT_Values.RA.stdBuilder().itemInputs(getModItem(DraconicEvolution.ID, "chaosFragment", 1, 1, missing))
                .itemOutputs(getModItem(DraconicEvolution.ID, "chaosFragment", 9, 0, missing)).noFluidInputs()
                .noFluidOutputs().duration(25).eut(480).addTo(sHammerRecipes);
        GT_Values.RA.stdBuilder()
                .itemInputs(
                        getModItem(DraconicEvolution.ID, "safetyMatch", 16, 1000, missing),
                        getModItem(GregTech.ID, "gt.metaitem.01", 1, 18879, missing))
                .itemOutputs(getModItem(DraconicEvolution.ID, "safetyMatch", 1, 0, missing)).noFluidInputs()
                .noFluidOutputs().duration(64).eut(16).addTo(sBoxinatorRecipes);

    }
}
