package com.dreammaster.scripts;

import static gregtech.api.util.GT_ModHandler.addShapelessCraftingRecipe;
import static gregtech.api.util.GT_ModHandler.getModItem;
import static gregtech.api.util.GT_Recipe.GT_Recipe_Map.*;

import java.util.Arrays;
import java.util.List;

import net.minecraftforge.fluids.FluidRegistry;

import fox.spiteful.avaritia.crafting.ExtremeCraftingManager;
import gregtech.api.enums.GT_Values;
import gregtech.api.enums.Mods;

public class ScriptDraconicEvolution implements IScriptLoader {

    @Override
    public String getScriptName() {
        return "Draconic Evolution";
    }

    @Override
    public List<String> getDependencies() {
        return Arrays.asList(Mods.DraconicEvolution.ID);
    }

    @Override
    public void loadRecipes() {
        addShapedRecipe(
                getModItem("DraconicEvolution", "magnet", 1, 0, missing),
                new Object[] { "blockSteelMagnetic", "ingotSteelMagnetic", "ingotSteelMagnetic", null, null,
                        getModItem("gregtech", "gt.metaitem.01", 1, 32518, missing), "blockSteelMagnetic",
                        "ingotSteelMagnetic", "ingotSteelMagnetic" });
        addShapedRecipe(
                getModItem("DraconicEvolution", "draconiumChest", 1, 0, missing),
                new Object[] { "plateObsidian", getModItem("EnderIO", "blockCapBank", 1, 1, missing), "plateObsidian",
                        getModItem("IC2", "blockMachine", 1, 1, missing),
                        getModItem("avaritiaddons", "CompressedChest", 1, 0, missing),
                        getModItem("gregtech", "gt.metaitem.01", 1, 32744, missing), "plateObsidian", "plateObsidian",
                        "plateObsidian" });
        addShapelessCraftingRecipe(
                getModItem("DraconicEvolution", "safetyMatch", 1, 1000, missing),
                new Object[] { getModItem("gregtech", "gt.metaitem.01", 1, 32471, missing), "dustDraconium" });
        addShapedRecipe(
                getModItem("DraconicEvolution", "xRayBlock", 8, 0, missing),
                new Object[] { getModItem("minecraft", "glass_pane", 1, 0, missing),
                        getModItem("gregtech", "gt.metaitem.01", 1, 17330, missing),
                        getModItem("minecraft", "glass_pane", 1, 0, missing),
                        getModItem("gregtech", "gt.metaitem.01", 1, 17330, missing),
                        getModItem("gregtech", "gt.metaitem.02", 1, 29500, missing),
                        getModItem("gregtech", "gt.metaitem.01", 1, 17330, missing),
                        getModItem("minecraft", "glass_pane", 1, 0, missing),
                        getModItem("gregtech", "gt.metaitem.01", 1, 17330, missing),
                        getModItem("minecraft", "glass_pane", 1, 0, missing) });

        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "teleporterMKI", 1, 0, missing),
                "----a----",
                "---bbb---",
                "--baaab--",
                "abacdcaba",
                "-badedab-",
                "-bacdcab-",
                "-bbaaabb-",
                "-aabbbaa-",
                "a-------a",
                'a',
                "plateDenseDraconium",
                'b',
                "plateDenseNaquadahAlloy",
                'c',
                getModItem("gregtech", "gt.metaitem.03", 1, 32059, missing),
                'd',
                "plateEuropium",
                'e',
                getModItem("DraconicEvolution", "draconicCore", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "teleporterMKII", 1, 0, missing),
                "---aaa---",
                "-aabcbaa-",
                "-adefeda-",
                "aghaiahga",
                "acaigiaca",
                "abaaiaaba",
                "-agefega-",
                "-aabcbaa-",
                "---aaa---",
                'a',
                "plateDenseDraconium",
                'b',
                "plateDenseDraconiumAwakened",
                'c',
                createItemStack("TGregworks", "tGregToolPartLargePlate", 1, 1669, "{material:\"Infinity\"}", missing),
                'd',
                getModItem("gregtech", "gt.metaitem.01", 1, 32677, missing),
                'e',
                getModItem("gregtech", "gt.metaitem.01", 1, 32687, missing),
                'f',
                "blockAmericium",
                'g',
                getModItem("DraconicEvolution", "teleporterMKI", 1, 0, missing),
                'h',
                getModItem("gregtech", "gt.metaitem.01", 1, 32697, missing),
                'i',
                getModItem("DraconicEvolution", "awakenedCore", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "draconiumFluxCapacitor", 1, 0, missing),
                "---------",
                "----a----",
                "--abcba--",
                "--badab--",
                "-acdedca-",
                "--badab--",
                "--abcba--",
                "----a----",
                "---------",
                'a',
                "plateDraconium",
                'b',
                "wireGt02Superconductor",
                'c',
                getModItem("DraconicEvolution", "draconiumEnergyCore", 1, 0, missing),
                'd',
                createItemStack("EnderIO", "blockCapBank", 1, 3, "{type:\"VIBRANT\",storedEnergyRF:0}", missing),
                'e',
                getModItem("DraconicEvolution", "wyvernCore", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "wyvernSword", 1, 0, missing),
                "-------aa",
                "------aba",
                "-----aca-",
                "----ada--",
                "-e-ada---",
                "--efa----",
                "--ce-----",
                "-c--e----",
                "c--------",
                'a',
                "plateDraconium",
                'b',
                getModItem("DraconicEvolution", "draconiumEnergyCore", 1, 0, missing),
                'c',
                "ingotDraconium",
                'd',
                getModItem("DraconicEvolution", "wyvernCore", 1, 0, missing),
                'e',
                "ingotNeutronium",
                'f',
                getModItem("AWWayofTime", "energySword", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "wyvernPickaxe", 1, 0, missing),
                "-aaabaaa-",
                "accdedcca",
                "aa--f--aa",
                "----f----",
                "----f----",
                "----f----",
                "----f----",
                "----f----",
                "----f----",
                'a',
                "plateDraconium",
                'b',
                getModItem("DraconicEvolution", "draconiumEnergyCore", 1, 0, missing),
                'c',
                "ingotDraconium",
                'd',
                getModItem("DraconicEvolution", "wyvernCore", 1, 0, missing),
                'e',
                getModItem("AWWayofTime", "boundPickaxe", 1, 0, missing),
                'f',
                "ingotNeutronium");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "wyvernShovel", 1, 0, missing),
                "------aab",
                "-----acda",
                "------aca",
                "-----e-a-",
                "----e----",
                "---e-----",
                "--e------",
                "-e-------",
                "e--------",
                'a',
                "plateDraconium",
                'b',
                getModItem("DraconicEvolution", "draconiumEnergyCore", 1, 0, missing),
                'c',
                getModItem("DraconicEvolution", "wyvernCore", 1, 0, missing),
                'd',
                getModItem("AWWayofTime", "boundShovel", 1, 0, missing),
                'e',
                "ingotNeutronium");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "wyvernBow", 1, 0, missing),
                "---ab----",
                "--a-c----",
                "-a--c----",
                "a---c----",
                "d---e----",
                "a---c----",
                "-a--c----",
                "--a-c----",
                "---ab----",
                'a',
                "plateDraconium",
                'b',
                getModItem("DraconicEvolution", "wyvernCore", 1, 0, missing),
                'c',
                "ingotNeutronium",
                'd',
                getModItem("DraconicEvolution", "draconiumEnergyCore", 1, 0, missing),
                'e',
                getModItem("BloodArsenal", "bound_bow", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "wyvernHelm", 1, 0, missing),
                "--aaaaa--",
                "-abbcbba-",
                "-a-ded-a-",
                "-abbbbba-",
                "-abbbbba-",
                "-ab---ba-",
                "---------",
                "---------",
                "---------",
                'a',
                "plateNeutronium",
                'b',
                "plateDraconium",
                'c',
                getModItem("DraconicEvolution", "draconiumEnergyCore", 1, 0, missing),
                'd',
                getModItem("DraconicEvolution", "wyvernCore", 1, 0, missing),
                'e',
                getModItem("AWWayofTime", "sanguineHelmet", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "wyvernChest", 1, 0, missing),
                "-aa---aa-",
                "aaa---aaa",
                "aaa---aaa",
                "-abbbbba-",
                "-abbcbba-",
                "-abdedba-",
                "-abbbbba-",
                "-abbbbba-",
                "--aaaaa--",
                'a',
                "plateNeutronium",
                'b',
                "plateDraconium",
                'c',
                getModItem("DraconicEvolution", "draconiumEnergyCore", 1, 0, missing),
                'd',
                getModItem("DraconicEvolution", "wyvernCore", 1, 0, missing),
                'e',
                getModItem("AWWayofTime", "sanguineRobe", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "wyvernLeggs", 1, 0, missing),
                "aaaaaaaaa",
                "abbbcbbba",
                "abaadaaba",
                "aba---aba",
                "aea---aea",
                "aba---aba",
                "aba---aba",
                "aba---aba",
                "aaa---aaa",
                'a',
                "plateNeutronium",
                'b',
                "plateDraconium",
                'c',
                getModItem("DraconicEvolution", "draconiumEnergyCore", 1, 0, missing),
                'd',
                getModItem("AWWayofTime", "sanguinePants", 1, 0, missing),
                'e',
                getModItem("DraconicEvolution", "wyvernCore", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "wyvernBoots", 1, 0, missing),
                "-aaabaaa-",
                "-acadaca-",
                "-aca-aca-",
                "-aca-aca-",
                "aeca-acea",
                "aaaa-aaaa",
                "---------",
                "---------",
                "---------",
                'a',
                "plateNeutronium",
                'b',
                getModItem("AWWayofTime", "sanguineBoots", 1, 0, missing),
                'c',
                "plateDraconium",
                'd',
                getModItem("DraconicEvolution", "draconiumEnergyCore", 1, 0, missing),
                'e',
                getModItem("DraconicEvolution", "wyvernCore", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "draconiumFluxCapacitor", 1, 1, missing),
                "---------",
                "----a----",
                "--abcba--",
                "--badab--",
                "-aedfdea-",
                "--badab--",
                "--abeba--",
                "----a----",
                "---------",
                'a',
                "plateDraconiumAwakened",
                'b',
                "wireGt04Superconductor",
                'c',
                getModItem("DraconicEvolution", "awakenedCore", 1, 0, missing),
                'd',
                getModItem("dreamcraft", "item.EnrichedNaquadriaSunnariumAlloy", 1, 0, missing),
                'e',
                getModItem("DraconicEvolution", "draconiumEnergyCore", 1, 1, missing),
                'f',
                getModItem("DraconicEvolution", "draconiumFluxCapacitor", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "draconicSword", 1, 0, missing),
                "-------aa",
                "------aba",
                "-----aca-",
                "----ada--",
                "-e-ada---",
                "--efa----",
                "--ce-----",
                "-c--e----",
                "c--------",
                'a',
                "plateDraconiumAwakened",
                'b',
                getModItem("DraconicEvolution", "draconiumEnergyCore", 1, 1, missing),
                'c',
                "ingotDraconiumAwakened",
                'd',
                getModItem("DraconicEvolution", "awakenedCore", 1, 0, missing),
                'e',
                "ingotDraconium",
                'f',
                getModItem("DraconicEvolution", "wyvernSword", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "draconicPickaxe", 1, 0, missing),
                "-aaabaaa-",
                "accdedcca",
                "aa--f--aa",
                "----f----",
                "----f----",
                "----f----",
                "----f----",
                "----f----",
                "----f----",
                'a',
                "plateDraconiumAwakened",
                'b',
                getModItem("DraconicEvolution", "draconiumEnergyCore", 1, 1, missing),
                'c',
                "ingotDraconiumAwakened",
                'd',
                getModItem("DraconicEvolution", "awakenedCore", 1, 0, missing),
                'e',
                getModItem("DraconicEvolution", "wyvernPickaxe", 1, 0, missing),
                'f',
                "ingotDraconium");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "draconicShovel", 1, 0, missing),
                "------aab",
                "-----acda",
                "------aca",
                "-----e-a-",
                "----e----",
                "---e-----",
                "--e------",
                "-e-------",
                "e--------",
                'a',
                "plateDraconiumAwakened",
                'b',
                getModItem("DraconicEvolution", "draconiumEnergyCore", 1, 1, missing),
                'c',
                getModItem("DraconicEvolution", "awakenedCore", 1, 0, missing),
                'd',
                getModItem("DraconicEvolution", "wyvernShovel", 1, 0, missing),
                'e',
                "ingotDraconium");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "draconicBow", 1, 0, missing),
                "---ab----",
                "--a-c----",
                "-a--c----",
                "a---c----",
                "d---e----",
                "a---c----",
                "-a--c----",
                "--a-c----",
                "---ab----",
                'a',
                "plateDraconiumAwakened",
                'b',
                getModItem("DraconicEvolution", "awakenedCore", 1, 0, missing),
                'c',
                "ingotDraconium",
                'd',
                getModItem("DraconicEvolution", "draconiumEnergyCore", 1, 1, missing),
                'e',
                getModItem("DraconicEvolution", "wyvernBow", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "draconicHelm", 1, 0, missing),
                "--aaaaa--",
                "-abbcbba-",
                "-a-ded-a-",
                "-abbbbba-",
                "-abbbbba-",
                "-ab---ba-",
                "---------",
                "---------",
                "---------",
                'a',
                "plateDraconium",
                'b',
                "plateDraconiumAwakened",
                'c',
                getModItem("DraconicEvolution", "draconiumEnergyCore", 1, 1, missing),
                'd',
                getModItem("DraconicEvolution", "awakenedCore", 1, 0, missing),
                'e',
                getModItem("DraconicEvolution", "wyvernHelm", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "draconicChest", 1, 0, missing),
                "-aa---aa-",
                "aaa---aaa",
                "aaa---aaa",
                "-abbbbba-",
                "-abbcbba-",
                "-abdedba-",
                "-abbbbba-",
                "-abbbbba-",
                "--aaaaa--",
                'a',
                "plateDraconium",
                'b',
                "plateDraconiumAwakened",
                'c',
                getModItem("DraconicEvolution", "awakenedCore", 1, 0, missing),
                'd',
                getModItem("DraconicEvolution", "draconiumEnergyCore", 1, 1, missing),
                'e',
                getModItem("DraconicEvolution", "wyvernChest", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "draconicLeggs", 1, 0, missing),
                "aaaaaaaaa",
                "abbbcbbba",
                "abaadaaba",
                "aba---aba",
                "aea---aea",
                "aba---aba",
                "aba---aba",
                "aba---aba",
                "aaa---aaa",
                'a',
                "plateDraconium",
                'b',
                "plateDraconiumAwakened",
                'c',
                getModItem("DraconicEvolution", "draconiumEnergyCore", 1, 1, missing),
                'd',
                getModItem("DraconicEvolution", "wyvernLeggs", 1, 0, missing),
                'e',
                getModItem("DraconicEvolution", "awakenedCore", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "draconicBoots", 1, 0, missing),
                "-aaabaaa-",
                "-acadaca-",
                "-aca-aca-",
                "-aca-aca-",
                "aeca-acea",
                "aaaa-aaaa",
                "---------",
                "---------",
                "---------",
                'a',
                "plateDraconium",
                'b',
                getModItem("DraconicEvolution", "wyvernBoots", 1, 0, missing),
                'c',
                "plateDraconiumAwakened",
                'd',
                getModItem("DraconicEvolution", "draconiumEnergyCore", 1, 1, missing),
                'e',
                getModItem("DraconicEvolution", "awakenedCore", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "draconicAxe", 1, 0, missing),
                "-a-------",
                "abaaa----",
                "acdc-----",
                "-ae------",
                "--e------",
                "--e------",
                "--e------",
                "--e------",
                "--e------",
                'a',
                "plateDraconiumAwakened",
                'b',
                getModItem("DraconicEvolution", "draconiumEnergyCore", 1, 1, missing),
                'c',
                getModItem("DraconicEvolution", "awakenedCore", 1, 0, missing),
                'd',
                getModItem("AWWayofTime", "boundAxe", 1, 0, missing),
                'e',
                "ingotDraconium");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "draconicHoe", 1, 0, missing),
                "-aaaa----",
                "b--aaa---",
                "----aaac-",
                "-----dea-",
                "-----cda-",
                "----c----",
                "---c-----",
                "--c------",
                "-c-------",
                'a',
                "plateDraconiumAwakened",
                'b',
                getModItem("DraconicEvolution", "draconiumEnergyCore", 1, 1, missing),
                'c',
                "ingotDraconium",
                'd',
                getModItem("DraconicEvolution", "awakenedCore", 1, 0, missing),
                'e',
                getModItem("BloodArsenal", "bound_sickle", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "draconicDistructionStaff", 1, 0, missing),
                "---aba---",
                "-aacdcaa-",
                "a--efg--a",
                "----f----",
                "----f----",
                "----f----",
                "----f----",
                "----f----",
                "----f----",
                'a',
                "plateDraconiumAwakened",
                'b',
                getModItem("DraconicEvolution", "draconiumEnergyCore", 1, 1, missing),
                'c',
                getModItem("DraconicEvolution", "awakenedCore", 1, 0, missing),
                'd',
                getModItem("DraconicEvolution", "draconicShovel", 1, 0, missing),
                'e',
                getModItem("DraconicEvolution", "draconicPickaxe", 1, 0, missing),
                'f',
                "ingotDraconiumAwakened",
                'g',
                getModItem("DraconicEvolution", "draconicSword", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "energyInfuser", 1, 0, missing),
                "---------",
                "----a----",
                "---bcb---",
                "---ded---",
                "---efe---",
                "--bdedb--",
                "--ggcgg--",
                "---------",
                "---------",
                'a',
                "craftingToolScrewdriver",
                'b',
                "screwDraconium",
                'c',
                getModItem("DraconicEvolution", "particleGenerator", 1, 0, missing),
                'd',
                getModItem("DraconicEvolution", "infusedObsidian", 1, 0, missing),
                'e',
                getModItem("DraconicEvolution", "wyvernCore", 1, 0, missing),
                'f',
                getModItem("DraconicEvolution", "draconiumFluxCapacitor", 1, 0, missing),
                'g',
                "blockDraconium");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "particleGenerator", 1, 0, missing),
                "---------",
                "---abcba-",
                "---b---b-",
                "-abcba-c-",
                "-b-bdb-b-",
                "-c-abcba-",
                "-b---b---",
                "-abcba---",
                "---------",
                'a',
                getModItem("minecraft", "obsidian", 1, 0, missing),
                'b',
                "stickBlaze",
                'c',
                "itemVibrantCrystal",
                'd',
                getModItem("minecraft", "comparator", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "magnet", 1, 1, missing),
                "---------",
                "---------",
                "-abbbbb--",
                "------b--",
                "------b--",
                "------b--",
                "-cbbbbb--",
                "---------",
                "---------",
                'a',
                getModItem("DraconicEvolution", "magnet", 1, 0, missing),
                'b',
                "ingotNeodymiumMagnetic",
                'c',
                getModItem("EnderIO", "itemMagnet", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "reactorCraftingPart", 1, 1, missing),
                "---------",
                "---------",
                "---------",
                "-abbbbba-",
                "-cbbbbbc-",
                "-abbbbba-",
                "---------",
                "---------",
                "---------",
                'a',
                "plateDraconiumAwakened",
                'b',
                getModItem("dreamcraft", "item.EngravedEnergyChip", 1, 0, missing),
                'c',
                getModItem("DraconicEvolution", "wyvernCore", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "reactorCraftingPart", 1, 2, missing),
                "---------",
                "---------",
                "---------",
                "-abbbbba-",
                "-cbbbbbc-",
                "-abbbbba-",
                "---------",
                "---------",
                "---------",
                'a',
                "plateDraconium",
                'b',
                getModItem("dreamcraft", "item.EngravedDiamondCrystalChip", 1, 0, missing),
                'c',
                getModItem("DraconicEvolution", "draconicCore", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "reactorCraftingPart", 1, 3, missing),
                "---------",
                "---------",
                "-aabbbbb-",
                "-accccc--",
                "-deeeefg-",
                "-accccc--",
                "-aabbbbb-",
                "---------",
                "---------",
                'a',
                "stickLongDraconium",
                'b',
                getModItem("DraconicEvolution", "reactorCraftingPart", 1, 2, missing),
                'c',
                getModItem("DraconicEvolution", "reactorCraftingPart", 1, 1, missing),
                'd',
                getModItem("DraconicEvolution", "draconium", 1, 2, missing),
                'e',
                getModItem("gregtech", "gt.blockcasings4", 1, 7, missing),
                'f',
                getModItem("DraconicEvolution", "wyvernCore", 1, 0, missing),
                'g',
                "plateDraconium");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "reactorCraftingPart", 1, 4, missing),
                "---------",
                "---aba---",
                "--aacaa--",
                "-aadedaa-",
                "-bcefecb-",
                "-aadedaa-",
                "--aacaa--",
                "---aba---",
                "---------",
                'a',
                "stickRoseGold",
                'b',
                getModItem("DraconicEvolution", "reactorCraftingPart", 1, 2, missing),
                'c',
                getModItem("DraconicEvolution", "wyvernCore", 1, 0, missing),
                'd',
                getModItem("DraconicEvolution", "reactorCraftingPart", 1, 1, missing),
                'e',
                "lensNetherStar",
                'f',
                "lensDiamond");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "reactorCraftingPart", 1, 0, missing),
                "aaaaaaaaa",
                "aa-----aa",
                "a-aaaaa-a",
                "a-abbba-a",
                "a-abcba-a",
                "a-abbba-a",
                "a-aaaaa-a",
                "aa-----aa",
                "aaaaaaaaa",
                'a',
                "plateBlackPlutonium",
                'b',
                "plateDraconiumAwakened",
                'c',
                getModItem("DraconicEvolution", "awakenedCore", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "reactorStabilizer", 1, 0, missing),
                "---------",
                "---------",
                "-abbbbba-",
                "-bcdbdcb-",
                "-efghifb-",
                "-bcdbdcb-",
                "-abbbbba-",
                "---------",
                "---------",
                'a',
                "plateBlackPlutonium",
                'b',
                "plateDraconiumAwakened",
                'c',
                getModItem("dreamcraft", "item.EngravedManyullynCrystalChip", 1, 0, missing),
                'd',
                getModItem("DraconicEvolution", "draconiumFluxCapacitor", 1, 1, missing),
                'e',
                getModItem("DraconicEvolution", "reactorCraftingPart", 1, 0, missing),
                'f',
                getModItem("DraconicEvolution", "chaoticCore", 1, 0, missing),
                'g',
                getModItem("DraconicEvolution", "reactorCraftingPart", 1, 4, missing),
                'h',
                "blockCosmicNeutronium",
                'i',
                getModItem("DraconicEvolution", "reactorCraftingPart", 1, 3, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "reactorCore", 1, 0, missing),
                "---------",
                "---aaa---",
                "--abcba--",
                "-abcdcba-",
                "-acdedca-",
                "-abcdcba-",
                "--abcba--",
                "---aaa---",
                "---------",
                'a',
                "plateDraconiumAwakened",
                'b',
                "blockDraconium",
                'c',
                getModItem("DraconicEvolution", "draconium", 1, 2, missing),
                'd',
                "blockDraconiumAwakened",
                'e',
                getModItem("DraconicEvolution", "chaosShard", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "draconium", 1, 1, missing),
                "---------",
                "---------",
                "--abcba--",
                "--bdedb--",
                "--cecec--",
                "--bdedb--",
                "--abcba--",
                "---------",
                "---------",
                'a',
                createItemStack("DraconicEvolution", "mobSoul", 1, 0, "{Name:\"Any\"}", missing),
                'b',
                "plateDraconium",
                'c',
                getModItem("DraconicEvolution", "wyvernCore", 1, 0, missing),
                'd',
                "blockDraconium",
                'e',
                getModItem("DraconicEvolution", "draconium", 1, 2, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "teleporterStand", 1, 0, missing),
                "---------",
                "---------",
                "--abcba--",
                "---aaa---",
                "----d----",
                "----d----",
                "----d----",
                "---ede---",
                "--aaaaa--",
                'a',
                "slabStone",
                'b',
                "stickBlaze",
                'c',
                getModItem("DraconicEvolution", "teleporterMKI", 1, 0, missing),
                'd',
                getModItem("DraconicEvolution", "infusedObsidian", 1, 0, missing),
                'e',
                "stone");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "dislocatorReceptacle", 1, 0, missing),
                "---------",
                "---------",
                "--abcba--",
                "--bdbdb--",
                "--cbebc--",
                "--bdbdb--",
                "--abcba--",
                "---------",
                "---------",
                'a',
                "plateSilver",
                'b',
                "plateDraconium",
                'c',
                getModItem("DraconicEvolution", "draconicCore", 1, 0, missing),
                'd',
                getModItem("DraconicEvolution", "infusedObsidian", 1, 0, missing),
                'e',
                getModItem("DraconicEvolution", "teleporterStand", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "energyStorageCore", 1, 0, missing),
                "---------",
                "---------",
                "--aabaa--",
                "--aacaa--",
                "--bcdcb--",
                "--aacaa--",
                "--aabaa--",
                "---------",
                "---------",
                'a',
                "plateDraconium",
                'b',
                getModItem("DraconicEvolution", "draconiumFluxCapacitor", 1, 0, missing),
                'c',
                getModItem("DraconicEvolution", "wyvernCore", 1, 0, missing),
                'd',
                getModItem("DraconicEvolution", "draconium", 1, 2, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "energyPylon", 1, 0, missing),
                "---------",
                "---------",
                "--abcba--",
                "--bcdcb--",
                "--cdedc--",
                "--bcdcb--",
                "--abcba--",
                "---------",
                "---------",
                'a',
                "gemEnderEye",
                'b',
                "plateEmerald",
                'c',
                "plateDiamond",
                'd',
                getModItem("DraconicEvolution", "draconicCore", 1, 0, missing),
                'e',
                "blockDraconium");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "energyCrystal", 1, 0, missing),
                "---------",
                "----a----",
                "----b----",
                "---bbb---",
                "---aca---",
                "---bbb---",
                "----b----",
                "----a----",
                "---------",
                'a',
                "gemExquisiteDiamond",
                'b',
                "plateDraconium",
                'c',
                getModItem("DraconicEvolution", "draconicCore", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "energyCrystal", 1, 1, missing),
                "---------",
                "----a----",
                "----b----",
                "---cdc---",
                "---beb---",
                "---cdc---",
                "----b----",
                "----a----",
                "---------",
                'a',
                "plateDraconiumAwakened",
                'b',
                getModItem("DraconicEvolution", "draconicCore", 1, 0, missing),
                'c',
                "gemExquisiteRuby",
                'd',
                getModItem("DraconicEvolution", "wyvernCore", 1, 0, missing),
                'e',
                getModItem("DraconicEvolution", "energyCrystal", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "wrench", 1, 0, missing),
                "-----a---",
                "----aa---",
                "----ab---",
                "----abbaa",
                "---ccaaa-",
                "--ccc----",
                "-ccc-----",
                "ccc------",
                "dc-------",
                'a',
                "plateDraconium",
                'b',
                "plateDiamond",
                'c',
                "stickBlaze",
                'd',
                getModItem("DraconicEvolution", "draconicCore", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "generator", 1, 3, missing),
                "---------",
                "---------",
                "--abbba--",
                "--bcdcb--",
                "--befeb--",
                "--abbba--",
                "---------",
                "---------",
                "---------",
                'a',
                "plateSteel",
                'b',
                "ingotBrickNether",
                'c',
                getModItem("gregtech", "gt.metaitem.01", 1, 32500, missing),
                'd',
                getModItem("DraconicEvolution", "draconicCore", 1, 0, missing),
                'e',
                getModItem("BuildCraft|Transport", "item.buildcraftPipe.pipepowercobblestone", 1, 0, missing),
                'f',
                "craftingIronFurnace");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "playerDetectorAdvanced", 1, 0, missing),
                "---------",
                "---------",
                "---------",
                "--abcba--",
                "--adeda--",
                "--abcba--",
                "---------",
                "---------",
                "---------",
                'a',
                "plateDraconium",
                'b',
                "gemEnderEye",
                'c',
                getModItem("minecraft", "compass", 1, 0, missing),
                'd',
                getModItem("minecraft", "skull", 1, 1, missing),
                'e',
                getModItem("DraconicEvolution", "playerDetector", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "weatherController", 1, 0, missing),
                "---------",
                "---------",
                "--abcda--",
                "--aefea--",
                "--aghga--",
                "--aaaaa--",
                "---------",
                "---------",
                "---------",
                'a',
                "plateDraconium",
                'b',
                getModItem("DraconicEvolution", "rainSensor", 1, 0, missing),
                'c',
                getModItem("OpenBlocks", "bigbutton", 1, 0, missing),
                'd',
                getModItem("minecraft", "daylight_detector", 1, 0, missing),
                'e',
                getModItem("DraconicEvolution", "draconicCore", 1, 0, missing),
                'f',
                getModItem("Forestry", "factory", 1, 7, missing),
                'g',
                "stickBlaze",
                'h',
                "gemExquisiteEmerald");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "sunDial", 1, 0, missing),
                "---------",
                "---------",
                "--aabaa--",
                "--ccdcc--",
                "--cefec--",
                "--cghgc--",
                "--ccccc--",
                "---------",
                "---------",
                'a',
                "plateDraconium",
                'b',
                getModItem("minecraft", "dragon_egg", 1, 0, missing),
                'c',
                "plateDraconiumAwakened",
                'd',
                getModItem("DraconicEvolution", "dragonHeart", 1, 0, missing),
                'e',
                getModItem("DraconicEvolution", "wyvernCore", 1, 0, missing),
                'f',
                getModItem("DraconicEvolution", "chaosShard", 1, 0, missing),
                'g',
                getModItem("DraconicEvolution", "awakenedCore", 1, 0, missing),
                'h',
                getModItem("DraconicEvolution", "weatherController", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "grinder", 1, 3, missing),
                "---------",
                "---------",
                "--aaaaa--",
                "--abcba--",
                "--adeda--",
                "--aaaaa--",
                "---------",
                "---------",
                "---------",
                'a',
                "plateDraconium",
                'b',
                getModItem("Thaumcraft", "ItemSwordElemental", 1, 0, missing),
                'c',
                getModItem("EnderIO", "blockKillerJoe", 1, 0, missing),
                'd',
                getModItem("gregtech", "gt.metaitem.01", 1, 32604, missing),
                'e',
                getModItem("EnderIO", "blockCapBank", 1, 3, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "flowGate", 1, 6, missing),
                "---------",
                "---------",
                "--aaaaa--",
                "--aabaa--",
                "--cdedc--",
                "--aabaa--",
                "--aaaaa--",
                "---------",
                "---------",
                'a',
                "plateDraconium",
                'b',
                getModItem("DraconicEvolution", "draconicCore", 1, 0, missing),
                'c',
                "pipeHugeNeutronium",
                'd',
                getModItem("ProjRed|Integration", "projectred.integration.gate", 1, 26, missing),
                'e',
                getModItem("DraconicEvolution", "wyvernCore", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "flowGate", 1, 0, missing),
                "---------",
                "---------",
                "--aaaaa--",
                "--aabaa--",
                "--cdedc--",
                "--aabaa--",
                "--aaaaa--",
                "---------",
                "---------",
                'a',
                "plateDraconium",
                'b',
                getModItem("DraconicEvolution", "draconiumEnergyCore", 1, 0, missing),
                'c',
                getModItem("EnderIO", "itemPowerConduit", 1, 2, missing),
                'd',
                getModItem("ProjRed|Integration", "projectred.integration.gate", 1, 26, missing),
                'e',
                getModItem("DraconicEvolution", "wyvernCore", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "reactorEnergyInjector", 1, 0, missing),
                "---------",
                "---------",
                "--a-b-a--",
                "--acbca--",
                "--dcecd--",
                "--fffff--",
                "--fffff--",
                "---------",
                "---------",
                'a',
                getModItem("DraconicEvolution", "reactorCraftingPart", 1, 2, missing),
                'b',
                "plateDraconiumAwakened",
                'c',
                getModItem("DraconicEvolution", "reactorCraftingPart", 1, 1, missing),
                'd',
                getModItem("DraconicEvolution", "draconiumEnergyCore", 1, 0, missing),
                'e',
                getModItem("DraconicEvolution", "wyvernCore", 1, 0, missing),
                'f',
                "plateDraconium");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("DraconicEvolution", "upgradeModifier", 1, 0, missing),
                "---------",
                "---------",
                "--aaaaa--",
                "--abcba--",
                "--acdca--",
                "--abcba--",
                "--aaaaa--",
                "---------",
                "---------",
                'a',
                "plateDraconium",
                'b',
                "gearDraconium",
                'c',
                getModItem("DraconicEvolution", "draconicCore", 1, 0, missing),
                'd',
                getModItem("gregtech", "gt.metaitem.01", 1, 32604, missing));

        GT_Values.RA.stdBuilder()
                .itemInputs(
                        getModItem("gregtech", "gt.metaitem.01", 4, 17299, missing),
                        getModItem("DraconicEvolution", "draconiumDust", 1, 0, missing))
                .itemOutputs(getModItem("DraconicEvolution", "infoTablet", 1, 0, missing)).noFluidInputs()
                .noFluidOutputs().duration(400).eut(480).addTo(sAssemblerRecipes);
        GT_Values.RA.stdBuilder()
                .itemInputs(
                        getModItem("DraconicEvolution", "energyCrystal", 1, 0, missing),
                        getModItem("DraconicEvolution", "particleGenerator", 2, 0, missing))
                .itemOutputs(getModItem("DraconicEvolution", "energyCrystal", 1, 4, missing))
                .fluidInputs(FluidRegistry.getFluidStack("molten.enderium", 864)).noFluidOutputs().duration(1200)
                .eut(1024).addTo(sAssemblerRecipes);
        GT_Values.RA.stdBuilder()
                .itemInputs(
                        getModItem("DraconicEvolution", "energyCrystal", 1, 1, missing),
                        getModItem("DraconicEvolution", "particleGenerator", 2, 0, missing))
                .itemOutputs(getModItem("DraconicEvolution", "energyCrystal", 1, 5, missing))
                .fluidInputs(FluidRegistry.getFluidStack("molten.enderium", 864)).noFluidOutputs().duration(2400)
                .eut(4096).addTo(sAssemblerRecipes);
        GT_Values.RA.stdBuilder()
                .itemInputs(
                        getModItem("minecraft", "arrow", 1, 0, missing),
                        getModItem("minecraft", "ender_pearl", 1, 0, missing))
                .itemOutputs(getModItem("DraconicEvolution", "enderArrow", 1, 0, missing)).noFluidInputs()
                .noFluidOutputs().duration(200).eut(480).addTo(sAssemblerRecipes);
        GT_Values.RA.stdBuilder()
                .itemInputs(
                        getModItem("Railcraft", "detector", 1, 5, missing),
                        getModItem("DraconicEvolution", "draconicCore", 1, 0, missing))
                .itemOutputs(getModItem("DraconicEvolution", "playerDetector", 1, 0, missing)).noFluidInputs()
                .noFluidOutputs().duration(200).eut(480).addTo(sAssemblerRecipes);
        GT_Values.RA.stdBuilder()
                .itemInputs(
                        getModItem("ProjRed|Integration", "projectred.integration.gate", 1, 16, missing),
                        getModItem("gregtech", "gt.metaitem.01", 1, 17975, missing))
                .itemOutputs(getModItem("DraconicEvolution", "rainSensor", 1, 0, missing)).noFluidInputs()
                .noFluidOutputs().duration(200).eut(480).addTo(sAssemblerRecipes);
        GT_Values.RA.stdBuilder()
                .itemInputs(
                        getModItem("minecraft", "obsidian", 1, 0, missing),
                        getModItem("minecraft", "blaze_powder", 1, 0, missing))
                .itemOutputs(getModItem("DraconicEvolution", "infusedObsidian", 1, 0, missing))
                .fluidInputs(FluidRegistry.getFluidStack("molten.draconium", 144)).noFluidOutputs().duration(1200)
                .eut(1920).specialValue(7500).addTo(sBlastRecipes);
        GT_Values.RA.stdBuilder().itemInputs(getModItem("DraconicEvolution", "chaosShard", 1, 0, missing))
                .itemOutputs(getModItem("DraconicEvolution", "chaosFragment", 9, 2, missing)).noFluidInputs()
                .noFluidOutputs().duration(100).eut(480).addTo(sHammerRecipes);
        GT_Values.RA.stdBuilder().itemInputs(getModItem("DraconicEvolution", "chaosFragment", 1, 2, missing))
                .itemOutputs(getModItem("DraconicEvolution", "chaosFragment", 9, 1, missing)).noFluidInputs()
                .noFluidOutputs().duration(50).eut(480).addTo(sHammerRecipes);
        GT_Values.RA.stdBuilder().itemInputs(getModItem("DraconicEvolution", "chaosFragment", 1, 1, missing))
                .itemOutputs(getModItem("DraconicEvolution", "chaosFragment", 9, 0, missing)).noFluidInputs()
                .noFluidOutputs().duration(25).eut(480).addTo(sHammerRecipes);
        GT_Values.RA.stdBuilder()
                .itemInputs(
                        getModItem("DraconicEvolution", "safetyMatch", 16, 1000, missing),
                        getModItem("gregtech", "gt.metaitem.01", 1, 18879, missing))
                .itemOutputs(getModItem("DraconicEvolution", "safetyMatch", 1, 0, missing)).noFluidInputs()
                .noFluidOutputs().duration(64).eut(16).addTo(sBoxinatorRecipes);

    }
}
