package com.dreammaster.scripts;

import static gregtech.api.util.GT_ModHandler.getModItem;

import java.util.Arrays;
import java.util.List;

import fox.spiteful.avaritia.crafting.ExtremeCraftingManager;
import gregtech.api.enums.Mods;

public class ScriptSGCraft implements IScriptLoader {

    @Override
    public String getScriptName() {
        return "Stargate Craft";
    }

    @Override
    public List<String> getDependencies() {
        return Arrays.asList(Mods.SGCraft.ID);
    }

    @Override
    public void loadRecipes() {
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("SGCraft", "stargateRing", 1, 0, missing),
                "aaabcbbdd",
                "aaabbbdee",
                "aaabbde--",
                "fffbbde--",
                "fffbcde--",
                "fffbbde--",
                "aaabbde--",
                "aaabbbdee",
                "aaabcbbdd",
                'a',
                getModItem("gregtech", "gt.blockmetal9", 1, 7, missing),
                'b',
                getModItem("dreamcraft", "item.StargateFramePart", 1, 0, missing),
                'c',
                getModItem("dreamcraft", "item.StargateChevron", 1, 0, missing),
                'd',
                getModItem("dreamcraft", "item.StargateShieldingFoil", 1, 0, missing),
                'e',
                getModItem("gregtech", "gt.metaitem.01", 1, 32047, missing),
                'f',
                getModItem("gregtech", "gt.blockmetal9", 1, 4, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("SGCraft", "sgChevronUpgrade", 1, 0, missing),
                "---------",
                "---aba---",
                "---cac---",
                "---dbd---",
                "---cec---",
                "---dcd---",
                "---cac---",
                "---aba---",
                "---------",
                'a',
                getModItem("gregtech", "gt.metaitem.01", 1, 32023, missing),
                'b',
                getModItem("dreamcraft", "item.StargateChevron", 1, 0, missing),
                'c',
                getModItem("dreamcraft", "item.StargateFramePart", 1, 0, missing),
                'd',
                getModItem("gregtech", "gt.metaitem.01", 1, 32047, missing),
                'e',
                getModItem("gregtech", "gt.metaitem.01", 1, 32043, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("SGCraft", "stargateRing", 1, 1, missing),
                "---------",
                "----a----",
                "---aba---",
                "--acdca--",
                "-abdedba-",
                "--acdca--",
                "---aba---",
                "----a----",
                "---------",
                'a',
                getModItem("gregtech", "gt.blockmetal9", 1, 7, missing),
                'b',
                getModItem("gregtech", "gt.metaitem.01", 1, 32047, missing),
                'c',
                getModItem("dreamcraft", "item.QuantumCircuit", 1, 0, missing),
                'd',
                getModItem("SGCraft", "sgChevronUpgrade", 1, 0, missing),
                'e',
                getModItem("SGCraft", "stargateRing", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("SGCraft", "stargateBase", 1, 0, missing),
                "abbcdcbba",
                "befghgfeb",
                "beigjgieb",
                "cklmnmlkc",
                "dklnonlkd",
                "cklmnmlkc",
                "beigjgieb",
                "befghgfeb",
                "abbcdcbba",
                'a',
                getModItem("gregtech", "gt.metaitem.01", 1, 32043, missing),
                'b',
                getModItem("gregtech", "gt.metaitem.01", 1, 32047, missing),
                'c',
                getModItem("gregtech", "gt.metaitem.01", 1, 32039, missing),
                'd',
                getModItem("gregtech", "gt.metaitem.03", 1, 4139, missing),
                'e',
                getModItem("tectech", "gt.spacetime_compression_field_generator", 1, 8, missing),
                'f',
                getModItem("bartworks", "bw.werkstoffblocks.01", 1, 10112, missing),
                'g',
                getModItem("dreamcraft", "item.StargateShieldingFoil", 1, 0, missing),
                'h',
                getModItem("dreamcraft", "item.StargateFramePart", 1, 0, missing),
                'i',
                getModItem("gregtech", "gt.metaitem.01", 1, 32594, missing),
                'j',
                getModItem("gregtech", "gt.metaitem.01", 1, 22583, missing),
                'k',
                getModItem("tectech", "gt.stabilisation_field_generator", 1, 8, missing),
                'l',
                getModItem("gregtech", "gt.blockmachines", 1, 15410, missing),
                'm',
                getModItem("SGCraft", "stargateRing", 1, 0, missing),
                'n',
                getModItem("SGCraft", "stargateRing", 1, 1, missing),
                'o',
                getModItem("SGCraft", "sgCoreCrystal", 1, 0, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("SGCraft", "ic2Capacitor", 1, 0, missing),
                "---------",
                "---------",
                "---aaa---",
                "--abcba--",
                "--acbca--",
                "--abcba--",
                "---aaa---",
                "---------",
                "---------",
                'a',
                getModItem("dreamcraft", "item.StargateShieldingFoil", 1, 0, missing),
                'b',
                getModItem("gregtech", "gt.metaitem.01", 1, 32047, missing),
                'c',
                createItemStack(
                        "EnderIO",
                        "blockCapBank",
                        1,
                        0,
                        "{type:\"CREATIVE\",storedEnergyRF:2500000}",
                        missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("SGCraft", "sgIrisBlade", 1, 0, missing),
                "-----aaaa",
                "----aaaa-",
                "---aaaa--",
                "--aaaa---",
                "-aaaaa---",
                "abaaaa---",
                "abaaaaa--",
                "acbbaaaa-",
                "daaaaaaaa",
                'a',
                getModItem("gregtech", "gt.metaitem.01", 1, 22585, missing),
                'b',
                getModItem("gregtech", "gt.metaitem.01", 1, 32023, missing),
                'c',
                getModItem("gregtech", "gt.metaitem.01", 1, 32594, missing),
                'd',
                getModItem("GoodGenerator", "compactFusionCoil", 1, 3, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("SGCraft", "sgIrisUpgrade", 1, 0, missing),
                "--aaaaa--",
                "-b-----b-",
                "a-------a",
                "a-------a",
                "a-------a",
                "a-------a",
                "a-------a",
                "-b-----b-",
                "--aaaaa--",
                'a',
                getModItem("SGCraft", "sgIrisBlade", 1, 0, missing),
                'b',
                getModItem("GoodGenerator", "compactFusionCoil", 1, 3, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("SGCraft", "rfPowerUnit", 1, 0, missing),
                "aabcccbaa",
                "a-b---b-a",
                "a-b-d-b-a",
                "c--beb--c",
                "c-defed-c",
                "c--beb--c",
                "agg-d-gga",
                "a-g---g-a",
                "aaacccaaa",
                'a',
                getModItem("gregtech", "gt.blockmetal9", 1, 7, missing),
                'b',
                getModItem("GoodGenerator", "compactFusionCoil", 1, 3, missing),
                'c',
                getModItem("gregtech", "gt.blockmetal9", 1, 4, missing),
                'd',
                getModItem("dreamcraft", "item.QuantumCircuit", 1, 0, missing),
                'e',
                getModItem("SGCraft", "ic2Capacitor", 1, 0, missing),
                'f',
                getModItem("SGCraft", "stargateRing", 1, 0, missing),
                'g',
                getModItem("gregtech", "gt.metaitem.03", 1, 4586, missing));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem("SGCraft", "ocInterface", 1, 0, missing),
                "abccdccea",
                "ed--d--db",
                "c-d-d-d-c",
                "c--ddd--c",
                "ddddadddd",
                "c--ddd--c",
                "c-d-d-d-c",
                "bd--d--de",
                "aeccdccba",
                'a',
                getModItem("dreamcraft", "item.QuantumCircuit", 1, 0, missing),
                'b',
                getModItem("gregtech", "gt.metaitem.01", 1, 32039, missing),
                'c',
                getModItem("gregtech", "gt.blockmetal9", 1, 7, missing),
                'd',
                getModItem("GoodGenerator", "compactFusionCoil", 1, 3, missing),
                'e',
                getModItem("gregtech", "gt.metaitem.01", 1, 32043, missing));

    }
}
