package com.dreammaster.scripts;

import static gregtech.api.enums.Mods.AdvancedSolarPanel;
import static gregtech.api.enums.Mods.GregTech;
import static gregtech.api.enums.Mods.IndustrialCraft2;
import static gregtech.api.enums.Mods.Minecraft;
import static gregtech.api.util.GT_ModHandler.getModItem;
import static gregtech.api.util.GT_Recipe.GT_Recipe_Map.sAssemblerRecipes;

import java.util.Arrays;
import java.util.List;

import gregtech.api.enums.GT_Values;
import gregtech.api.enums.ItemList;

public class ScriptAdvancedSolarPanel implements IScriptLoader {

    @Override
    public String getScriptName() {
        return "Advanced Solar Panel";
    }

    @Override
    public List<String> getDependencies() {
        return Arrays.asList(AdvancedSolarPanel.ID, IndustrialCraft2.ID);
    }

    @Override
    public void loadRecipes() {

        // AUTOGENERATED

        addShapedRecipe(
                getModItem(AdvancedSolarPanel.ID, "advanced_solar_helmet", 1, 0, missing),
                "craftingToolWrench",
                getModItem(AdvancedSolarPanel.ID, "BlockAdvSolarPanel", 1, 0, missing),
                "craftingToolScrewdriver",
                "circuitAdvanced",
                getModItem(IndustrialCraft2.ID, "itemArmorNanoHelmet", 1, wildcard, missing),
                "circuitAdvanced",
                "cableGt04Aluminium",
                ItemList.Transformer_HV_MV.get(1L),
                "cableGt04Aluminium");
        addShapedRecipe(
                getModItem(AdvancedSolarPanel.ID, "hybrid_solar_helmet", 1, 0, missing),
                "craftingToolWrench",
                getModItem(AdvancedSolarPanel.ID, "BlockAdvSolarPanel", 1, 1, missing),
                "craftingToolScrewdriver",
                "circuitMaster",
                getModItem(IndustrialCraft2.ID, "itemArmorQuantumHelmet", 1, wildcard, missing),
                "circuitMaster",
                "cableGt04Platinum",
                ItemList.Transformer_EV_HV.get(1L),
                "cableGt04Platinum");
        addShapedRecipe(
                getModItem(AdvancedSolarPanel.ID, "ultimate_solar_helmet", 1, 0, missing),
                "craftingToolWrench",
                "circuitUltimate",
                "craftingToolScrewdriver",
                "craftingSolarPanelHV",
                getModItem(AdvancedSolarPanel.ID, "hybrid_solar_helmet", 1, wildcard, missing),
                "craftingSolarPanelHV",
                "cableGt04VanadiumGallium",
                ItemList.Transformer_IV_EV.get(1L),
                "cableGt04VanadiumGallium");
        addShapedRecipe(
                getModItem(AdvancedSolarPanel.ID, "asp_crafting_items", 4, 5, missing),
                "glassReinforced",
                getModItem(AdvancedSolarPanel.ID, "asp_crafting_items", 1, 2, missing),
                "glassReinforced",
                getModItem(AdvancedSolarPanel.ID, "asp_crafting_items", 1, 2, missing),
                "plateGlowstone",
                getModItem(AdvancedSolarPanel.ID, "asp_crafting_items", 1, 2, missing),
                "glassReinforced",
                getModItem(AdvancedSolarPanel.ID, "asp_crafting_items", 1, 2, missing),
                "glassReinforced");
        addShapedRecipe(
                getModItem(AdvancedSolarPanel.ID, "asp_crafting_items", 1, 13, missing),
                getModItem(AdvancedSolarPanel.ID, "asp_crafting_items", 1, 4, missing),
                "plateNetherStar",
                getModItem(AdvancedSolarPanel.ID, "asp_crafting_items", 1, 4, missing),
                "plateNetherStar",
                "circuitOptical",
                "plateNetherStar",
                getModItem(AdvancedSolarPanel.ID, "asp_crafting_items", 1, 4, missing),
                "plateNetherStar",
                getModItem(AdvancedSolarPanel.ID, "asp_crafting_items", 1, 4, missing));
        addShapedRecipe(
                ItemList.Cover_SolarPanel_LV.get(1L),
                "craftingToolCrowbar",
                getModItem(AdvancedSolarPanel.ID, "BlockAdvSolarPanel", 1, 0, missing),
                "craftingToolScrewdriver",
                "craftingToolWrench",
                "craftingToolHardHammer",
                "craftingToolFile");
        addShapedRecipe(
                ItemList.Cover_SolarPanel_MV.get(1L),
                "craftingToolCrowbar",
                getModItem(AdvancedSolarPanel.ID, "BlockAdvSolarPanel", 1, 1, missing),
                "craftingToolScrewdriver",
                "craftingToolWrench",
                "craftingToolHardHammer",
                "craftingToolFile");
        addShapedRecipe(
                ItemList.Cover_SolarPanel_HV.get(1L),
                "craftingToolCrowbar",
                getModItem(AdvancedSolarPanel.ID, "BlockAdvSolarPanel", 1, 2, missing),
                "craftingToolScrewdriver",
                "craftingToolWrench",
                "craftingToolHardHammer",
                "craftingToolFile");
        addShapedRecipe(
                ItemList.Cover_SolarPanel_EV.get(1L),
                "craftingToolCrowbar",
                getModItem(AdvancedSolarPanel.ID, "BlockAdvSolarPanel", 1, 3, missing),
                "craftingToolScrewdriver",
                "craftingToolWrench",
                "craftingToolHardHammer",
                "craftingToolFile");

        GT_Values.RA.stdBuilder()
                .itemInputs(
                        getModItem(GregTech.ID, "gt.metaitem.01", 1, 11098, missing),
                        getModItem(Minecraft.ID, "glowstone", 4, 0, missing))
                .itemOutputs(getModItem(AdvancedSolarPanel.ID, "asp_crafting_items", 1, 2, missing)).noFluidInputs()
                .noFluidOutputs().duration(600).eut(1920).addTo(sAssemblerRecipes);
        GT_Values.RA.stdBuilder()
                .itemInputs(
                        getModItem(AdvancedSolarPanel.ID, "asp_crafting_items", 1, 0, missing),
                        getModItem(AdvancedSolarPanel.ID, "asp_crafting_items", 8, 2, missing))
                .itemOutputs(getModItem(AdvancedSolarPanel.ID, "asp_crafting_items", 1, 3, missing)).noFluidInputs()
                .noFluidOutputs().duration(1200).eut(7680).addTo(sAssemblerRecipes);
        GT_Values.RA.stdBuilder()
                .itemInputs(
                        getModItem(GregTech.ID, "gt.metaitem.01", 4, 17318, missing),
                        getModItem(IndustrialCraft2.ID, "itemPartIridium", 8, 0, missing))
                .itemOutputs(getModItem(AdvancedSolarPanel.ID, "asp_crafting_items", 1, 1, missing)).noFluidInputs()
                .noFluidOutputs().duration(800).eut(30720).addTo(sAssemblerRecipes);
        GT_Values.RA.stdBuilder()
                .itemInputs(
                        getModItem(AdvancedSolarPanel.ID, "asp_crafting_items", 1, 1, missing),
                        getModItem(AdvancedSolarPanel.ID, "asp_crafting_items", 8, 3, missing))
                .itemOutputs(getModItem(AdvancedSolarPanel.ID, "asp_crafting_items", 1, 4, missing)).noFluidInputs()
                .noFluidOutputs().duration(1600).eut(122880).addTo(sAssemblerRecipes);

    }
}
