package com.dreammaster.scripts;

import static gregtech.api.enums.Mods.CompactKineticGenerators;
import static gregtech.api.enums.Mods.IndustrialCraft2;
import static com.dreammaster.scripts.IngredientFactory.getModItem;

import java.util.Arrays;
import java.util.List;

import com.dreammaster.item.NHItemList;

import fox.spiteful.avaritia.crafting.ExtremeCraftingManager;
import gregtech.api.enums.ItemList;
import gtPlusPlus.xmod.gregtech.api.enums.GregtechItemList;

public class ScriptCompactKineticGenerators implements IScriptLoader {

    @Override
    public String getScriptName() {
        return "Compact Kinetic Generators";
    }

    @Override
    public List<String> getDependencies() {
        return Arrays.asList(CompactKineticGenerators.ID, IndustrialCraft2.ID);
    }

    @Override
    public void loadRecipes() {
        addShapedRecipe(
                getModItem(CompactKineticGenerators.ID, "IridiumBlade", 1, 0),
                "plateAlloyIridium",
                "plateAlloyIridium",
                "plateAlloyIridium",
                "plateAlloyIridium",
                "ringOsmium",
                "plateAlloyIridium",
                "plateAlloyIridium",
                "plateAlloyIridium",
                "plateAlloyIridium");
        addShapedRecipe(
                getModItem(CompactKineticGenerators.ID, "IridiumRotor", 1, 0),
                GregtechItemList.IridiumShaft.get(1),
                getModItem(CompactKineticGenerators.ID, "IridiumBlade", 1, 0),
                "craftingToolHardHammer",
                getModItem(CompactKineticGenerators.ID, "IridiumBlade", 1, 0),
                "ringChrome",
                getModItem(CompactKineticGenerators.ID, "IridiumBlade", 1, 0),
                "craftingToolWrench",
                getModItem(CompactKineticGenerators.ID, "IridiumBlade", 1, 0),
                GregtechItemList.IridiumShaft.get(1));

        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 0),
                "---------",
                "---------",
                "--aabaa--",
                "--cdedc--",
                "--bfgfb--",
                "--chehc--",
                "--aabaa--",
                "---------",
                "---------",
                'a',
                "plateTripleTungstenSteel",
                'b',
                getModItem(IndustrialCraft2.ID, "blockKineticGenerator", 1, 0),
                'c',
                "itemCasingTungstenSteel",
                'd',
                "gearGtSmallDesh",
                'e',
                "cableGt02Tungsten",
                'f',
                "circuitElite",
                'g',
                ItemList.Hull_EV.get(1L),
                'h',
                ItemList.Electric_Motor_EV.get(1L));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 1),
                "---------",
                "---------",
                "--aabaa--",
                "--cdedc--",
                "--bfgfb--",
                "--chehc--",
                "--aabaa--",
                "---------",
                "---------",
                'a',
                "plateTripleIridium",
                'b',
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 0),
                'c',
                "itemCasingIridium",
                'd',
                "gearGtSmallOriharukon",
                'e',
                "wireGt04HSSG",
                'f',
                "circuitMaster",
                'g',
                ItemList.Hull_IV.get(1L),
                'h',
                ItemList.Electric_Motor_IV.get(1L));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 2),
                "---------",
                "---------",
                "--aabaa--",
                "--cdedc--",
                "--bfgfb--",
                "--chehc--",
                "--aabaa--",
                "---------",
                "---------",
                'a',
                "plateTripleNaquadah",
                'b',
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 1),
                'c',
                NHItemList.IridiumAlloyItemCasing.get(),
                'd',
                "gearGtSmallDraconium",
                'e',
                "cableGt04VanadiumGallium",
                'f',
                "circuitUltimate",
                'g',
                ItemList.Hull_LuV.get(1L),
                'h',
                ItemList.Electric_Motor_LuV.get(1L));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 3),
                "---------",
                "---------",
                "--aabaa--",
                "--cdedc--",
                "--bfgfb--",
                "--chehc--",
                "--aabaa--",
                "---------",
                "---------",
                'a',
                "plateTripleNeutronium",
                'b',
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 2),
                'c',
                "itemCasingNeutronium",
                'd',
                "gearGtSmallElectrumFlux",
                'e',
                "cableGt08Duranium",
                'f',
                "circuitSuperconductor",
                'g',
                ItemList.Hull_ZPM.get(1L),
                'h',
                ItemList.Electric_Motor_ZPM.get(1L));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 4),
                "---------",
                "---------",
                "--aabaa--",
                "--cdedc--",
                "--bfgfb--",
                "--chehc--",
                "--aabaa--",
                "---------",
                "---------",
                'a',
                "plateTripleTungstenSteel",
                'b',
                getModItem(IndustrialCraft2.ID, "blockKineticGenerator", 1, 4),
                'c',
                "itemCasingTungstenSteel",
                'd',
                ItemList.Electric_Pump_EV.get(1L),
                'e',
                "cableGt02Tungsten",
                'f',
                "circuitElite",
                'g',
                ItemList.Hull_EV.get(1L),
                'h',
                "gearGtSmallDesh");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 5),
                "---------",
                "---------",
                "--aabaa--",
                "--cdedc--",
                "--bfgfb--",
                "--chehc--",
                "--aabaa--",
                "---------",
                "---------",
                'a',
                "plateTripleIridium",
                'b',
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 4),
                'c',
                "itemCasingIridium",
                'd',
                ItemList.Electric_Pump_IV.get(1L),
                'e',
                "wireGt04HSSG",
                'f',
                "circuitMaster",
                'g',
                ItemList.Hull_IV.get(1L),
                'h',
                "gearGtSmallOriharukon");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 6),
                "---------",
                "---------",
                "--aabaa--",
                "--cdedc--",
                "--bfgfb--",
                "--chehc--",
                "--aabaa--",
                "---------",
                "---------",
                'a',
                "plateTripleNaquadah",
                'b',
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 5),
                'c',
                NHItemList.IridiumAlloyItemCasing.get(),
                'd',
                ItemList.Electric_Pump_LuV.get(1L),
                'e',
                "cableGt04VanadiumGallium",
                'f',
                "circuitUltimate",
                'g',
                ItemList.Hull_LuV.get(1L),
                'h',
                "gearGtSmallDraconium");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 7),
                "---------",
                "---------",
                "--aabaa--",
                "--cdedc--",
                "--bfgfb--",
                "--chehc--",
                "--aabaa--",
                "---------",
                "---------",
                'a',
                "plateTripleNeutronium",
                'b',
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 6),
                'c',
                "itemCasingNeutronium",
                'd',
                ItemList.Electric_Pump_ZPM.get(1L),
                'e',
                "cableGt08Duranium",
                'f',
                "circuitSuperconductor",
                'g',
                ItemList.Hull_ZPM.get(1L),
                'h',
                "gearGtSmallElectrumFlux");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 8),
                "---------",
                "---------",
                "--aabaa--",
                "--cdedc--",
                "--fghgf--",
                "--cijic--",
                "--aabaa--",
                "---------",
                "---------",
                'a',
                "plateTripleTungstenSteel",
                'b',
                GregtechItemList.TungstenSteelShaft.get(1),
                'c',
                "rotorTungstenSteel",
                'd',
                "gearDesh",
                'e',
                ItemList.Hull_EV.get(1L),
                'f',
                "cableGt02Tungsten",
                'g',
                "circuitElite",
                'h',
                getModItem(IndustrialCraft2.ID, "blockGenerator", 1, 9),
                'i',
                ItemList.Electric_Motor_EV.get(1L),
                'j',
                ItemList.BatteryHull_EV_Full.get(1));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 9),
                "---------",
                "---------",
                "--aabaa--",
                "--cdedc--",
                "--fghgf--",
                "--cijic--",
                "--aabaa--",
                "---------",
                "---------",
                'a',
                "plateTripleIridium",
                'b',
                GregtechItemList.TungstenSteelShaft.get(1),
                'c',
                "rotorIridium",
                'd',
                "gearOriharukon",
                'e',
                ItemList.Hull_IV.get(1L),
                'f',
                "wireGt04HSSG",
                'g',
                "circuitMaster",
                'h',
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 8),
                'i',
                ItemList.Electric_Motor_IV.get(1L),
                'j',
                ItemList.BatteryHull_IV_Full.get(1));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 10),
                "---------",
                "---------",
                "--aabaa--",
                "--cdedc--",
                "--fghgf--",
                "--cijic--",
                "--aabaa--",
                "---------",
                "---------",
                'a',
                "plateTripleNaquadah",
                'b',
                GregtechItemList.IridiumShaft.get(1),
                'c',
                "rotorOsmium",
                'd',
                "gearDraconium",
                'e',
                ItemList.Hull_LuV.get(1L),
                'f',
                "cableGt04VanadiumGallium",
                'g',
                "circuitUltimate",
                'h',
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 9),
                'i',
                ItemList.Electric_Motor_LuV.get(1L),
                'j',
                ItemList.BatteryHull_LuV_Full.get(1));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 11),
                "---------",
                "---------",
                "--aabaa--",
                "--cdedc--",
                "--fghgf--",
                "--cijic--",
                "--aabaa--",
                "---------",
                "---------",
                'a',
                "plateTripleNeutronium",
                'b',
                GregtechItemList.IridiumShaft.get(1),
                'c',
                "rotorNeutronium",
                'd',
                "gearElectrumFlux",
                'e',
                ItemList.Hull_ZPM.get(1L),
                'f',
                "cableGt08Duranium",
                'g',
                "circuitSuperconductor",
                'h',
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 10),
                'i',
                ItemList.Electric_Motor_ZPM.get(1L),
                'j',
                ItemList.BatteryHull_ZPM_Full.get(1));

    }
}
