package com.dreammaster.scripts;

import static gregtech.api.enums.Mods.CompactKineticGenerators;
import static gregtech.api.enums.Mods.GTPlusPlus;
import static gregtech.api.enums.Mods.IndustrialCraft2;
import static gregtech.api.util.GTModHandler.getModItem;

import java.util.Arrays;
import java.util.List;

import net.minecraft.item.ItemStack;

import com.dreammaster.gthandler.CustomItemList;

import fox.spiteful.avaritia.crafting.ExtremeCraftingManager;
import gregtech.api.enums.ItemList;
import gtPlusPlus.xmod.ic2.item.IC2Items;

public class ScriptCompactKineticGenerators implements IScriptLoader {

    @Override
    public String getScriptName() {
        return "Compact Kinetic Generators";
    }

    @Override
    public List<String> getDependencies() {
        return Arrays.asList(CompactKineticGenerators.ID, GTPlusPlus.ID, IndustrialCraft2.ID);
    }

    @Override
    public void loadRecipes() {
        addShapedRecipe(
                getModItem(CompactKineticGenerators.ID, "IridiumBlade", 1, 0, missing),
                "plateAlloyIridium",
                "plateAlloyIridium",
                "plateAlloyIridium",
                "plateAlloyIridium",
                "ringOsmium",
                "plateAlloyIridium",
                "plateAlloyIridium",
                "plateAlloyIridium",
                "plateAlloyIridium");
        addShapedRecipe(
                getModItem(CompactKineticGenerators.ID, "IridiumRotor", 1, 0, missing),
                new ItemStack(IC2Items.shaft_Material_4.getItem(), 1, 0),
                getModItem(CompactKineticGenerators.ID, "IridiumBlade", 1, 0, missing),
                "craftingToolHardHammer",
                getModItem(CompactKineticGenerators.ID, "IridiumBlade", 1, 0, missing),
                "ringChrome",
                getModItem(CompactKineticGenerators.ID, "IridiumBlade", 1, 0, missing),
                "craftingToolWrench",
                getModItem(CompactKineticGenerators.ID, "IridiumBlade", 1, 0, missing),
                new ItemStack(IC2Items.shaft_Material_4.getItem(), 1, 0));

        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 0, missing),
                "---------",
                "---------",
                "--aabaa--",
                "--cdedc--",
                "--bfgfb--",
                "--chehc--",
                "--aabaa--",
                "---------",
                "---------",
                'a',
                "plateTripleTungstenSteel",
                'b',
                getModItem(IndustrialCraft2.ID, "blockKineticGenerator", 1, 0, missing),
                'c',
                "itemCasingTungstenSteel",
                'd',
                "gearGtSmallDesh",
                'e',
                "cableGt02Tungsten",
                'f',
                "circuitElite",
                'g',
                ItemList.Hull_EV.get(1L),
                'h',
                ItemList.Electric_Motor_EV.get(1L));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 1, missing),
                "---------",
                "---------",
                "--aabaa--",
                "--cdedc--",
                "--bfgfb--",
                "--chehc--",
                "--aabaa--",
                "---------",
                "---------",
                'a',
                "plateTripleIridium",
                'b',
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 0, missing),
                'c',
                "itemCasingIridium",
                'd',
                "gearGtSmallOriharukon",
                'e',
                "wireGt04HSSG",
                'f',
                "circuitMaster",
                'g',
                ItemList.Hull_IV.get(1L),
                'h',
                ItemList.Electric_Motor_IV.get(1L));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 2, missing),
                "---------",
                "---------",
                "--aabaa--",
                "--cdedc--",
                "--bfgfb--",
                "--chehc--",
                "--aabaa--",
                "---------",
                "---------",
                'a',
                "plateTripleNaquadah",
                'b',
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 1, missing),
                'c',
                CustomItemList.IridiumAlloyItemCasing.get(1L),
                'd',
                "gearGtSmallDraconium",
                'e',
                "cableGt04VanadiumGallium",
                'f',
                "circuitUltimate",
                'g',
                ItemList.Hull_LuV.get(1L),
                'h',
                ItemList.Electric_Motor_LuV.get(1L));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 3, missing),
                "---------",
                "---------",
                "--aabaa--",
                "--cdedc--",
                "--bfgfb--",
                "--chehc--",
                "--aabaa--",
                "---------",
                "---------",
                'a',
                "plateTripleNeutronium",
                'b',
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 2, missing),
                'c',
                "itemCasingNeutronium",
                'd',
                "gearGtSmallElectrumFlux",
                'e',
                "cableGt08Duranium",
                'f',
                "circuitSuperconductor",
                'g',
                ItemList.Hull_ZPM.get(1L),
                'h',
                ItemList.Electric_Motor_ZPM.get(1L));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 4, missing),
                "---------",
                "---------",
                "--aabaa--",
                "--cdedc--",
                "--bfgfb--",
                "--chehc--",
                "--aabaa--",
                "---------",
                "---------",
                'a',
                "plateTripleTungstenSteel",
                'b',
                getModItem(IndustrialCraft2.ID, "blockKineticGenerator", 1, 4, missing),
                'c',
                "itemCasingTungstenSteel",
                'd',
                ItemList.Electric_Pump_EV.get(1L),
                'e',
                "cableGt02Tungsten",
                'f',
                "circuitElite",
                'g',
                ItemList.Hull_EV.get(1L),
                'h',
                "gearGtSmallDesh");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 5, missing),
                "---------",
                "---------",
                "--aabaa--",
                "--cdedc--",
                "--bfgfb--",
                "--chehc--",
                "--aabaa--",
                "---------",
                "---------",
                'a',
                "plateTripleIridium",
                'b',
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 4, missing),
                'c',
                "itemCasingIridium",
                'd',
                ItemList.Electric_Pump_IV.get(1L),
                'e',
                "wireGt04HSSG",
                'f',
                "circuitMaster",
                'g',
                ItemList.Hull_IV.get(1L),
                'h',
                "gearGtSmallOriharukon");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 6, missing),
                "---------",
                "---------",
                "--aabaa--",
                "--cdedc--",
                "--bfgfb--",
                "--chehc--",
                "--aabaa--",
                "---------",
                "---------",
                'a',
                "plateTripleNaquadah",
                'b',
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 5, missing),
                'c',
                CustomItemList.IridiumAlloyItemCasing.get(1L),
                'd',
                ItemList.Electric_Pump_LuV.get(1L),
                'e',
                "cableGt04VanadiumGallium",
                'f',
                "circuitUltimate",
                'g',
                ItemList.Hull_LuV.get(1L),
                'h',
                "gearGtSmallDraconium");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 7, missing),
                "---------",
                "---------",
                "--aabaa--",
                "--cdedc--",
                "--bfgfb--",
                "--chehc--",
                "--aabaa--",
                "---------",
                "---------",
                'a',
                "plateTripleNeutronium",
                'b',
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 6, missing),
                'c',
                "itemCasingNeutronium",
                'd',
                ItemList.Electric_Pump_ZPM.get(1L),
                'e',
                "cableGt08Duranium",
                'f',
                "circuitSuperconductor",
                'g',
                ItemList.Hull_ZPM.get(1L),
                'h',
                "gearGtSmallElectrumFlux");
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 8, missing),
                "---------",
                "---------",
                "--aabaa--",
                "--cdedc--",
                "--fghgf--",
                "--cijic--",
                "--aabaa--",
                "---------",
                "---------",
                'a',
                "plateTripleTungstenSteel",
                'b',
                new ItemStack(IC2Items.shaft_Material_2.getItem(), 1, 0),
                'c',
                "rotorTungstenSteel",
                'd',
                "gearDesh",
                'e',
                ItemList.Hull_EV.get(1L),
                'f',
                "cableGt02Tungsten",
                'g',
                "circuitElite",
                'h',
                getModItem(IndustrialCraft2.ID, "blockGenerator", 1, 9, missing),
                'i',
                ItemList.Electric_Motor_EV.get(1L),
                'j',
                ItemList.BatteryHull_EV_Full.get(1));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 9, missing),
                "---------",
                "---------",
                "--aabaa--",
                "--cdedc--",
                "--fghgf--",
                "--cijic--",
                "--aabaa--",
                "---------",
                "---------",
                'a',
                "plateTripleIridium",
                'b',
                new ItemStack(IC2Items.shaft_Material_2.getItem(), 1, 0),
                'c',
                "rotorIridium",
                'd',
                "gearOriharukon",
                'e',
                ItemList.Hull_IV.get(1L),
                'f',
                "wireGt04HSSG",
                'g',
                "circuitMaster",
                'h',
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 8, missing),
                'i',
                ItemList.Electric_Motor_IV.get(1L),
                'j',
                ItemList.BatteryHull_IV_Full.get(1));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 10, missing),
                "---------",
                "---------",
                "--aabaa--",
                "--cdedc--",
                "--fghgf--",
                "--cijic--",
                "--aabaa--",
                "---------",
                "---------",
                'a',
                "plateTripleNaquadah",
                'b',
                new ItemStack(IC2Items.shaft_Material_4.getItem(), 1, 0),
                'c',
                "rotorOsmium",
                'd',
                "gearDraconium",
                'e',
                ItemList.Hull_LuV.get(1L),
                'f',
                "cableGt04VanadiumGallium",
                'g',
                "circuitUltimate",
                'h',
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 9, missing),
                'i',
                ItemList.Electric_Motor_LuV.get(1L),
                'j',
                ItemList.BatteryHull_LuV_Full.get(1));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 11, missing),
                "---------",
                "---------",
                "--aabaa--",
                "--cdedc--",
                "--fghgf--",
                "--cijic--",
                "--aabaa--",
                "---------",
                "---------",
                'a',
                "plateTripleNeutronium",
                'b',
                new ItemStack(IC2Items.shaft_Material_4.getItem(), 1, 0),
                'c',
                "rotorNeutronium",
                'd',
                "gearElectrumFlux",
                'e',
                ItemList.Hull_ZPM.get(1L),
                'f',
                "cableGt08Duranium",
                'g',
                "circuitSuperconductor",
                'h',
                getModItem(CompactKineticGenerators.ID, "BlockCkg", 1, 10, missing),
                'i',
                ItemList.Electric_Motor_ZPM.get(1L),
                'j',
                ItemList.BatteryHull_ZPM_Full.get(1));

    }
}
