package com.dreammaster.gthandler;

import static gregtech.api.enums.GT_Values.W;

import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;

import gregtech.api.interfaces.IItemContainer;
import gregtech.api.util.GT_ModHandler;
import gregtech.api.util.GT_OreDictUnificator;
import gregtech.api.util.GT_Utility;

public enum CustomItemList implements IItemContainer {

    Casing_Pyrolyse,
    Machine_Multi_AirFilterT1,
    Machine_Multi_AirFilterT2,
    Machine_Multi_AirFilterT3,
    Casing_AirFilter_Vent_T1,
    Casing_AirFilter_Turbine_T1,
    Casing_AirFilter_Vent_T2,
    Casing_AirFilter_Turbine_T2,
    Casing_AirFilter_Vent_T3,
    Casing_AirFilter_Turbine_T3,
    @Deprecated
    Hatch_Dynamo_UEV,
    @Deprecated
    Hatch_Dynamo_UIV,
    @Deprecated
    Hatch_Dynamo_UMV,
    @Deprecated
    Hatch_Dynamo_UXV,
    @Deprecated
    Hatch_Energy_UEV,
    @Deprecated
    Hatch_Energy_UIV,
    @Deprecated
    Hatch_Energy_UMV,
    @Deprecated
    Hatch_Energy_UXV,
    @Deprecated
    Hatch_Input_UEV,
    @Deprecated
    Hatch_Input_UIV,
    @Deprecated
    Hatch_Input_UMV,
    @Deprecated
    Hatch_Input_UXV,
    @Deprecated
    Hatch_Input_MAX,
    @Deprecated
    Hatch_Output_UEV,
    @Deprecated
    Hatch_Output_UIV,
    @Deprecated
    Hatch_Output_UMV,
    @Deprecated
    Hatch_Output_UXV,
    @Deprecated
    Hatch_Output_MAX,
    @Deprecated
    Battery_TurboCharger_4by4_ULV,
    @Deprecated
    Battery_TurboCharger_4by4_LV,
    @Deprecated
    Battery_TurboCharger_4by4_MV,
    @Deprecated
    Battery_TurboCharger_4by4_HV,
    @Deprecated
    Battery_TurboCharger_4by4_EV,
    @Deprecated
    Battery_TurboCharger_4by4_IV,
    @Deprecated
    Battery_TurboCharger_4by4_LuV,
    @Deprecated
    Battery_TurboCharger_4by4_ZPM,
    @Deprecated
    Battery_TurboCharger_4by4_UV,
    @Deprecated
    Battery_TurboCharger_4by4_UHV,
    @Deprecated
    Battery_Charger_4by4_UEV,
    @Deprecated
    Battery_Charger_4by4_UIV,
    @Deprecated
    Battery_Charger_4by4_UMV,
    @Deprecated
    Battery_Charger_4by4_UXV,
    @Deprecated
    Battery_Buffer_1by1_UEV,
    @Deprecated
    Battery_Buffer_1by1_UIV,
    @Deprecated
    Battery_Buffer_1by1_UMV,
    @Deprecated
    Battery_Buffer_1by1_UXV,
    @Deprecated
    Battery_Buffer_1by1_MAXV,
    @Deprecated
    Battery_Buffer_2by2_UEV,
    @Deprecated
    Battery_Buffer_2by2_UIV,
    @Deprecated
    Battery_Buffer_2by2_UMV,
    @Deprecated
    Battery_Buffer_2by2_UXV,
    @Deprecated
    Battery_Buffer_2by2_MAXV,
    @Deprecated
    Battery_Buffer_3by3_UEV,
    @Deprecated
    Battery_Buffer_3by3_UIV,
    @Deprecated
    Battery_Buffer_3by3_UMV,
    @Deprecated
    Battery_Buffer_3by3_UXV,
    @Deprecated
    Battery_Buffer_3by3_MAXV,
    @Deprecated
    Battery_Buffer_4by4_UEV,
    @Deprecated
    Battery_Buffer_4by4_UIV,
    @Deprecated
    Battery_Buffer_4by4_UMV,
    @Deprecated
    Battery_Buffer_4by4_UXV,
    @Deprecated
    Battery_Buffer_4by4_MAXV,
    @Deprecated
    Hull_UEV,
    @Deprecated
    Hull_UIV,
    @Deprecated
    Hull_UMV,
    @Deprecated
    Hull_UXV,
    @Deprecated
    Hull_MAXV, // since Hull_MAX is in gt
    @Deprecated
    Casing_UEV,
    @Deprecated
    Casing_UIV,
    @Deprecated
    Casing_UMV,
    @Deprecated
    Casing_UXV,
    @Deprecated
    Casing_MAXV, // since Hull_MAX is in gt
    @Deprecated
    Transformer_UEV_UHV,
    @Deprecated
    Transformer_UIV_UEV,
    @Deprecated
    Transformer_UMV_UIV,
    @Deprecated
    Transformer_UXV_UMV,
    @Deprecated
    Transformer_MAX_UXV,
    @Deprecated
    WetTransformer_LV_ULV,
    @Deprecated
    WetTransformer_MV_LV,
    @Deprecated
    WetTransformer_HV_MV,
    @Deprecated
    WetTransformer_EV_HV,
    @Deprecated
    WetTransformer_IV_EV,
    @Deprecated
    WetTransformer_LuV_IV,
    @Deprecated
    WetTransformer_ZPM_LuV,
    @Deprecated
    WetTransformer_UV_ZPM,
    @Deprecated
    WetTransformer_UHV_UV,
    @Deprecated
    WetTransformer_UEV_UHV,
    @Deprecated
    WetTransformer_UIV_UEV,
    @Deprecated
    WetTransformer_UMV_UIV,
    @Deprecated
    WetTransformer_UXV_UMV,
    @Deprecated
    WetTransformer_MAX_UXV,
    @Deprecated
    Transformer_HA_UEV_UHV,
    @Deprecated
    Transformer_HA_UIV_UEV,
    @Deprecated
    Transformer_HA_UMV_UIV,
    @Deprecated
    Transformer_HA_UXV_UMV,
    @Deprecated
    Transformer_HA_MAX_UXV,
    @Deprecated
    BatteryHull_EV,
    @Deprecated
    BatteryHull_IV,
    @Deprecated
    BatteryHull_LuV,
    @Deprecated
    BatteryHull_ZPM,
    @Deprecated
    BatteryHull_UV,
    @Deprecated
    BatteryHull_UHV,
    @Deprecated
    BatteryHull_UEV,
    @Deprecated
    BatteryHull_UIV,
    @Deprecated
    BatteryHull_UMV,
    @Deprecated
    BatteryHull_UxV,
    @Deprecated
    BatteryHull_EV_Full,
    @Deprecated
    BatteryHull_IV_Full,
    @Deprecated
    BatteryHull_LuV_Full,
    @Deprecated
    BatteryHull_ZPM_Full,
    @Deprecated
    BatteryHull_UV_Full,
    @Deprecated
    BatteryHull_UHV_Full,
    @Deprecated
    BatteryHull_UEV_Full,
    @Deprecated
    BatteryHull_UIV_Full,
    @Deprecated
    BatteryHull_UMV_Full,
    @Deprecated
    BatteryHull_UxV_Full,
    @Deprecated

    Generator_Plasma_ZPMV,
    @Deprecated
    Generator_Plasma_UV,
    @Deprecated
    Generator_Plasma_UHV,
    @Deprecated
    Generator_Plasma_UEV,
    @Deprecated
    Generator_Plasma_UIV,
    @Deprecated
    Generator_Plasma_UMV,
    @Deprecated
    AlloySmelterLuV,
    @Deprecated
    AlloySmelterZPM,
    @Deprecated
    AlloySmelterUV,
    @Deprecated
    AlloySmelterUHV,
    @Deprecated
    AlloySmelterUEV,
    @Deprecated
    AlloySmelterUIV,
    @Deprecated
    AlloySmelterUMV,
    @Deprecated
    AmplifabricatorLuV,
    @Deprecated
    AmplifabricatorZPM,
    @Deprecated
    AmplifabricatorUV,
    @Deprecated
    AmplifabricatorUHV,
    @Deprecated
    AmplifabricatorUEV,
    @Deprecated
    AmplifabricatorUIV,
    @Deprecated
    AmplifabricatorUMV,
    @Deprecated
    ArcFurnaceLuV,
    @Deprecated
    ArcFurnaceZPM,
    @Deprecated
    ArcFurnaceUV,
    @Deprecated
    ArcFurnaceUHV,
    @Deprecated
    ArcFurnaceUEV,
    @Deprecated
    ArcFurnaceUIV,
    @Deprecated
    ArcFurnaceUMV,
    @Deprecated
    AssemblingMachineLuV,
    @Deprecated
    AssemblingMachineZPM,
    @Deprecated
    AssemblingMachineUV,
    @Deprecated
    AssemblingMachineUHV,
    @Deprecated
    AssemblingMachineUEV,
    @Deprecated
    AssemblingMachineUIV,
    @Deprecated
    AssemblingMachineUMV,
    @Deprecated
    AutoclaveLuV,
    @Deprecated
    AutoclaveZPM,
    @Deprecated
    AutoclaveUV,
    @Deprecated
    AutoclaveUHV,
    @Deprecated
    AutoclaveUEV,
    @Deprecated
    AutoclaveUIV,
    @Deprecated
    AutoclaveUMV,
    @Deprecated
    BendingMachineLuV,
    @Deprecated
    BendingMachineZPM,
    @Deprecated
    BendingMachineUV,
    @Deprecated
    BendingMachineUHV,
    @Deprecated
    BendingMachineUEV,
    @Deprecated
    BendingMachineUIV,
    @Deprecated
    BendingMachineUMV,
    @Deprecated
    BreweryLuV,
    @Deprecated
    BreweryZPM,
    @Deprecated
    BreweryUV,
    @Deprecated
    BreweryUHV,
    @Deprecated
    BreweryUEV,
    @Deprecated
    BreweryUIV,
    @Deprecated
    BreweryUMV,
    @Deprecated
    CanningMachineLuV,
    @Deprecated
    CanningMachineZPM,
    @Deprecated
    CanningMachineUV,
    @Deprecated
    CanningMachineUHV,
    @Deprecated
    CanningMachineUEV,
    @Deprecated
    CanningMachineUIV,
    @Deprecated
    CanningMachineUMV,
    @Deprecated
    CentrifugeLuV,
    @Deprecated
    CentrifugeZPM,
    @Deprecated
    CentrifugeUV,
    @Deprecated
    CentrifugeUHV,
    @Deprecated
    CentrifugeUEV,
    @Deprecated
    CentrifugeUIV,
    @Deprecated
    CentrifugeUMV,
    @Deprecated
    ChemicalBathLuV,
    @Deprecated
    ChemicalBathZPM,
    @Deprecated
    ChemicalBathUV,
    @Deprecated
    ChemicalBathUHV,
    @Deprecated
    ChemicalBathUEV,
    ChemicalBathUIV,
    @Deprecated
    ChemicalBathUMV,
    @Deprecated
    ChemicalReactorLuV,
    @Deprecated
    ChemicalReactorZPM,
    @Deprecated
    ChemicalReactorUV,
    @Deprecated
    ChemicalReactorUHV,
    @Deprecated
    ChemicalReactorUEV,
    @Deprecated
    ChemicalReactorUIV,
    @Deprecated
    ChemicalReactorUMV,
    @Deprecated
    CircuitAssemblerUHV,
    @Deprecated
    CircuitAssemblerUEV,
    @Deprecated
    CircuitAssemblerUIV,
    @Deprecated
    CircuitAssemblerUMV,
    @Deprecated
    CircuitAssemblerUXV,
    @Deprecated
    CircuitAssemblerMAX,
    @Deprecated
    CompressorLuV,
    @Deprecated
    CompressorZPM,
    @Deprecated
    CompressorUV,
    @Deprecated
    CompressorUHV,
    @Deprecated
    CompressorUEV,
    @Deprecated
    CompressorUIV,
    @Deprecated
    CompressorUMV,
    @Deprecated
    CuttingMachineLuV,
    @Deprecated
    CuttingMachineZPM,
    @Deprecated
    CuttingMachineUV,
    @Deprecated
    CuttingMachineUHV,
    @Deprecated
    CuttingMachineUEV,
    @Deprecated
    CuttingMachineUIV,
    @Deprecated
    CuttingMachineUMV,
    @Deprecated
    DistilleryLuV,
    @Deprecated
    DistilleryZPM,
    @Deprecated
    DistilleryUV,
    @Deprecated
    DistilleryUHV,
    @Deprecated
    DistilleryUEV,
    @Deprecated
    DistilleryUIV,
    @Deprecated
    DistilleryUMV,
    @Deprecated
    ElectricFurnaceLuV,
    @Deprecated
    ElectricFurnaceZPM,
    @Deprecated
    ElectricFurnaceUV,
    @Deprecated
    ElectricFurnaceUHV,
    @Deprecated
    ElectricFurnaceUEV,
    @Deprecated
    ElectricFurnaceUIV,
    @Deprecated
    ElectricFurnaceUMV,
    @Deprecated
    ElectricOvenLuV,
    @Deprecated
    ElectricOvenZPM,
    @Deprecated
    ElectricOvenUV,
    @Deprecated
    ElectricOvenUHV,
    @Deprecated
    ElectricOvenUEV,
    @Deprecated
    ElectricOvenUIV,
    @Deprecated
    ElectricOvenUMV,
    @Deprecated
    ElectrolyzerLuV,
    @Deprecated
    ElectrolyzerZPM,
    @Deprecated
    ElectrolyzerUV,
    @Deprecated
    ElectrolyzerUHV,
    @Deprecated
    ElectrolyzerUEV,
    @Deprecated
    ElectrolyzerUIV,
    @Deprecated
    ElectrolyzerUMV,
    @Deprecated
    ElectromagneticSeparatorLuV,
    @Deprecated
    ElectromagneticSeparatorZPM,
    @Deprecated
    ElectromagneticSeparatorUV,
    @Deprecated
    ElectromagneticSeparatorUHV,
    @Deprecated
    ElectromagneticSeparatorUEV,
    @Deprecated
    ElectromagneticSeparatorUIV,
    @Deprecated
    ElectromagneticSeparatorUMV,
    @Deprecated
    ExtractorLuV,
    @Deprecated
    ExtractorZPM,
    @Deprecated
    ExtractorUV,
    @Deprecated
    ExtractorUHV,
    @Deprecated
    ExtractorUEV,
    @Deprecated
    ExtractorUIV,
    @Deprecated
    ExtractorUMV,
    @Deprecated
    ExtruderLuV,
    @Deprecated
    ExtruderZPM,
    @Deprecated
    ExtruderUV,
    @Deprecated
    ExtruderUHV,
    @Deprecated
    ExtruderUEV,
    @Deprecated
    ExtruderUIV,
    @Deprecated
    ExtruderUMV,
    @Deprecated
    FermenterLuV,
    @Deprecated
    FermenterZPM,
    @Deprecated
    FermenterUV,
    @Deprecated
    FermenterUHV,
    @Deprecated
    FermenterUEV,
    @Deprecated
    FermenterUIV,
    @Deprecated
    FermenterUMV,
    @Deprecated
    FluidCannerLuV,
    @Deprecated
    FluidCannerZPM,
    @Deprecated
    FluidCannerUV,
    @Deprecated
    FluidCannerUHV,
    @Deprecated
    FluidCannerUEV,
    @Deprecated
    FluidCannerUIV,
    @Deprecated
    FluidCannerUMV,
    @Deprecated
    FluidExtractorLuV,
    @Deprecated
    FluidExtractorZPM,
    @Deprecated
    FluidExtractorUV,
    @Deprecated
    FluidExtractorUHV,
    @Deprecated
    FluidExtractorUEV,
    @Deprecated
    FluidExtractorUIV,
    @Deprecated
    FluidExtractorUMV,
    @Deprecated
    FluidHeaterLuV,
    @Deprecated
    FluidHeaterZPM,
    @Deprecated
    FluidHeaterUV,
    @Deprecated
    FluidHeaterUHV,
    @Deprecated
    FluidHeaterUEV,
    @Deprecated
    FluidHeaterUIV,
    @Deprecated
    FluidHeaterUMV,
    @Deprecated
    FluidSolidifierLuV,
    @Deprecated
    FluidSolidifierZPM,
    @Deprecated
    FluidSolidifierUV,
    @Deprecated
    FluidSolidifierUHV,
    @Deprecated
    FluidSolidifierUEV,
    @Deprecated
    FluidSolidifierUIV,
    @Deprecated
    FluidSolidifierUMV,
    @Deprecated
    FormingPressLuV,
    @Deprecated
    FormingPressZPM,
    @Deprecated
    FormingPressUV,
    @Deprecated
    FormingPressUHV,
    @Deprecated
    FormingPressUEV,
    @Deprecated
    FormingPressUIV,
    @Deprecated
    FormingPressUMV,
    @Deprecated
    ForgeHammerLuV,
    @Deprecated
    ForgeHammerZPM,
    @Deprecated
    ForgeHammerUV,
    @Deprecated
    ForgeHammerUHV,
    @Deprecated
    ForgeHammerUEV,
    @Deprecated
    ForgeHammerUIV,
    @Deprecated
    ForgeHammerUMV,
    @Deprecated
    LatheLuV,
    @Deprecated
    LatheZPM,
    @Deprecated
    LatheUV,
    @Deprecated
    LatheUHV,
    @Deprecated
    LatheUEV,
    @Deprecated
    LatheUIV,
    @Deprecated
    LatheUMV,
    @Deprecated
    PrecisionLaserEngraverLuV,
    @Deprecated
    PrecisionLaserEngraverZPM,
    @Deprecated
    PrecisionLaserEngraverUV,
    @Deprecated
    PrecisionLaserEngraverUHV,
    @Deprecated
    PrecisionLaserEngraverUEV,
    @Deprecated
    PrecisionLaserEngraverUIV,
    @Deprecated
    PrecisionLaserEngraverUMV,
    @Deprecated
    MaceratorLuV,
    @Deprecated
    MaceratorZPM,
    @Deprecated
    MaceratorUV,
    @Deprecated
    MaceratorUHV,
    @Deprecated
    MaceratorUEV,
    @Deprecated
    MaceratorUIV,
    @Deprecated
    MaceratorUMV,
    @Deprecated
    MassFabricatorLuV,
    @Deprecated
    MassFabricatorZPM,
    @Deprecated
    MassFabricatorUV,
    @Deprecated
    MassFabricatorUHV,
    @Deprecated
    MassFabricatorUEV,
    @Deprecated
    MassFabricatorUIV,
    @Deprecated
    MassFabricatorUMV,
    @Deprecated
    MicrowaveLuV,
    @Deprecated
    MicrowaveZPM,
    @Deprecated
    MicrowaveUV,
    @Deprecated
    MicrowaveUHV,
    @Deprecated
    MicrowaveUEV,
    @Deprecated
    MicrowaveUIV,
    @Deprecated
    MicrowaveUMV,
    @Deprecated
    MixerLuV,
    @Deprecated
    MixerZPM,
    @Deprecated
    MixerUV,
    @Deprecated
    MixerUHV,
    @Deprecated
    MixerUEV,
    @Deprecated
    MixerUIV,
    @Deprecated
    MixerUMV,
    @Deprecated
    OreWashingPlantLuV,
    @Deprecated
    OreWashingPlantZPM,
    @Deprecated
    OreWashingPlantUV,
    @Deprecated
    OreWashingPlantUHV,
    @Deprecated
    OreWashingPlantUEV,
    @Deprecated
    OreWashingPlantUIV,
    @Deprecated
    OreWashingPlantUMV,
    @Deprecated
    PlasmaArcFurnaceLuV,
    @Deprecated
    PlasmaArcFurnaceZPM,
    @Deprecated
    PlasmaArcFurnaceUV,
    @Deprecated
    PlasmaArcFurnaceUHV,
    @Deprecated
    PlasmaArcFurnaceUEV,
    @Deprecated
    PlasmaArcFurnaceUIV,
    @Deprecated
    PlasmaArcFurnaceUMV,
    @Deprecated
    PolarizerLuV,
    @Deprecated
    PolarizerZPM,
    @Deprecated
    PolarizerUV,
    @Deprecated
    PolarizerUHV,
    @Deprecated
    PolarizerUEV,
    @Deprecated
    PolarizerUIV,
    @Deprecated
    PolarizerUMV,
    @Deprecated
    RockBreakerLuV,
    @Deprecated
    RockBreakerZPM,
    @Deprecated
    RockBreakerUV,
    @Deprecated
    RockBreakerUHV,
    @Deprecated
    RockBreakerUEV,
    @Deprecated
    RockBreakerUIV,
    @Deprecated
    RockBreakerUMV,
    @Deprecated
    RecyclerLuV,
    @Deprecated
    RecyclerZPM,
    @Deprecated
    RecyclerUV,
    @Deprecated
    RecyclerUHV,
    @Deprecated
    RecyclerUEV,
    @Deprecated
    RecyclerUIV,
    @Deprecated
    RecyclerUMV,
    @Deprecated
    ReplicatorLuV,
    @Deprecated
    ReplicatorZPM,
    @Deprecated
    ReplicatorUV,
    @Deprecated
    ReplicatorUHV,
    @Deprecated
    ReplicatorUEV,
    @Deprecated
    ReplicatorUIV,
    @Deprecated
    ReplicatorUMV,
    @Deprecated
    ScannerLuV,
    @Deprecated
    ScannerZPM,
    @Deprecated
    ScannerUV,
    @Deprecated
    ScannerUHV,
    @Deprecated
    ScannerUEV,
    @Deprecated
    ScannerUIV,
    @Deprecated
    ScannerUMV,
    @Deprecated
    SiftingMachineLuV,
    @Deprecated
    SiftingMachineZPM,
    @Deprecated
    SiftingMachineUV,
    @Deprecated
    SiftingMachineUHV,
    @Deprecated
    SiftingMachineUEV,
    @Deprecated
    SiftingMachineUIV,
    @Deprecated
    SiftingMachineUMV,
    @Deprecated
    SlicingMachineLuV,
    @Deprecated
    SlicingMachineZPM,
    @Deprecated
    SlicingMachineUV,
    @Deprecated
    SlicingMachineUHV,
    @Deprecated
    SlicingMachineUEV,
    @Deprecated
    SlicingMachineUIV,
    @Deprecated
    SlicingMachineUMV,
    @Deprecated
    ThermalCentrifugeLuV,
    @Deprecated
    ThermalCentrifugeZPM,
    @Deprecated
    ThermalCentrifugeUV,
    @Deprecated
    ThermalCentrifugeUHV,
    @Deprecated
    ThermalCentrifugeUEV,
    @Deprecated
    ThermalCentrifugeUIV,
    @Deprecated
    ThermalCentrifugeUMV,
    @Deprecated
    WiremillLuV,
    @Deprecated
    WiremillZPM,
    @Deprecated
    WiremillUV,
    @Deprecated
    WiremillUHV,
    @Deprecated
    WiremillUEV,
    @Deprecated
    WiremillUIV,
    @Deprecated
    WiremillUMV,
    @Deprecated
    PumpLuV,
    @Deprecated
    PumpZPM,
    @Deprecated
    Automation_ChestBuffer_UHV,
    @Deprecated
    Automation_ChestBuffer_UEV,
    @Deprecated
    Automation_ChestBuffer_UIV,
    @Deprecated
    Automation_ChestBuffer_UMV,
    @Deprecated
    Automation_ChestBuffer_UXV,

    // CoreModItems
    EtchedLowVoltageWiring,
    EtchedInsaneVoltageWiring,
    EtchedLudicrousVoltageWiring,
    SteelBars,
    AluminiumBars,
    StainlessSteelBars,
    TungstenBars,
    TungstenSteelBars,
    IridiumBars,
    OsmiumBars,
    ChromeBars,
    TitaniumBars,
    NeutroniumBars,
    RedstoneAlloyBars,
    ElectricalSteelBars,
    ConductiveIronBars,
    EnergeticAlloyBars,
    VibrantAlloyBars,
    PulsatingIronBars,
    SoulariumBars,
    EnderiumBaseBars,
    EnderiumBars,
    PistonBlock,
    PistonPlate,
    ReinforcedGlassLense,
    ReinforcedGlassPLate,
    IridiumAlloyItemCasing,
    NagaScaleChip,
    NagaScaleFragment,
    LichBoneChip,
    LichBoneFragment,
    LichBone,
    FieryBloodDrop,
    CarminiteChip,
    CarminiteFragment,
    SnowQueenBloodDrop,
    SnowQueenBlood,
    NetherStarFragment,
    AdvancedBoard,
    AdvancedProcessorBoard,
    NanoBoard,
    NanoCrystal,
    NanoProcessorBoard,
    QuantumBoard,
    QuantumProcessorBoard,
    EngravedQuantumChip,
    HighEnergyCircuitParts,
    HighEnergyFlowCircuit,
    NanoCircuit,
    PikoCircuit,
    QuantumCircuit,
    EngravedDiamondCrystalChip,
    EngravedEnergyChip,
    CarbonPartBoots,
    CarbonPartChestplate,
    CarbonPartHelmet,
    CarbonPartHelmetNightVision,
    CarbonPartLeggings,
    NanoRubberBoots,
    NanoChestJetPack,
    NanoPlatedLeggings,
    NanoScubaHelmet,
    QuantumPartBoots,
    QuantumPartChestplate,
    QuantumPartHelmetEmpty,
    QuantumPartHelmet,
    QuantumPartLeggings,
    HeavyDutyAlloyIngotT4,
    HeavyDutyAlloyIngotT5,
    HeavyDutyAlloyIngotT6,
    HeavyDutyAlloyIngotT7,
    HeavyDutyAlloyIngotT8,
    HeavyDutyAlloyIngotT9,
    BlackPlutoniumCompressedPlate,
    DeshDualCompressedPlates,
    TitaniumDualCompressedPlates,
    IceCompressedPlate,
    IceDualCompressedPlates,
    QuantinumCompressedPlate,
    QuantinumDualCompressedPlates,
    MytrylDualCompressedPlates,
    MytrylCompressedPlate,
    MysteriousCrystalCompressedPlate,
    MysteriousCrystalDualCompressedPlates,
    SteelDualCompressedPlates,
    TinDualCompressedPlates,
    CopperDualCompressedPlates,
    IronDualCompressedPlates,
    MeteoricIronDualCompressedPlates,
    LedoxCompressedPlate,
    LedoxPlate,
    QuantinumPlate,
    CallistoIcePlate,
    MytrylPlate,
    MytrylCrystal,
    CallistoIceCompressedPlate,
    MarshmallowForm,
    MarshmallowFormMold,
    UncookedSlush,
    MalformedSlush,
    GlowingMarshmallow,
    Marshmallow,
    MoldHelmet,
    MoldChestplate,
    MoldLeggings,
    MoldBoots,
    IchoriumCap,
    CoinTechnician,
    CoinTechnicianI,
    CoinTechnicianII,
    CoinTechnicianIII,
    CoinTechnicianIV,
    CoinDarkWizard,
    CoinDarkWizardI,
    CoinDarkWizardII,
    CoinDarkWizardIII,
    CoinDarkWizardIV,
    CoinAdventure,
    CoinAdventureI,
    CoinAdventureII,
    CoinAdventureIII,
    CoinAdventureIV,
    CoinBees,
    CoinBeesI,
    CoinBeesII,
    CoinBeesIII,
    CoinBeesIV,
    CoinBlood,
    CoinBloodI,
    CoinBloodII,
    CoinBloodIII,
    CoinBloodIV,
    CoinFarmer,
    CoinFarmerI,
    CoinFarmerII,
    CoinFarmerIII,
    CoinFarmerIV,
    CoinForestry,
    CoinForestryI,
    CoinForestryII,
    CoinForestryIII,
    CoinForestryIV,
    CoinSurvivor,
    CoinSurvivorI,
    CoinSurvivorII,
    CoinSurvivorIII,
    CoinSurvivorIV,
    CoinSpace,
    CoinSpaceI,
    CoinSpaceII,
    CoinSpaceIII,
    CoinSpaceIV,
    CoinChunkloaderTierI,
    CoinChunkloaderTierII,
    CoinChunkloaderTierIII,
    CoinChunkloaderTierIV,
    CoinChunkloaderTierV,
    CoinChemist,
    CoinChemistI,
    CoinChemistII,
    CoinChemistIII,
    CoinChemistIV,
    CoinCook,
    CoinCookI,
    CoinCookII,
    CoinCookIII,
    CoinCookIV,
    CoinBlank,
    CoinBlankI,
    CoinBlankII,
    CoinBlankIII,
    CoinBlankIV,
    CoinSmith,
    CoinSmithI,
    CoinSmithII,
    CoinSmithIII,
    CoinSmithIV,
    CoinWitch,
    CoinWitchI,
    CoinWitchII,
    CoinWitchIII,
    CoinWitchIV,
    CoinFlower,
    CoinFlowerI,
    CoinFlowerII,
    CoinFlowerIII,
    CoinFlowerIV,
    CoinDonation,
    WetTofu,
    WeakOrb,
    ApprenticeOrb,
    MasterOrb,
    MagicianOrb,
    ArchmageOrb,
    TranscendentOrb,
    RawOrbTier1,
    RawOrbTier2,
    RawOrbTier3,
    RawOrbTier4,
    RawOrbTier5,
    RawOrbTier6,
    ArcaneSlate,
    TeleposerFrame,
    MysteriousCrystal,
    ManyullynCrystal,
    WoodenCasing,
    EssentiaCircuit,
    EngineeringProcessorEssentiaPulsatingCore,
    SchematicsAstroMiner,
    SchematicsCargoRocket,
    SchematicsMoonBuggy,
    SchematicsTier1,
    SchematicsTier2,
    SchematicsTier3,
    SchematicsTier4,
    SchematicsTier5,
    SchematicsTier6,
    SchematicsTier7,
    SchematicsTier8,
    RawSDHCAlloy,
    TungstenString,
    MeteoricIronString,
    MediumFuelCanister,
    LargeFuelCanister,
    ExtraLargeFuelCanister,
    HeavyDutyRocketEngineTier3,
    HeavyDutyRocketEngineTier4,
    HeavyDutyNoseConeTier3,
    HeavyDutyNoseConeTier4,
    HeavyDutyRocketFinsTier3,
    HeavyDutyRocketFinsTier4,
    Tier2Booster,
    Tier3Booster,
    Tier4Booster,
    HeavyDutyPlateTier4,
    HeavyDutyPlateTier5,
    HeavyDutyPlateTier6,
    HeavyDutyPlateTier7,
    HeavyDutyPlateTier8,
    LeadNickelPlate,
    LeadOriharukonPlate,
    MoonStoneDust,
    MarsStoneDust,
    AsteroidsStoneDust,
    PhobosStoneDust,
    DeimosStoneDust,
    CeresStoneDust,
    EuropaIceDust,
    EuropaStoneDust,
    GanymedeStoneDust,
    CallistoStoneDust,
    IoStoneDust,
    VenusStoneDust,
    MercuryStoneDust,
    EnceladusIceDust,
    EnceladusStoneDust,
    TitanStoneDust,
    OberonStoneDust,
    ProteusStoneDust,
    TritonStoneDust,
    PlutoIceDust,
    PlutoStoneDust,
    HaumeaStoneDust,
    MakeMakeStoneDust,
    MercuryCoreDust,
    CentauriAStoneDust,
    CentauriASurfaceDust,
    VegaBStoneDust,
    BarnardaEStoneDust,
    BarnardaFStoneDust,
    TCetiEStoneDust,
    MirandaStoneDust,
    WaferTier3,
    IndustryFrame,
    AdsorptionFilterCasing,
    AdsorptionFilter,
    AdsorptionFilterDirty,
    VoidSeed,
    MicaBasedPulp,
    MicaBasedSheet,
    MicaInsulatorSheet,
    MicaInsulatorFoil,
    AluminoSilicateWool,
    HotNetherrackBrick,
    InfernalBrick,
    AdvancedCokeOvenBrick,
    AdvancedCokeOvenBrickDust,
    CokeOvenBrick,
    CokeOvenBrickDust,
    MedalDerp,
    MedalGTExplosion,
    MedalBuilder,
    MedalEngineer,
    MedalWarp,
    MaceratedPlantmass,
    BedrockiumPlate,
    EngineCore,
    AlumiteDust,
    nameRemover,
    TwilightCrystal,
    UnfiredClayBrick,
    UnfiredSearedBrick,
    UnfiredCokeOvenBrick,
    UnfiredSlimeSoulBrick,
    RawLapotronCrystal,
    LapotronDust,
    SandDust,
    AluminiumIronPlate,
    ReinforcedAluminiumIronPlate,
    IrradiantReinforcedAluminiumPlate,
    IrradiantReinforcedTitaniumPlate,
    IrradiantReinforcedTungstenPlate,
    IrradiantReinforcedTungstenSteelPlate,
    IrradiantReinforcedChromePlate,
    IrradiantReinforcedNaquadriaPlate,
    IrradiantReinforcedNeutroniumPlate,
    IrradiantReinforcedBedrockiumPlate,
    QuantumCrystal,
    MysteriousCrystalLens,
    MysteriousCrystalGemFlawless,
    MysteriousCrystalGemExquisite,
    PrimordialPearlFragment,
    SandStoneRod,
    TheBigEgg,
    MutatedEgg,
    DraconiumEgg,
    EnderEgg,
    ChargedCertusQuartzDust,
    RawNeutronium,
    NeutronReflectorSmallParts,
    NeutronReflectorParts,
    TenKCell,
    ThirtyKCell,
    SixtyKCell,
    Empty180SpCell,
    Empty360SpCell,
    Empty540SpCell,
    Empty1080SpCell,
    RawPicoWafer,
    PicoWafer,
    StargateFramePart,
    StargateChevron,
    StargateShieldingFoil,
    StargateCrystalDust,
    TCetiESeaweedExtract,
    ArtificialLeather,
    EctoplasmaChip,
    EctoplasmaFragment,
    ArcaneShardChip,
    ArcaneShardFragment,
    RuneOfPowerFragment,
    RuneOfAgilityFragment,
    RuneOfVigorFragment,
    RuneOfDefenseFragment,
    RuneOfMagicFragment,
    RuneOfVoidFragment,
    NandChipBoard,
    LogicProcessorItemGoldCore,
    EngineeringProcessorItemDiamondCore,
    EngineeringProcessorItemEmeraldCore,
    EngineeringProcessorItemAdvEmeraldCore,
    Display,
    TitaniumIronPlate,
    ReinforcedTitaniumIronPlate,
    TungstenIronPlate,
    ReinforcedTungstenIronPlate,
    TungstenSteelIronPlate,
    ReinforcedTungstenSteelIronPlate,
    ChromeIronPlate,
    ReinforcedChromeIronPlate,
    NaquadriaIronPlate,
    ReinforcedNaquadriaIronPlate,
    NeutroniumIronPlate,
    ReinforcedNeutroniumIronPlate,
    BedrockiumIronPlate,
    ReinforcedBedrockiumIronPlate,
    BioBall,
    PotassiumHydroxideDust,
    ChromaticLens,
    RadoxPolymerLens,
    NanoCircuitOrigin,
    ChevronOrigin,
    FramePartOrigin,
    GatePlateOrigin,
    PikoCircuitPolychrome,
    QuantumCircuitPolychrome,
    GatePlatePolychrome,
    ChevronPolychrome,
    FramePartPolychrome,
    PikoCircuitDimensional,
    QuantumCircuitDimensional,
    GatePlateDimensional,
    ChevronDimensional,
    FramePartDimensional;

    private ItemStack mStack;
    private boolean mHasNotBeenSet = true;

    @Override
    public IItemContainer set(Item aItem) {
        mHasNotBeenSet = false;
        if (aItem == null) {
            return this;
        }
        ItemStack aStack = new ItemStack(aItem, 1, 0);
        mStack = GT_Utility.copyAmount(1, aStack);
        return this;
    }

    @Override
    public IItemContainer set(ItemStack aStack) {
        mHasNotBeenSet = false;
        mStack = GT_Utility.copyAmount(1, aStack);
        return this;
    }

    @Override
    public Item getItem() {
        if (mHasNotBeenSet) {
            throw new IllegalAccessError("The Enum '" + name() + "' has not been set to an Item at this time!");
        }
        if (GT_Utility.isStackInvalid(mStack)) {
            return null;
        }
        return mStack.getItem();
    }

    @Override
    public Block getBlock() {
        if (mHasNotBeenSet) {
            throw new IllegalAccessError("The Enum '" + name() + "' has not been set to an Item at this time!");
        }
        return GT_Utility.getBlockFromItem(getItem());
    }

    @Override
    public final boolean hasBeenSet() {
        return !mHasNotBeenSet;
    }

    @Override
    public boolean isStackEqual(Object aStack) {
        return isStackEqual(aStack, false, false);
    }

    @Override
    public boolean isStackEqual(Object aStack, boolean aWildcard, boolean aIgnoreNBT) {
        return !GT_Utility.isStackInvalid(aStack)
                && GT_Utility.areUnificationsEqual((ItemStack) aStack, aWildcard ? getWildcard(1) : get(1), aIgnoreNBT);
    }

    @Override
    public ItemStack get(long aAmount, Object... aReplacements) {
        if (mHasNotBeenSet) {
            throw new IllegalAccessError("The Enum '" + name() + "' has not been set to an Item at this time!");
        }
        if (GT_Utility.isStackInvalid(mStack)) {
            return GT_Utility.copyAmount(aAmount, aReplacements);
        }
        return GT_Utility.copyAmount(aAmount, GT_OreDictUnificator.get(mStack));
    }

    @Override
    public ItemStack getWildcard(long aAmount, Object... aReplacements) {
        if (mHasNotBeenSet) {
            throw new IllegalAccessError("The Enum '" + name() + "' has not been set to an Item at this time!");
        }
        if (GT_Utility.isStackInvalid(mStack)) {
            return GT_Utility.copyAmount(aAmount, aReplacements);
        }
        return GT_Utility.copyAmountAndMetaData(aAmount, W, GT_OreDictUnificator.get(mStack));
    }

    @Override
    public ItemStack getUndamaged(long aAmount, Object... aReplacements) {
        if (mHasNotBeenSet) {
            throw new IllegalAccessError("The Enum '" + name() + "' has not been set to an Item at this time!");
        }
        if (GT_Utility.isStackInvalid(mStack)) {
            return GT_Utility.copyAmount(aAmount, aReplacements);
        }
        return GT_Utility.copyAmountAndMetaData(aAmount, 0, GT_OreDictUnificator.get(mStack));
    }

    @Override
    public ItemStack getAlmostBroken(long aAmount, Object... aReplacements) {
        if (mHasNotBeenSet) {
            throw new IllegalAccessError("The Enum '" + name() + "' has not been set to an Item at this time!");
        }
        if (GT_Utility.isStackInvalid(mStack)) {
            return GT_Utility.copyAmount(aAmount, aReplacements);
        }
        return GT_Utility.copyAmountAndMetaData(aAmount, mStack.getMaxDamage() - 1, GT_OreDictUnificator.get(mStack));
    }

    @Override
    public ItemStack getWithName(long aAmount, String aDisplayName, Object... aReplacements) {
        ItemStack rStack = get(1, aReplacements);
        if (GT_Utility.isStackInvalid(rStack)) {
            return null;
        }
        rStack.setStackDisplayName(aDisplayName);
        return GT_Utility.copyAmount(aAmount, rStack);
    }

    @Override
    public ItemStack getWithCharge(long aAmount, int aEnergy, Object... aReplacements) {
        ItemStack rStack = get(1, aReplacements);
        if (GT_Utility.isStackInvalid(rStack)) {
            return null;
        }
        GT_ModHandler.chargeElectricItem(rStack, aEnergy, Integer.MAX_VALUE, true, false);
        return GT_Utility.copyAmount(aAmount, rStack);
    }

    @Override
    public ItemStack getWithDamage(long aAmount, long aMetaValue, Object... aReplacements) {
        if (mHasNotBeenSet) {
            throw new IllegalAccessError("The Enum '" + name() + "' has not been set to an Item at this time!");
        }
        if (GT_Utility.isStackInvalid(mStack)) {
            return GT_Utility.copyAmount(aAmount, aReplacements);
        }
        return GT_Utility.copyAmountAndMetaData(aAmount, aMetaValue, GT_OreDictUnificator.get(mStack));
    }

    @Override
    public IItemContainer registerOre(Object... aOreNames) {
        if (mHasNotBeenSet) {
            throw new IllegalAccessError("The Enum '" + name() + "' has not been set to an Item at this time!");
        }
        for (Object tOreName : aOreNames) {
            GT_OreDictUnificator.registerOre(tOreName, get(1));
        }
        return this;
    }

    @Override
    public IItemContainer registerWildcardAsOre(Object... aOreNames) {
        if (mHasNotBeenSet) {
            throw new IllegalAccessError("The Enum '" + name() + "' has not been set to an Item at this time!");
        }
        for (Object tOreName : aOreNames) {
            GT_OreDictUnificator.registerOre(tOreName, getWildcard(1));
        }
        return this;
    }
}
