package com.dreammaster.item;

import static com.dreammaster.creativetab.ModTabList.BARS_AND_CASINGS;
import static com.dreammaster.creativetab.ModTabList.CIRCUITS;
import static com.dreammaster.creativetab.ModTabList.GENERIC;
import static com.dreammaster.creativetab.ModTabList.MOLDS;
import static com.dreammaster.creativetab.ModTabList.SHAPES;
import static com.dreammaster.creativetab.ModTabList.SOLAR;
import static com.dreammaster.creativetab.ModTabList.SPACE;
import static com.dreammaster.creativetab.ModTabList.THAUMCRAFT;

import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;

import com.dreammaster.item.baubles.OvenGlove;
import com.dreammaster.item.baubles.WitherProtectionRing;
import com.dreammaster.item.food.QuantumBread;
import com.dreammaster.lib.Refstrings;

import cpw.mods.fml.common.registry.GameRegistry;

public enum NHItemList {

    // ===== Complex Items =====
    OvenGlove("OvenGlove", new OvenGlove(), GENERIC),
    WitherProtectionRing("WitherProtectionRing", new WitherProtectionRing(), THAUMCRAFT),
    WoodenBrickForm("WoodenBrickForm", new WoodenBrickForm(), GENERIC),
    QuantumBread("QuantumBread", new QuantumBread(), GENERIC),
    BowFletchingCast("BowFletchingCast", new CustomPattern(), MOLDS),
    BowStringCast("BowStringCast", new CustomPattern(), MOLDS),

    // ===== Simple Items =====
    MicaBasedPulp("MicaBasedPulp", GENERIC),
    MicaBasedSheet("MicaBasedSheet", GENERIC),
    MicaInsulatorSheet("MicaInsulatorSheet", GENERIC),
    MicaInsulatorFoil("MicaInsulatorFoil", GENERIC),
    TenKCell("TenKCell", GENERIC),
    ThirtyKCell("ThirtyKCell", GENERIC),
    SixtyKCell("SixtyKCell", GENERIC),
    Empty180SpCell("Empty180SpCell", GENERIC),
    Empty360SpCell("Empty360SpCell", GENERIC),
    Empty540SpCell("Empty540SpCell", GENERIC),
    Empty1080SpCell("Empty1080SpCell", GENERIC),
    AdsorptionFilterCasing("AdsorptionFilterCasing", GENERIC),
    AdsorptionFilter("AdsorptionFilter", GENERIC),
    AdsorptionFilterDirty("AdsorptionFilterDirty", GENERIC),
    AluminiumBars("AluminiumBars", BARS_AND_CASINGS),
    AluminiumIronPlate("AluminiumIronPlate", SOLAR),
    AdvancedCokeOvenBrick("AdvancedCokeOvenBrick", GENERIC),
    AdvancedCokeOvenBrickDust("AdvancedCokeOvenBrickDust", GENERIC),
    AdvancedBoard("AdvancedBoard", CIRCUITS),
    AdvancedProcessorBoard("AdvancedProcessorBoard", CIRCUITS),
    ApprenticeOrb("ApprenticeOrb", THAUMCRAFT),
    ArcaneSlate("ArcaneSlate", THAUMCRAFT),
    ArchmageOrb("ArchmageOrb", THAUMCRAFT),
    ArcaneShardChip("ArcaneShardChip", GENERIC),
    ArcaneShardFragment("ArcaneShardFragment", GENERIC),
    ArtificialLeather("ArtificialLeather", GENERIC),
    AsteroidsStoneDust("AsteroidsStoneDust", GENERIC),
    BarnardaEStoneDust("BarnardaEStoneDust", SPACE),
    BarnardaFStoneDust("BarnardaFStoneDust", SPACE),
    BioCarbonPlate("BioCarbonPlate", GENERIC),
    BedrockiumIronPlate("BedrockiumIronPlate", SOLAR),
    BioBall("BioBall", GENERIC),
    BioOrganicMesh("BioOrganicMesh", GENERIC),
    BioChunk("BioChunk", GENERIC),
    Blaster("Blaster", THAUMCRAFT),
    BloodVial("BloodVial", THAUMCRAFT),
    CompressedBioBall("CompressedBioBall", GENERIC),
    BlackPlutoniumCompressedPlate("BlackPlutoniumCompressedPlate", SPACE),
    BlankPlatedChip("BlankPlatedChip", CIRCUITS),
    CallistoIceCompressedPlate("CallistoIceCompressedPlate", SPACE),
    CallistoStoneDust("CallistoStoneDust", SPACE),
    CarbonPartBoots("CarbonPartBoots", GENERIC),
    CarbonPartChestplate("CarbonPartChestplate", GENERIC),
    CarbonPartHelmet("CarbonPartHelmet", GENERIC),
    CarbonPartHelmetNightVision("CarbonPartHelmetNightVision", GENERIC),
    CarbonPartLeggings("CarbonPartLeggings", GENERIC),
    CarminiteChip("CarminiteChip", THAUMCRAFT),
    CarminiteFragment("CarminiteFragment", THAUMCRAFT),
    CentauriASurfaceDust("CentauriASurfaceDust", SPACE),
    CentauriAStoneDust("CentauriAStoneDust", SPACE),
    CeresStoneDust("CeresStoneDust", SPACE),
    ChargedMechanistWandCap("ChargedMechanistWandCap", THAUMCRAFT),
    ChargedSilverWandCap("ChargedSilverWandCap", THAUMCRAFT),
    ChargedSojournerWandCap("ChargedSojournerWandCap", THAUMCRAFT),
    ChargedThaumiumWandCap("ChargedThaumiumWandCap", THAUMCRAFT),
    ChargedVoidWandCap("ChargedVoidWandCap", THAUMCRAFT),
    ChargedCertusQuartzDust("ChargedCertusQuartzDust", GENERIC),
    ChargedCertusQuartzPlate("ChargedCertusQuartzPlate", GENERIC),
    ChargedCertusQuartzRod("ChargedCertusQuartzRod", GENERIC),
    CoinChunkloaderTierI("CoinChunkloaderTierI", GENERIC),
    CoinChunkloaderTierII("CoinChunkloaderTierII", GENERIC),
    CoinChunkloaderTierIII("CoinChunkloaderTierIII", GENERIC),
    CoinChunkloaderTierIV("CoinChunkloaderTierIV", GENERIC),
    CoinChunkloaderTierV("CoinChunkloaderTierV", GENERIC),
    CoinAdventure("CoinAdventure", GENERIC),
    CoinAdventureI("CoinAdventureI", GENERIC),
    CoinAdventureII("CoinAdventureII", GENERIC),
    CoinAdventureIII("CoinAdventureIII", GENERIC),
    CoinAdventureIV("CoinAdventureIV", GENERIC),
    CoinBees("CoinBees", GENERIC),
    CoinBeesI("CoinBeesI", GENERIC),
    CoinBeesII("CoinBeesII", GENERIC),
    CoinBeesIII("CoinBeesIII", GENERIC),
    CoinBeesIV("CoinBeesIV", GENERIC),
    CoinBlank("CoinBlank", GENERIC),
    CoinBlankI("CoinBlankI", GENERIC),
    CoinBlankII("CoinBlankII", GENERIC),
    CoinBlankIII("CoinBlankIII", GENERIC),
    CoinBlankIV("CoinBlankIV", GENERIC),
    CoinBlood("CoinBlood", GENERIC),
    CoinBloodI("CoinBloodI", GENERIC),
    CoinBloodII("CoinBloodII", GENERIC),
    CoinBloodIII("CoinBloodIII", GENERIC),
    CoinBloodIV("CoinBloodIV", GENERIC),
    CoinChemist("CoinChemist", GENERIC),
    CoinChemistI("CoinChemistI", GENERIC),
    CoinChemistII("CoinChemistII", GENERIC),
    CoinChemistIII("CoinChemistIII", GENERIC),
    CoinChemistIV("CoinChemistIV", GENERIC),
    CoinCook("CoinCook", GENERIC),
    CoinCookI("CoinCookI", GENERIC),
    CoinCookII("CoinCookII", GENERIC),
    CoinCookIII("CoinCookIII", GENERIC),
    CoinCookIV("CoinCookIV", GENERIC),
    CoinDarkWizard("CoinDarkWizard", GENERIC),
    CoinDarkWizardI("CoinDarkWizardI", GENERIC),
    CoinDarkWizardII("CoinDarkWizardII", GENERIC),
    CoinDarkWizardIII("CoinDarkWizardIII", GENERIC),
    CoinDarkWizardIV("CoinDarkWizardIV", GENERIC),
    CoinFarmer("CoinFarmer", GENERIC),
    CoinFarmerI("CoinFarmerI", GENERIC),
    CoinFarmerII("CoinFarmerII", GENERIC),
    CoinFarmerIII("CoinFarmerIII", GENERIC),
    CoinFarmerIV("CoinFarmerIV", GENERIC),
    CoinFlower("CoinFlower", GENERIC),
    CoinFlowerI("CoinFlowerI", GENERIC),
    CoinFlowerII("CoinFlowerII", GENERIC),
    CoinFlowerIII("CoinFlowerIII", GENERIC),
    CoinFlowerIV("CoinFlowerIV", GENERIC),
    CoinForestry("CoinForestry", GENERIC),
    CoinForestryI("CoinForestryI", GENERIC),
    CoinForestryII("CoinForestryII", GENERIC),
    CoinForestryIII("CoinForestryIII", GENERIC),
    CoinForestryIV("CoinForestryIV", GENERIC),
    CoinSmith("CoinSmith", GENERIC),
    CoinSmithI("CoinSmithI", GENERIC),
    CoinSmithII("CoinSmithII", GENERIC),
    CoinSmithIII("CoinSmithIII", GENERIC),
    CoinSmithIV("CoinSmithIV", GENERIC),
    CoinWitch("CoinWitch", GENERIC),
    CoinWitchI("CoinWitchI", GENERIC),
    CoinWitchII("CoinWitchII", GENERIC),
    CoinWitchIII("CoinWitchIII", GENERIC),
    CoinWitchIV("CoinWitchIV", GENERIC),
    CoinSpace("CoinSpace", GENERIC),
    CoinSpaceI("CoinSpaceI", GENERIC),
    CoinSpaceII("CoinSpaceII", GENERIC),
    CoinSpaceIII("CoinSpaceIII", GENERIC),
    CoinSpaceIV("CoinSpaceIV", GENERIC),
    CoinSurvivor("CoinSurvivor", GENERIC),
    CoinSurvivorI("CoinSurvivorI", GENERIC),
    CoinSurvivorII("CoinSurvivorII", GENERIC),
    CoinSurvivorIII("CoinSurvivorIII", GENERIC),
    CoinSurvivorIV("CoinSurvivorIV", GENERIC),
    CoinTechnician("CoinTechnician", GENERIC),
    CoinTechnicianI("CoinTechnicianI", GENERIC),
    CoinTechnicianII("CoinTechnicianII", GENERIC),
    CoinTechnicianIII("CoinTechnicianIII", GENERIC),
    CoinTechnicianIV("CoinTechnicianIV", GENERIC),
    CoinDonation("CoinDonation", GENERIC),
    CokeOvenBrick("CokeOvenBrick", GENERIC),
    CokeOvenBrickDust("CokeOvenBrickDust", GENERIC),
    ConductiveIronBars("ConductiveIronBars", BARS_AND_CASINGS),
    CopperDualCompressedPlates("CopperDualCompressedPlates", SPACE),
    ChromeBars("ChromeBars", BARS_AND_CASINGS),
    ChromeIronPlate("ChromeIronPlate", SOLAR),
    CobbleStoneRod("CobbleStoneRod", GENERIC),
    CopperWandCap("CopperWandCap", THAUMCRAFT),
    CrimsonStainedClothCap("CrimsonStainedClothCap", THAUMCRAFT),
    DraconiumEgg("DraconiumEgg", GENERIC),
    DeimosStoneDust("DeimosStoneDust", SPACE),
    DeshDualCompressedPlates("DeshDualCompressedPlates", SPACE),
    Display("Display", CIRCUITS),
    DiamondCoreChip("DiamondCoreChip", CIRCUITS),
    DiamondDrillTip("DiamondDrillTip", GENERIC),
    DiamondFluidCoreChip("DiamondFluidCoreChip", CIRCUITS),
    EctoplasmaChip("EctoplasmaChip", GENERIC),
    EctoplasmaFragment("EctoplasmaFragment", GENERIC),
    ElectricalSteelBars("ElectricalSteelBars", BARS_AND_CASINGS),
    ElectricBoatHull("ElectricBoatHull", GENERIC),
    ElectrotineWire("ElectrotineWire", GENERIC),
    EmeraldAdvancedCoreChip("EmeraldAdvancedCoreChip", CIRCUITS),
    EmeraldAdvancedFluidCoreChip("EmeraldAdvancedFluidCoreChip", CIRCUITS),
    EmeraldHighAdvancedCoreChip("EmeraldHighAdvancedCoreChip", CIRCUITS),
    EMT("EMT", GENERIC),
    EnceladusIceDust("EnceladusIceDust", SPACE),
    EnceladusStoneDust("EnceladusStoneDust", SPACE),
    EnchantedClothCap("EnchantedClothCap", THAUMCRAFT),
    EnderiumBaseBars("EnderiumBaseBars", BARS_AND_CASINGS),
    EnderiumBars("EnderiumBars", BARS_AND_CASINGS),
    EnergeticAlloyBars("EnergeticAlloyBars", BARS_AND_CASINGS),
    EnderEgg("EnderEgg", GENERIC),
    EngineeringProcessorEssentiaPulsatingCore("EngineeringProcessorEssentiaPulsatingCore", CIRCUITS),
    EngineeringProcessorFluidDiamondCore("EngineeringProcessorFluidDiamondCore", CIRCUITS),
    EngineeringProcessorFluidEmeraldCore("EngineeringProcessorFluidEmeraldCore", CIRCUITS),
    EngineeringProcessorItemAdvEmeraldCore("EngineeringProcessorItemAdvEmeraldCore", CIRCUITS),
    EngineeringProcessorItemEmeraldCore("EngineeringProcessorItemEmeraldCore", CIRCUITS),
    EngineeringProcessorItemDiamondCore("EngineeringProcessorItemDiamondCore", CIRCUITS),
    EngineeringProcessorSpatialPulsatingCore("EngineeringProcessorSpatialPulsatingCore", CIRCUITS),
    EngineCore("EngineCore", GENERIC),
    EngravedEnergyChip("EngravedEnergyChip", CIRCUITS),
    EngravedDiamondCrystalChip("EngravedDiamondCrystalChip", CIRCUITS),
    EngravedGoldChip("EngravedGoldChip", CIRCUITS),
    EngravedManyullynCrystalChip("EngravedManyullynCrystalChip", CIRCUITS),
    EngravedQuantumChip("EngravedQuantumChip", CIRCUITS),
    EnrichedNaquadriaSunnariumAlloy("EnrichedNaquadriaSunnariumAlloy", SOLAR),
    EnrichedNaquadriaNeutroniumSunnariumAlloy("EnrichedNaquadriaNeutroniumSunnariumAlloy", SOLAR),
    EnrichedXSunnariumAlloy("EnrichedXSunnariumAlloy", SOLAR),
    EnvironmentalCircuit("EnvironmentalCircuit", CIRCUITS),
    EssentiaCircuit("EssentiaCircuit", CIRCUITS),
    EtchedLowVoltageWiring("EtchedLowVoltageWiring", CIRCUITS),
    EtchedInsaneVoltageWiring("EtchedInsaneVoltageWiring", CIRCUITS),
    EtchedLudicrousVoltageWiring("EtchedLudicrousVoltageWiring", CIRCUITS),
    EuropaIceDust("EuropaIceDust", SPACE),
    EuropaStoneDust("EuropaStoneDust", SPACE),
    ExtraLargeFuelCanister("ExtraLargeFuelCanister", SPACE),
    ExtruderShapeBoat("ExtruderShapeBoat", SHAPES),
    FieryBloodDrop("FieryBloodDrop", THAUMCRAFT),
    GanymedeStoneDust("GanymedeStoneDust", SPACE),
    GeneticCircuit("GeneticCircuit", CIRCUITS),
    GlowingMarshmallow("GlowingMarshmallow", THAUMCRAFT),
    GoldCoreChip("GoldCoreChip", CIRCUITS),
    GoldWandCap("GoldWandCap", THAUMCRAFT),
    HeavyDutyAlloyIngotT4("HeavyDutyAlloyIngotT4", SPACE),
    HeavyDutyAlloyIngotT5("HeavyDutyAlloyIngotT5", SPACE),
    HeavyDutyAlloyIngotT6("HeavyDutyAlloyIngotT6", SPACE),
    HeavyDutyAlloyIngotT7("HeavyDutyAlloyIngotT7", SPACE),
    HeavyDutyAlloyIngotT8("HeavyDutyAlloyIngotT8", SPACE),
    HeavyDutyAlloyIngotT9("HeavyDutyAlloyIngotT9", SPACE),
    HeavyDutyNoseConeTier3("HeavyDutyNoseConeTier3", SPACE),
    HeavyDutyNoseConeTier4("HeavyDutyNoseConeTier4", SPACE),
    HeavyDutyPlateTier4("HeavyDutyPlateTier4", SPACE),
    HeavyDutyPlateTier5("HeavyDutyPlateTier5", SPACE),
    HeavyDutyPlateTier6("HeavyDutyPlateTier6", SPACE),
    HeavyDutyPlateTier7("HeavyDutyPlateTier7", SPACE),
    HeavyDutyPlateTier8("HeavyDutyPlateTier8", SPACE),
    HeavyDutyRocketEngineTier3("HeavyDutyRocketEngineTier3", SPACE),
    HeavyDutyRocketEngineTier4("HeavyDutyRocketEngineTier4", SPACE),
    HeavyDutyRocketFinsTier3("HeavyDutyRocketFinsTier3", SPACE),
    HeavyDutyRocketFinsTier4("HeavyDutyRocketFinsTier4", SPACE),
    HighEnergyCircuitParts("HighEnergyCircuitParts", CIRCUITS),
    HighEnergyFlowCircuit("HighEnergyFlowCircuit", CIRCUITS),
    IceCompressedPlate("IceCompressedPlate", SPACE),
    IceDualCompressedPlates("IceDualCompressedPlates", SPACE),
    IchoriumCap("IchoriumCap", THAUMCRAFT),
    IndustryFrame("IndustryFrame", GENERIC),
    InfernalBrick("InfernalBrick", GENERIC),
    IoStoneDust("IoStoneDust", SPACE),
    IridiumBars("IridiumBars", BARS_AND_CASINGS),
    IridiumAlloyItemCasing("IridiumAlloyItemCasing", BARS_AND_CASINGS),
    IrradiantReinforcedAluminiumPlate("IrradiantReinforcedAluminiumPlate", SOLAR),
    IrradiantReinforcedBedrockiumPlate("IrradiantReinforcedBedrockiumPlate", SOLAR),
    IrradiantReinforcedChromePlate("IrradiantReinforcedChromePlate", SOLAR),
    IrradiantReinforcedNaquadriaPlate("IrradiantReinforcedNaquadriaPlate", SOLAR),
    IrradiantReinforcedNeutroniumPlate("IrradiantReinforcedNeutroniumPlate", SOLAR),
    IrradiantReinforcedTitaniumPlate("IrradiantReinforcedTitaniumPlate", SOLAR),
    IrradiantReinforcedTungstenPlate("IrradiantReinforcedTungstenPlate", SOLAR),
    IrradiantReinforcedTungstenSteelPlate("IrradiantReinforcedTungstenSteelPlate", SOLAR),
    IronWandCap("IronWandCap", THAUMCRAFT),
    IronDualCompressedPlates("IronDualCompressedPlates", SPACE),
    HaumeaStoneDust("HaumeaStoneDust", SPACE),
    HotNetherrackBrick("HotNetherrackBrick", GENERIC),
    LapotronDust("LapotronDust", CIRCUITS),
    LargeFuelCanister("LargeFuelCanister", SPACE),
    LaserEmitter("LaserEmitter", GENERIC),
    LeadNickelPlate("LeadNickelPlate", SPACE),
    LeadOriharukonPlate("LeadOriharukonPlate", SPACE),
    LedoxCompressedPlate("LedoxCompressedPlate", SPACE),
    LichBone("LichBone", THAUMCRAFT),
    LichBoneChip("LichBoneChip", THAUMCRAFT),
    LichBoneFragment("LichBoneFragment", THAUMCRAFT),
    LogicProcessorItemGoldCore("LogicProcessorItemGoldCore", CIRCUITS),
    LightShaft("LightShaft", SPACE),
    LightBinding("LightBinding", SPACE),
    LightAxeHead("LightAxeHead", SPACE),
    LightPickaxeHead("LightPickaxeHead", SPACE),
    LightSwordBlade("LightSwordBlade", SPACE),
    LongObsidianRod("LongObsidianRod", GENERIC),
    LongStoneRod("LongStoneRod", GENERIC),
    MagicianOrb("MagicianOrb", THAUMCRAFT),
    MarsStoneDust("MarsStoneDust", SPACE),
    NanoCircuit("NanoCircuit", CIRCUITS),
    MaceratedPlantmass("MaceratedPlantmass", GENERIC),
    MakeMakeStoneDust("MakeMakeStoneDust", SPACE),
    MalformedSlush("MalformedSlush", THAUMCRAFT),
    Marshmallow("Marshmallow", THAUMCRAFT),
    ManyullynCrystal("ManyullynCrystal", GENERIC),
    MarshmallowForm("MarshmallowForm", THAUMCRAFT),
    MarshmallowFormMold("MarshmallowFormMold", THAUMCRAFT),
    MasterOrb("MasterOrb", THAUMCRAFT),
    MediumFuelCanister("MediumFuelCanister", SPACE),
    MercuryCoreDust("MercuryCoreDust", SPACE),
    MercuryStoneDust("MercuryStoneDust", SPACE),
    MeteoricIronString("MeteoricIronString", SPACE),
    MeteoricIronDualCompressedPlates("MeteoricIronDualCompressedPlates", SPACE),
    MirandaStoneDust("MirandaStoneDust", SPACE),
    TuffDust("TuffDust", GENERIC),
    ChaoticDust("ChaoticDust", GENERIC),
    DeepslateDust("DeepslateDust", GENERIC),
    MoldChestplate("MoldChestplate", MOLDS),
    MoldHelmet("MoldHelmet", MOLDS),
    MoldLeggings("MoldLeggings", MOLDS),
    MoldFormLeggings("MoldFormLeggings", MOLDS),
    MoldFormHelmet("MoldFormHelmet", MOLDS),
    MoldFormChestplate("MoldFormChestplate", MOLDS),
    MoldFormBoots("MoldFormBoots", MOLDS),
    MoldBoots("MoldBoots", MOLDS),
    MoldFormAnvil("MoldFormAnvil", MOLDS),
    MoldFormArrowHead("MoldFormArrowHead", MOLDS),
    MoldFormBaguette("MoldFormBaguette", MOLDS),
    MoldFormBall("MoldFormBall", MOLDS),
    MoldFormBlock("MoldFormBlock", MOLDS),
    MoldFormBolt("MoldFormBolt", MOLDS),
    MoldFormBottle("MoldFormBottle", MOLDS),
    MoldFormBread("MoldFormBread", MOLDS),
    MoldFormBuns("MoldFormBuns", MOLDS),
    MoldFormCasing("MoldFormCasing", MOLDS),
    MoldFormCoinage("MoldFormCoinage", MOLDS),
    MoldFormCylinder("MoldFormCylinder", MOLDS),
    MoldFormGear("MoldFormGear", MOLDS),
    MoldFormIngot("MoldFormIngot", MOLDS),
    MoldFormName("MoldFormName", MOLDS),
    MoldFormNuggets("MoldFormNuggets", MOLDS),
    MoldFormPlate("MoldFormPlate", MOLDS),
    MoldFormRing("MoldFormRing", MOLDS),
    MoldFormRound("MoldFormRound", MOLDS),
    MoldFormRotor("MoldFormRotor", MOLDS),
    MoldFormScrew("MoldFormScrew", MOLDS),
    MoldFormSmallGear("MoldFormSmallGear", MOLDS),
    MoldFormStick("MoldFormStick", MOLDS),
    MoldFormStickLong("MoldFormStickLong", MOLDS),
    MoldFormTurbineBlade("MoldFormTurbineBlade", MOLDS),
    MoldFormPipeTiny("MoldFormPipeTiny", MOLDS),
    MoldFormPipeSmall("MoldFormPipeSmall", MOLDS),
    MoldFormPipeMedium("MoldFormPipeMedium", MOLDS),
    MoldFormPipeLarge("MoldFormPipeLarge", MOLDS),
    MoldFormPipeHuge("MoldFormPipeHuge", MOLDS),
    MoldFormDrillHead("MoldFormDrillHead", MOLDS),
    MoonStoneDust("MoonStoneDust", GENERIC),
    MushroomPowder("MushroomPowder", GENERIC),
    MutatedEgg("MutatedEgg", GENERIC),
    MysteriousCrystal("MysteriousCrystal", SPACE),
    MysteriousCrystalGemExquisite("MysteriousCrystalGemExquisite", SPACE),
    MysteriousCrystalGemFlawless("MysteriousCrystalGemFlawless", SPACE),
    MysteriousCrystalLens("MysteriousCrystalLens", SPACE),
    MysteriousCrystalCompressedPlate("MysteriousCrystalCompressedPlate", SPACE),
    MysteriousCrystalDualCompressedPlates("MysteriousCrystalDualCompressedPlates", SPACE),
    MytrylCrystal("MytrylCrystal", SPACE),
    MytrylCompressedPlate("MytrylCompressedPlate", SPACE),
    MytrylDualCompressedPlates("MytrylDualCompressedPlates", SPACE),
    NagaScaleChip("NagaScaleChip", THAUMCRAFT),
    NagaScaleFragment("NagaScaleFragment", THAUMCRAFT),
    NanoCrystal("NanoCrystal", CIRCUITS),
    NanoBoard("NanoBoard", CIRCUITS),
    NanoProcessorBoard("NanoProcessorBoard", CIRCUITS),
    NanoChestJetPack("NanoChestJetPack", GENERIC),
    NanoPlatedLeggings("NanoPlatedLeggings", GENERIC),
    NanoRubberBoots("NanoRubberBoots", GENERIC),
    NanoScubaHelmet("NanoScubaHelmet", GENERIC),
    NaquadriaIronPlate("NaquadriaIronPlate", SOLAR),
    NeutroniumBars("NeutroniumBars", BARS_AND_CASINGS),
    NeutroniumIronPlate("NeutroniumIronPlate", SOLAR),
    NeutronReflectorSmallParts("NeutronReflectorSmallParts", CIRCUITS),
    NeutronReflectorParts("NeutronReflectorParts", CIRCUITS),
    NetherStarFragment("NetherStarFragment", GENERIC),
    Nothing("Nothing", GENERIC),
    PikoCircuit("PikoCircuit", CIRCUITS),
    PistonPlate("PistonPlate", GENERIC),
    PhobosStoneDust("PhobosStoneDust", SPACE),
    PlutoIceDust("PlutoIceDust", SPACE),
    PlutoStoneDust("PlutoStoneDust", SPACE),
    PotassiumHydroxideDust("PotassiumHydroxideDust", GENERIC),
    PrimordialPearlFragment("PrimordialPearlFragment", THAUMCRAFT),
    ProteusStoneDust("ProteusStoneDust", SPACE),
    PulsatingIronBars("PulsatingIronBars", BARS_AND_CASINGS),
    PulsatingSpatialCoreChip("PulsatingSpatialCoreChip", CIRCUITS),
    OberonStoneDust("OberonStoneDust", SPACE),
    OsmiumBars("OsmiumBars", BARS_AND_CASINGS),
    QuantinumCompressedPlate("QuantinumCompressedPlate", SPACE),
    QuantinumDualCompressedPlates("QuantinumDualCompressedPlates", SPACE),
    QuantumCircuit("QuantumCircuit", CIRCUITS),
    QuantumCrystal("QuantumCrystal", CIRCUITS),
    QuantumPartBoots("QuantumPartBoots", GENERIC),
    QuantumPartChestplate("QuantumPartChestplate", GENERIC),
    QuantumPartHelmet("QuantumPartHelmet", GENERIC),
    QuantumPartHelmetEmpty("QuantumPartHelmetEmpty", GENERIC),
    QuantumPartLeggings("QuantumPartLeggings", GENERIC),
    QuantumBoard("QuantumBoard", CIRCUITS),
    QuantumProcessorBoard("QuantumProcessorBoard", CIRCUITS),
    RawBioFiber("RawBioFiber", GENERIC),
    RawLapotronCrystal("RawLapotronCrystal", CIRCUITS),
    RawPicoWafer("RawPicoWafer", CIRCUITS),
    PicoWafer("PicoWafer", CIRCUITS),
    // AdvancedPicoWafer("AdvancedPicoWafer", ModTabList.CircuitsTab),
    RawMytryl("RawMytryl", SPACE),
    RawNeutronium("RawNeutronium", SPACE),
    RawOrbTier1("RawOrbTier1", THAUMCRAFT),
    RawOrbTier2("RawOrbTier2", THAUMCRAFT),
    RawOrbTier3("RawOrbTier3", THAUMCRAFT),
    RawOrbTier4("RawOrbTier4", THAUMCRAFT),
    RawOrbTier5("RawOrbTier5", THAUMCRAFT),
    RawOrbTier6("RawOrbTier6", THAUMCRAFT),
    RawSDHCAlloy("RawSDHCAlloy", SPACE),
    RedstoneAlloyBars("RedstoneAlloyBars", BARS_AND_CASINGS),
    ReinforcedGlassPlate("ReinforcedGlassPlate", GENERIC),
    ReinforcedGlassLense("ReinforcedGlassLense", GENERIC),
    ReinforcedIridiumDrillTip("ReinforcedIridiumDrillTip", GENERIC),
    ReinforcedAluminiumIronPlate("ReinforcedAluminiumIronPlate", SOLAR),
    ReinforcedBedrockiumIronPlate("ReinforcedBedrockiumIronPlate", SOLAR),
    ReinforcedChromeIronPlate("ReinforcedChromeIronPlate", SOLAR),
    ReinforcedNaquadriaIronPlate("ReinforcedNaquadriaIronPlate", SOLAR),
    ReinforcedNeutroniumIronPlate("ReinforcedNeutroniumIronPlate", SOLAR),
    ReinforcedTitaniumIronPlate("ReinforcedTitaniumIronPlate", SOLAR),
    ReinforcedTungstenIronPlate("ReinforcedTungstenIronPlate", SOLAR),
    ReinforcedTungstenSteelIronPlate("ReinforcedTungstenSteelIronPlate", SOLAR),
    RuneOfPowerFragment("RuneOfPowerFragment", GENERIC),
    RuneOfAgilityFragment("RuneOfAgilityFragment", GENERIC),
    RuneOfVigorFragment("RuneOfVigorFragment", GENERIC),
    RuneOfDefenseFragment("RuneOfDefenseFragment", GENERIC),
    RuneOfMagicFragment("RuneOfMagicFragment", GENERIC),
    RuneOfVoidFragment("RuneOfVoidFragment", GENERIC),
    SandStoneRod("SandStoneRod", GENERIC),
    SawBladeStone("SawBladeStone", GENERIC),
    SawBladeDiamond("SawBladeDiamond", GENERIC),
    SawBladeArdite("SawBladeArdite", GENERIC),
    SawBladeManyullyn("SawBladeManyullyn", GENERIC),
    SawBladeRuby("SawBladeRuby", GENERIC),
    SawBladeSapphire("SawBladeSapphire", GENERIC),
    SawBladePeridot("SawBladePeridot", GENERIC),
    SchematicsAstroMiner("SchematicsAstroMiner", SPACE),
    SchematicsCargoRocket("SchematicsCargoRocket", SPACE),
    SchematicsMoonBuggy("SchematicsMoonBuggy", SPACE),
    SchematicsTier1("SchematicsTier1", SPACE),
    SchematicsTier2("SchematicsTier2", SPACE),
    SchematicsTier3("SchematicsTier3", SPACE),
    SchematicsTier4("SchematicsTier4", SPACE),
    SchematicsTier5("SchematicsTier5", SPACE),
    SchematicsTier6("SchematicsTier6", SPACE),
    SchematicsTier7("SchematicsTier7", SPACE),
    SchematicsTier8("SchematicsTier8", SPACE),
    ShadowImbuedClothCap("ShadowImbuedClothCap", THAUMCRAFT),
    ShadowmetalCap("ShadowmetalCap", THAUMCRAFT),
    ShapeAxeHead("ShapeAxeHead", SHAPES),
    ShapeBlock("ShapeBlock", SHAPES),
    ShapeBoat("ShapeBoat", SHAPES),
    ShapeBolt("ShapeBolt", SHAPES),
    ShapeBottle("ShapeBottle", SHAPES),
    ShapeCasing("ShapeCasing", SHAPES),
    ShapeCell("ShapeCell", SHAPES),
    ShapeFileHead("ShapeFileHead", SHAPES),
    ShapeGear("ShapeGear", SHAPES),
    ShapeHammerHead("ShapeHammerHead", SHAPES),
    ShapeHoeHead("ShapeHoeHead", SHAPES),
    ShapeHugePipe("ShapeHugePipe", SHAPES),
    ShapeIngot("ShapeIngot", SHAPES),
    ShapeLargePipe("ShapeLargePipe", SHAPES),
    ShapeNormalPipe("ShapeNormalPipe", SHAPES),
    ShapePickaxeHead("ShapePickaxeHead", SHAPES),
    ShapePlate("ShapePlate", SHAPES),
    ShapeRing("ShapeRing", SHAPES),
    ShapeRod("ShapeRod", SHAPES),
    ShapeRotor("ShapeRotor", SHAPES),
    ShapeSawBlade("ShapeSawBlade", SHAPES),
    ShapeShovelHead("ShapeShovelHead", SHAPES),
    ShapeSmallGear("ShapeSmallGear", SHAPES),
    ShapeSmallPipe("ShapeSmallPipe", SHAPES),
    ShapeSwordBlade("ShapeSwordBlade", SHAPES),
    ShapeTinyPipe("ShapeTinyPipe", SHAPES),
    ShapeTurbineBlade("ShapeTurbineBlade", SHAPES),
    ShapeWire("ShapeWire", SHAPES), // DEPRECATED. remove in next major version
    ShapeDrillHead("ShapeDrillHead", SHAPES),
    SilverThread("SilverThread", THAUMCRAFT),
    SilveredFleece("SilveredFleece", THAUMCRAFT),
    SimpleCircuitBoard("SimpleCircuitBoard", CIRCUITS),
    SnowQueenBlood("SnowQueenBlood", THAUMCRAFT),
    SnowQueenBloodDrop("SnowQueenBloodDrop", THAUMCRAFT),
    SoulariumBars("SoulariumBars", BARS_AND_CASINGS),
    StainlessSteelBars("StainlessSteelBars", BARS_AND_CASINGS),
    SteelBars("SteelBars", BARS_AND_CASINGS),
    SteelDualCompressedPlates("SteelDualCompressedPlates", SPACE),
    StonePlate("StonePlate", GENERIC),
    StargateFramePart("StargateFramePart", SPACE),
    StargateChevron("StargateChevron", SPACE),
    StargateShieldingFoil("StargateShieldingFoil", SPACE),
    StargateCrystalDust("StargateCrystalDust", SPACE),
    TCetiESeaweedExtract("TCetiESeaweedExtract", SPACE),
    TCetiEStoneDust("TCetiEStoneDust", SPACE),
    TeleposerFrame("TeleposerFrame", THAUMCRAFT),
    TheBigEgg("TheBigEgg", GENERIC),
    Tier2Booster("Tier2Booster", SPACE),
    Tier3Booster("Tier3Booster", SPACE),
    Tier4Booster("Tier4Booster", SPACE),
    TinDualCompressedPlates("TinDualCompressedPlates", SPACE),
    TitaniumBars("TitaniumBars", BARS_AND_CASINGS),
    TitaniumDualCompressedPlates("TitaniumDualCompressedPlates", SPACE),
    TitaniumIronPlate("TitaniumIronPlate", SOLAR),
    TitanStoneDust("TitanStoneDust", SPACE),
    TranscendentOrb("TranscendentOrb", THAUMCRAFT),
    TritonStoneDust("TritonStoneDust", SPACE),
    TungstenBars("TungstenBars", BARS_AND_CASINGS),
    TungstenIronPlate("TungstenIronPlate", SOLAR),
    TungstenSteelBars("TungstenSteelBars", BARS_AND_CASINGS),
    TungstenSteelIronPlate("TungstenSteelIronPlate", SOLAR),
    TungstenString("TungstenString", SPACE),
    TwilightCrystal("TwilightCrystal", GENERIC),
    UncookedSlush("UncookedSlush", THAUMCRAFT),
    UnfiredClayBrick("UnfiredClayBrick", GENERIC),
    UnfiredCokeOvenBrick("UnfiredCokeOvenBrick", GENERIC),
    UnfiredSearedBrick("UnfiredSearedBrick", GENERIC),
    UnfiredSlimeSoilBrick("UnfiredSlimeSoilBrick", GENERIC),
    VegaBStoneDust("VegaBStoneDust", SPACE),
    VenusStoneDust("VenusStoneDust", SPACE),
    VibrantAlloyBars("VibrantAlloyBars", BARS_AND_CASINGS),
    VinteumThread("VinteumThread", THAUMCRAFT),
    VoidEssence("VoidEssence", THAUMCRAFT),
    VoidSeed("VoidSeed", THAUMCRAFT),
    WaferTier3("WaferTier3", SPACE),
    WandCapAlchemical("WandCapAlchemical", THAUMCRAFT),
    WandCapBloodIron("WandCapBloodIron", THAUMCRAFT),
    WandCapElementium("WandCapElementium", THAUMCRAFT),
    WandCapManaSteel("WandCapManaSteel", THAUMCRAFT),
    WandCapTerraSteel("WandCapTerraSteel", THAUMCRAFT),
    WandCapVinteum("WandCapVinteum", THAUMCRAFT),
    WandCapThauminite("WandCapThauminite", THAUMCRAFT),
    WeakOrb("WeakOrb", THAUMCRAFT),
    WetTofu("WetTofu", GENERIC),
    WirelessTransmitter("WirelessTransmitter", GENERIC),
    WoodenCasing("WoodenCasing", GENERIC),
    MedalDerp("MedalDerp", GENERIC),
    MedalGTExplosion("MedalGTExplosion", GENERIC),
    MedalBuilder("MedalBuilder", GENERIC),
    MedalEngineer("MedalEngineer", GENERIC),
    MedalWarp("MedalWarp", GENERIC),
    AluminoSilicateWool("AluminoSilicateWool", GENERIC),
    EdibleSalt("EdibleSalt", GENERIC),
    CircuitULV("CircuitULV", CIRCUITS),
    CircuitLV("CircuitLV", CIRCUITS),
    CircuitMV("CircuitMV", CIRCUITS),
    CircuitHV("CircuitHV", CIRCUITS),
    CircuitEV("CircuitEV", CIRCUITS),
    CircuitIV("CircuitIV", CIRCUITS),
    CircuitLuV("CircuitLuV", CIRCUITS),
    CircuitZPM("CircuitZPM", CIRCUITS),
    CircuitUV("CircuitUV", CIRCUITS),
    CircuitUHV("CircuitUHV", CIRCUITS),
    CircuitUEV("CircuitUEV", CIRCUITS),
    CircuitUIV("CircuitUIV", CIRCUITS),
    CircuitUMV("CircuitUMV", CIRCUITS),
    CircuitUXV("CircuitUXV", CIRCUITS),
    CircuitMAX("CircuitMAX", CIRCUITS),
    RadoxPolymerLens("RadoxPolymerLens", SPACE),
    ChromaticLens("ChromaticLens", SPACE),
    ChromaticGem("ChromaticGem", SPACE),
    ChromaticGemFlawless("ChromaticGemFlawless", SPACE),
    ChromaticGemExquisite("ChromaticGemExquisite", SPACE),
    NanoCircuitOrigin("OriginNanoCircuit", SPACE),
    GatePlateOrigin("OriginGatePlate", SPACE),
    ChevronOrigin("OriginChevron", SPACE),
    FramePartOrigin("OriginFramePart", SPACE),
    PikoCircuitPolychrome("PolychromePikoCircuit", SPACE),
    QuantumCircuitPolychrome("PolychromeQuantumCircuit", SPACE),
    GatePlatePolychrome("PolychromeGatePlate", SPACE),
    ChevronPolychrome("PolychromeChevron", SPACE),
    FramePartPolychrome("PolychromeFramePart", SPACE),
    PikoCircuitDimensional("DimensionalPikoCircuit", SPACE),
    QuantumCircuitDimensional("DimensionalQuantumCircuit", SPACE),
    GatePlateDimensional("DimensionalGatePlate", SPACE),
    ChevronDimensional("DimensionalChevron", SPACE),
    FramePartDimensional("DimensionalFramePart", SPACE),
    GatePlateHarmonic("HarmonicGatePlate", SPACE),
    ChevronHarmonic("HarmonicChevron", SPACE),
    FramePartHarmonic("HarmonicFramePart", SPACE),
    StargateDustAncients("StargateDustAncients", SPACE),
    StargateCrystalAncients("StargateCrystalAncients", SPACE);

    static {
        CoinChunkloaderTierI.item.setMaxStackSize(4);
        CoinChunkloaderTierII.item.setMaxStackSize(4);
        CoinChunkloaderTierIII.item.setMaxStackSize(4);
        CoinChunkloaderTierIV.item.setMaxStackSize(4);
        CoinChunkloaderTierV.item.setMaxStackSize(4);
        MedalDerp.item.setMaxStackSize(1);
        MedalGTExplosion.item.setMaxStackSize(1);
        MedalBuilder.item.setMaxStackSize(1);
        MedalEngineer.item.setMaxStackSize(1);
        MedalWarp.item.setMaxStackSize(1);
    }

    // ################################################################################
    public final String name;
    public final Item item;

    NHItemList(String name, CreativeTabs tab) {
        this(name, new Item(), tab);
    }

    NHItemList(String name, Item item, CreativeTabs tab) {
        this.name = name;
        this.item = item;

        item.setUnlocalizedName(name);
        item.setTextureName(Refstrings.MODID + ":item" + name);
        item.setCreativeTab(tab);
    }

    public ItemStack get() {
        return new ItemStack(item, 1);
    }

    public ItemStack get(int amount) {
        return new ItemStack(item, amount);
    }

    public static void registerAll() {
        for (final var entry : NHItemList.values()) {
            GameRegistry.registerItem(entry.item, entry.name);
        }
    }
}
