package com.dreammaster.bartworksHandler;

import static bartworks.API.recipe.BartWorksRecipeMaps.bacterialVatRecipes;
import static com.dreammaster.scripts.IngredientFactory.getModItem;
import static gregtech.api.enums.GTValues.*;
import static gregtech.api.enums.Materials.NaquadahEnriched;
import static gregtech.api.enums.Materials.Plutonium;
import static gregtech.api.enums.Materials.Uranium;
import static gregtech.api.enums.Mods.BartWorks;
import static gregtech.api.enums.Mods.PamsHarvestCraft;
import static gregtech.api.recipe.RecipeMaps.centrifugeRecipes;
import static gregtech.api.recipe.RecipeMaps.chemicalReactorRecipes;
import static gregtech.api.recipe.RecipeMaps.fluidExtractionRecipes;
import static gregtech.api.recipe.RecipeMaps.mixerRecipes;
import static gregtech.api.recipe.RecipeMaps.multiblockChemicalReactorRecipes;
import static gregtech.api.util.GTRecipeBuilder.MINUTES;
import static gregtech.api.util.GTRecipeBuilder.SECONDS;
import static gregtech.api.util.GTRecipeConstants.GLASS;
import static gregtech.api.util.GTRecipeConstants.SIEVERT;
import static gregtech.api.util.GTRecipeConstants.UniversalChemical;

import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraftforge.fluids.Fluid;
import net.minecraftforge.fluids.FluidRegistry;
import net.minecraftforge.fluids.FluidStack;
import net.minecraftforge.oredict.OreDictionary;

import com.ruling_0.materiallib.api.MaterialLibAPI;

import bartworks.API.enums.BioCultureEnum;
import bartworks.MainMod;
import bartworks.common.items.SimpleSubItemClass;
import bartworks.util.BWUtil;
import cpw.mods.fml.common.registry.GameRegistry;
import gregtech.api.enums.FluidState;
import gregtech.api.enums.GTValues;
import gregtech.api.enums.ItemList;
import gregtech.api.enums.Materials;
import gregtech.api.enums.TierEU;
import gregtech.api.enums.materials2.Materials2FluidShapes;
import gregtech.api.enums.materials2.Materials2Materials;
import gregtech.api.enums.materials2.Materials2Shapes;
import gregtech.api.fluid.GTFluidFactory;
import gregtech.api.util.GTModHandler;
import gregtech.api.util.recipe.Sievert;

public class BioItemLoader {

    private static Item BIOTEMS;
    private static Fluid[] BIOFLUIDS;

    // FIXME: Move bio-items to Bartworks and remove this whole section.
    public static void preInit() {
        BIOTEMS = new SimpleSubItemClass("itemCollagen", "itemGelatin", "itemAgar").setCreativeTab(MainMod.BIO_TAB);
        GameRegistry.registerItem(BIOTEMS, "GTNHBioItems", BartWorks.ID);

        BIOFLUIDS = new Fluid[] { GTFluidFactory.builder("GelatinMixture").withDefaultLocalName("Gelatin Mixture")
                .withTextureName("molten.autogenerated").withColorRGBA(new short[] { 255, 255, 125 })
                .withStateAndTemperature(FluidState.LIQUID, 300).buildAndRegister().addLocalizedName().asFluid(),
                GTFluidFactory.builder("MeatExtract").withDefaultLocalName("Meat Extract")
                        .withTextureName("molten.autogenerated").withColorRGBA(new short[] { 160, 70, 50 })
                        .withStateAndTemperature(FluidState.LIQUID, 300).buildAndRegister().addLocalizedName()
                        .asFluid(),
                GTFluidFactory.builder("UnknownNutrientAgar").withDefaultLocalName("Unknown Nutrient Agar")
                        .withTextureName("molten.autogenerated").withColorRGBA(new short[] { 175, 133, 0 })
                        .withStateAndTemperature(FluidState.LIQUID, 300).buildAndRegister().addLocalizedName()
                        .asFluid(),
                GTFluidFactory.builder("SeaweedBroth").withDefaultLocalName("Seaweed Broth")
                        .withTextureName("molten.autogenerated").withColorRGBA(new short[] { 60, 200, 0 })
                        .withStateAndTemperature(FluidState.LIQUID, 300).buildAndRegister().addLocalizedName()
                        .asFluid() };

    }

    public static void registerRecipes() {
        if (BIOTEMS == null || BIOFLUIDS == null) {
            throw new IllegalStateException("Called registerRecipes without calling preInit first.");
        }

        GTValues.RA.stdBuilder()
                .itemInputs(
                        MaterialLibAPI.getStack(Materials2Materials.MeatRaw, Materials2Shapes.shapeDust, (int) (2)),
                        new ItemStack(Items.bone, 1))
                .itemOutputs(new ItemStack(BIOTEMS, 2, 0))
                .fluidInputs(
                        MaterialLibAPI.getFluidStack(
                                Materials2Materials.DilutedSulfuricAcid,
                                Materials2FluidShapes.shapeFluidLiquid,
                                (int) (1000)))
                .fluidOutputs(Materials.Water.getFluid(1000)).duration(1 * MINUTES + 20 * SECONDS).eut(TierEU.RECIPE_HV)
                .addTo(UniversalChemical);

        GTValues.RA.stdBuilder()
                .itemInputs(
                        MaterialLibAPI.getStack(Materials2Materials.MeatRaw, Materials2Shapes.shapeDust, (int) (1)),
                        Materials.Bone.getDust(2))
                .itemOutputs(new ItemStack(BIOTEMS, 1, 0))
                .fluidInputs(
                        MaterialLibAPI.getFluidStack(
                                Materials2Materials.DilutedSulfuricAcid,
                                Materials2FluidShapes.shapeFluidLiquid,
                                (int) (500)))
                .fluidOutputs(Materials.Water.getFluid(500)).duration(40 * SECONDS).eut(TierEU.RECIPE_HV)
                .addTo(UniversalChemical);

        GTValues.RA.stdBuilder().itemInputs(new ItemStack(BIOTEMS, 4, 0), Materials.Water.getCells(3))
                .itemOutputs(Materials.Empty.getCells(3)).fluidInputs(Materials.PhosphoricAcid.getFluid(1000))
                .fluidOutputs(new FluidStack(BIOFLUIDS[0], 4000)).duration(1 * MINUTES + 20 * SECONDS)
                .eut(TierEU.RECIPE_HV).addTo(UniversalChemical);

        GTValues.RA.stdBuilder().itemInputs(new ItemStack(BIOTEMS, 4, 0), Materials.PhosphoricAcid.getCells(1))
                .itemOutputs(Materials.Empty.getCells(1)).fluidInputs(Materials.Water.getFluid(3000))
                .fluidOutputs(new FluidStack(BIOFLUIDS[0], 4000)).duration(1 * MINUTES + 20 * SECONDS)
                .eut(TierEU.RECIPE_HV).addTo(chemicalReactorRecipes);

        GTValues.RA.stdBuilder().circuit(1)
                .itemOutputs(
                        MaterialLibAPI.getStack(Materials2Materials.Phosphorus, Materials2Shapes.shapeDust, (int) (1)),
                        new ItemStack(BIOTEMS, 4, 1))
                .fluidInputs(new FluidStack(BIOFLUIDS[0], 6000)).duration(2 * MINUTES).eut(TierEU.RECIPE_HV)
                .addTo(centrifugeRecipes);

        RA.stdBuilder().itemInputs(new ItemStack(BIOTEMS, 1, 1)).circuit(11).itemOutputs(new ItemStack(BIOTEMS, 1, 2))
                .fluidInputs(GTModHandler.getDistilledWater(1000)).duration(30 * SECONDS).eut(TierEU.RECIPE_HV)
                .addTo(mixerRecipes);

        GTValues.RA.stdBuilder()
                .itemInputs(MaterialLibAPI.getStack(Materials2Materials.MeatRaw, Materials2Shapes.shapeDust, (int) (1)))
                .fluidOutputs(new FluidStack(BIOFLUIDS[1], 125)).duration(15 * SECONDS).eut(TierEU.RECIPE_MV)
                .addTo(fluidExtractionRecipes);

        GTValues.RA.stdBuilder()
                .itemInputs(
                        new ItemStack(BIOTEMS, 8, 2),
                        ItemList.Circuit_Chip_Stemcell.get(16),
                        MaterialLibAPI.getStack(Materials2Materials.Salt, Materials2Shapes.shapeDust, (int) (64)))
                .fluidInputs(
                        FluidRegistry.getFluidStack("unknowwater", 4000),
                        Materials.PhthalicAcid.getFluid(3000),
                        new FluidStack(BIOFLUIDS[1], 1000))
                .fluidOutputs(new FluidStack(BIOFLUIDS[2], 8000)).duration(60 * SECONDS).eut(TierEU.RECIPE_UV)
                .addTo(multiblockChemicalReactorRecipes);

        GTValues.RA.stdBuilder()
                .itemInputs(
                        ItemList.IC2_Energium_Dust.get(8),
                        MaterialLibAPI.getStack(Materials2Materials.Mytryl, Materials2Shapes.shapeDust, (int) (1)),
                        getModItem(PamsHarvestCraft.ID, "seaweedItem", 64))
                .special(BioCultureEnum.getPetriDish(BioCultureEnum.TcetieisFucusSerratus.bioCulture))
                .fluidInputs(new FluidStack(BIOFLUIDS[2], 50)).fluidOutputs(new FluidStack(BIOFLUIDS[3], 50))
                .duration(1 * MINUTES).eut(TierEU.RECIPE_UV).metadata(GLASS, 8)
                .metadata(SIEVERT, new Sievert(100, false)).addTo(bacterialVatRecipes);

        for (int i = 0; i < OreDictionary.getOres("cropTcetiESeaweed").size(); i++) {
            GTValues.RA.stdBuilder().circuit(i + 1)
                    .itemOutputs(OreDictionary.getOres("cropTcetiESeaweed").get(i).copy().splitStack(64))
                    .fluidInputs(new FluidStack(BIOFLUIDS[3], 1000)).duration(2 * SECONDS).eut(TierEU.RECIPE_UV)
                    .addTo(centrifugeRecipes);
        }

        GTValues.RA.stdBuilder()
                .itemInputs(
                        MaterialLibAPI.getStack(Materials2Materials.MeatRaw, Materials2Shapes.shapeDust, (int) (4)),
                        MaterialLibAPI.getStack(Materials2Materials.Salt, Materials2Shapes.shapeDust, (int) (4)),
                        MaterialLibAPI.getStack(Materials2Materials.Calcium, Materials2Shapes.shapeDust, (int) (4)),
                        new ItemStack(BIOTEMS, 4, 2))
                .special(BioCultureEnum.getPetriDish(BioCultureEnum.OvaEvolutionis.bioCulture))
                .fluidInputs(FluidRegistry.getFluidStack("binnie.bacteria", 4))
                .fluidOutputs(
                        MaterialLibAPI.getFluidStack(
                                Materials2Materials.GrowthMediumRaw,
                                Materials2FluidShapes.shapeFluidLiquid,
                                (int) (1)))
                .duration(1 * MINUTES).eut(TierEU.RECIPE_IV).metadata(GLASS, 5)
                .metadata(SIEVERT, new Sievert(BWUtil.calculateSv(Uranium), false)).addTo(bacterialVatRecipes);

        GTValues.RA.stdBuilder()
                .itemInputs(
                        MaterialLibAPI.getStack(Materials2Materials.MeatRaw, Materials2Shapes.shapeDust, (int) (8)),
                        MaterialLibAPI.getStack(Materials2Materials.Salt, Materials2Shapes.shapeDust, (int) (8)),
                        MaterialLibAPI.getStack(Materials2Materials.Calcium, Materials2Shapes.shapeDust, (int) (8)),
                        new ItemStack(BIOTEMS, 4, 2))
                .special(BioCultureEnum.getPetriDish(BioCultureEnum.OvaEvolutionis.bioCulture))
                .fluidInputs(FluidRegistry.getFluidStack("bacterialsludge", 4))
                .fluidOutputs(
                        MaterialLibAPI.getFluidStack(
                                Materials2Materials.GrowthMediumRaw,
                                Materials2FluidShapes.shapeFluidLiquid,
                                (int) (2)))
                .duration(1 * MINUTES).eut(TierEU.RECIPE_LuV).metadata(GLASS, 6)
                .metadata(SIEVERT, new Sievert(BWUtil.calculateSv(Plutonium), false)).addTo(bacterialVatRecipes);

        GTValues.RA.stdBuilder()
                .itemInputs(
                        MaterialLibAPI.getStack(Materials2Materials.MeatRaw, Materials2Shapes.shapeDust, (int) (12)),
                        MaterialLibAPI.getStack(Materials2Materials.Salt, Materials2Shapes.shapeDust, (int) (12)),
                        MaterialLibAPI.getStack(Materials2Materials.Calcium, Materials2Shapes.shapeDust, (int) (12)),
                        new ItemStack(BIOTEMS, 4, 2))
                .special(BioCultureEnum.getPetriDish(BioCultureEnum.OvaEvolutionis.bioCulture))
                .fluidInputs(FluidRegistry.getFluidStack("mutagen", 4))
                .fluidOutputs(
                        MaterialLibAPI.getFluidStack(
                                Materials2Materials.GrowthMediumRaw,
                                Materials2FluidShapes.shapeFluidLiquid,
                                (int) (4)))
                .duration(1 * MINUTES).eut(TierEU.RECIPE_ZPM).metadata(GLASS, 7)
                .metadata(SIEVERT, new Sievert(BWUtil.calculateSv(NaquadahEnriched), true)).addTo(bacterialVatRecipes);
    }
}
