package com.dreammaster.bartworksHandler;

import static bartworks.API.recipe.BartWorksRecipeMaps.bacterialVatRecipes;
import static com.dreammaster.scripts.IngredientFactory.getModItem;
import static gregtech.api.enums.GTValues.*;
import static gregtech.api.enums.Materials.NaquadahEnriched;
import static gregtech.api.enums.Materials.Plutonium;
import static gregtech.api.enums.Materials.Uranium;
import static gregtech.api.enums.Mods.BartWorks;
import static gregtech.api.enums.Mods.GalaxySpace;
import static gregtech.api.enums.Mods.PamsHarvestCraft;
import static gregtech.api.enums.Mods.SGCraft;
import static gregtech.api.enums.Mods.TinkerConstruct;
import static gregtech.api.recipe.RecipeMaps.autoclaveRecipes;
import static gregtech.api.recipe.RecipeMaps.centrifugeRecipes;
import static gregtech.api.recipe.RecipeMaps.chemicalBathRecipes;
import static gregtech.api.recipe.RecipeMaps.chemicalReactorRecipes;
import static gregtech.api.recipe.RecipeMaps.fluidExtractionRecipes;
import static gregtech.api.recipe.RecipeMaps.mixerNonCellRecipes;
import static gregtech.api.recipe.RecipeMaps.mixerRecipes;
import static gregtech.api.recipe.RecipeMaps.multiblockChemicalReactorRecipes;
import static gregtech.api.util.GTRecipeBuilder.MINUTES;
import static gregtech.api.util.GTRecipeBuilder.SECONDS;
import static gregtech.api.util.GTRecipeConstants.GLASS;
import static gregtech.api.util.GTRecipeConstants.SIEVERT;
import static gregtech.api.util.GTRecipeConstants.UniversalChemical;

import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraftforge.fluids.Fluid;
import net.minecraftforge.fluids.FluidRegistry;
import net.minecraftforge.fluids.FluidStack;
import net.minecraftforge.oredict.OreDictionary;

import bartworks.API.enums.BioCultureEnum;
import bartworks.MainMod;
import bartworks.common.items.SimpleSubItemClass;
import bartworks.common.loaders.BioCultureLoader;
import bartworks.common.loaders.FluidLoader;
import bartworks.system.material.WerkstoffLoader;
import bartworks.util.BWUtil;
import cpw.mods.fml.common.registry.GameRegistry;
import gregtech.api.enums.FluidState;
import gregtech.api.enums.GTValues;
import gregtech.api.enums.ItemList;
import gregtech.api.enums.Materials;
import gregtech.api.enums.OrePrefixes;
import gregtech.api.enums.TierEU;
import gregtech.api.fluid.GTFluidFactory;
import gregtech.api.util.GTModHandler;
import gregtech.api.util.recipe.Sievert;
import gtPlusPlus.xmod.gregtech.api.enums.GregtechItemList;
import gtnhlanth.common.register.WerkstoffMaterialPool;

public class BioItemLoader {

    private static Item BIOTEMS;
    private static Fluid[] BIOFLUIDS;

    // FIXME: Move bio-items to Bartworks and remove this whole section.
    public static void preInit() {
        BIOTEMS = new SimpleSubItemClass(
                "itemCollagen",
                "itemGelatin",
                "itemAgar",
                "itemPeptone",
                "itemBacterialGrowthMediumDust").setCreativeTab(MainMod.BIO_TAB);
        GameRegistry.registerItem(BIOTEMS, "GTNHBioItems", BartWorks.ID);

        BIOFLUIDS = new Fluid[] { GTFluidFactory.builder("GelatinMixture").withDefaultLocalName("Gelatin Mixture")
                .withTextureName("molten.autogenerated").withColorRGBA(new short[] { 255, 255, 125 })
                .withStateAndTemperature(FluidState.LIQUID, 300).buildAndRegister().addLocalizedName().asFluid(),
                // 1
                GTFluidFactory.builder("MeatExtract").withDefaultLocalName("Meat Extract")
                        .withTextureName("molten.autogenerated").withColorRGBA(new short[] { 160, 70, 50 })
                        .withStateAndTemperature(FluidState.LIQUID, 300).buildAndRegister().addLocalizedName()
                        .asFluid(),
                // 2
                GTFluidFactory.builder("UnknownNutrientAgar").withDefaultLocalName("Unknown Nutrient Agar")
                        .withTextureName("molten.autogenerated").withColorRGBA(new short[] { 175, 133, 0 })
                        .withStateAndTemperature(FluidState.LIQUID, 300).buildAndRegister().addLocalizedName()
                        .asFluid(),
                // 3
                GTFluidFactory.builder("SeaweedBroth").withDefaultLocalName("Seaweed Broth")
                        .withTextureName("molten.autogenerated").withColorRGBA(new short[] { 60, 200, 0 })
                        .withStateAndTemperature(FluidState.LIQUID, 300).buildAndRegister().addLocalizedName()
                        .asFluid(),
                // 4
                GTFluidFactory.builder("YeastExtract").withDefaultLocalName("Yeast Extract")
                        .withTextureName("molten.autogenerated").withColorRGBA(new short[] { 200, 160, 255 })
                        .withStateAndTemperature(FluidState.LIQUID, 300).buildAndRegister().addLocalizedName()
                        .asFluid(),
                // 5
                GTFluidFactory.builder("ProteaseSolution").withDefaultLocalName("Protease Solution")
                        .withTextureName("autogenerated").withColorRGBA(new short[] { 255, 235, 180 })
                        .withStateAndTemperature(FluidState.LIQUID, 300).buildAndRegister().addLocalizedName()
                        .asFluid(),
                // 6
                GTFluidFactory.builder("Protease").withDefaultLocalName("Protease").withTextureName("autogenerated")
                        .withColorRGBA(new short[] { 255, 224, 224 }).withStateAndTemperature(FluidState.LIQUID, 300)
                        .buildAndRegister().addLocalizedName().asFluid(),
                // 7
                GTFluidFactory.builder("YeastGrowthMedium").withDefaultLocalName("Yeast Growth Medium")
                        .withTextureName("autogenerated").withColorRGBA(new short[] { 142, 80, 220 })
                        .withStateAndTemperature(FluidState.LIQUID, 300).buildAndRegister().addLocalizedName()
                        .asFluid(),
                // 8
                GTFluidFactory.builder("AgarSolution").withDefaultLocalName("Agar Solution")
                        .withTextureName("autogenerated").withColorRGBA(new short[] { 190, 235, 200 })
                        .withStateAndTemperature(FluidState.LIQUID, 300).buildAndRegister().addLocalizedName()
                        .asFluid(),
                // 9
                GTFluidFactory.builder("AAVitRichSolution").withDefaultLocalName("Amino Acid - Vitamin Rich Solution")
                        .withTextureName("autogenerated").withColorRGBA(new short[] { 255, 250, 100 })
                        .withStateAndTemperature(FluidState.LIQUID, 300).buildAndRegister().addLocalizedName()
                        .asFluid(),
                // 10
                GTFluidFactory.builder("PhosphoricBuffer").withDefaultLocalName("Phosphoric Buffer")
                        .withTextureName("autogenerated").withColorRGBA(new short[] { 255, 255, 255 })
                        .withStateAndTemperature(FluidState.LIQUID, 300).buildAndRegister().addLocalizedName()
                        .asFluid(),
                // 11
                GTFluidFactory.builder("Serum").withDefaultLocalName("Serum").withTextureName("autogenerated")
                        .withColorRGBA(new short[] { 255, 230, 90 }).withStateAndTemperature(FluidState.LIQUID, 300)
                        .buildAndRegister().addLocalizedName().asFluid() };

    }

    public static void registerRecipes() {
        if (BIOTEMS == null || BIOFLUIDS == null) {
            throw new IllegalStateException("Called registerRecipes without calling preInit first.");
        }

        GTValues.RA.stdBuilder().itemInputs(Materials.MeatRaw.getDust(2), new ItemStack(Items.bone, 1))
                .itemOutputs(new ItemStack(BIOTEMS, 2, 0)).fluidInputs(Materials.DilutedSulfuricAcid.getFluid(1000))
                .fluidOutputs(Materials.Water.getFluid(1000)).duration(1 * MINUTES + 20 * SECONDS).eut(TierEU.RECIPE_HV)
                .addTo(UniversalChemical);

        GTValues.RA.stdBuilder().itemInputs(Materials.MeatRaw.getDust(1), Materials.Bone.getDust(2))
                .itemOutputs(new ItemStack(BIOTEMS, 1, 0)).fluidInputs(Materials.DilutedSulfuricAcid.getFluid(500))
                .fluidOutputs(Materials.Water.getFluid(500)).duration(40 * SECONDS).eut(TierEU.RECIPE_HV)
                .addTo(UniversalChemical);

        GTValues.RA.stdBuilder().itemInputs(new ItemStack(BIOTEMS, 4, 0), Materials.Water.getCells(3))
                .itemOutputs(Materials.Empty.getCells(3)).fluidInputs(Materials.PhosphoricAcid.getFluid(1000))
                .fluidOutputs(new FluidStack(BIOFLUIDS[0], 4000)).duration(1 * MINUTES + 20 * SECONDS)
                .eut(TierEU.RECIPE_HV).addTo(UniversalChemical);

        GTValues.RA.stdBuilder().itemInputs(new ItemStack(BIOTEMS, 4, 0), Materials.PhosphoricAcid.getCells(1))
                .itemOutputs(Materials.Empty.getCells(1)).fluidInputs(Materials.Water.getFluid(3000))
                .fluidOutputs(new FluidStack(BIOFLUIDS[0], 4000)).duration(1 * MINUTES + 20 * SECONDS)
                .eut(TierEU.RECIPE_HV).addTo(chemicalReactorRecipes);

        GTValues.RA.stdBuilder().circuit(1).itemOutputs(Materials.Phosphorus.getDust(1), new ItemStack(BIOTEMS, 4, 1))
                .fluidInputs(new FluidStack(BIOFLUIDS[0], 6000)).duration(2 * MINUTES).eut(TierEU.RECIPE_HV)
                .addTo(centrifugeRecipes);

        GTValues.RA.stdBuilder().itemInputs(Materials.MeatRaw.getDust(1))
                .fluidOutputs(new FluidStack(BIOFLUIDS[1], 125)).duration(15 * SECONDS).eut(TierEU.RECIPE_MV)
                .addTo(fluidExtractionRecipes);

        GTValues.RA.stdBuilder()
                .itemInputs(
                        new ItemStack(BIOTEMS, 8, 2),
                        ItemList.Circuit_Chip_Stemcell.get(16),
                        Materials.Salt.getDust(64))
                .fluidInputs(
                        FluidRegistry.getFluidStack("unknowwater", 4000),
                        Materials.PhthalicAcid.getFluid(3000),
                        new FluidStack(BIOFLUIDS[1], 1000))
                .fluidOutputs(new FluidStack(BIOFLUIDS[2], 8000)).duration(60 * SECONDS).eut(TierEU.RECIPE_UV)
                .addTo(multiblockChemicalReactorRecipes);

        GTValues.RA.stdBuilder()
                .itemInputs(
                        ItemList.IC2_Energium_Dust.get(8),
                        Materials.Mytryl.getDust(1),
                        getModItem(PamsHarvestCraft.ID, "seaweedItem", 64))
                .special(BioCultureEnum.getPetriDish(BioCultureEnum.TcetieisFucusSerratus.bioCulture))
                .fluidInputs(new FluidStack(BIOFLUIDS[2], 50)).fluidOutputs(new FluidStack(BIOFLUIDS[3], 50))
                .duration(1 * MINUTES).eut(TierEU.RECIPE_UV).metadata(GLASS, 8)
                .metadata(SIEVERT, new Sievert(100, false)).addTo(bacterialVatRecipes);

        for (int i = 0; i < OreDictionary.getOres("cropTcetiESeaweed").size(); i++) {
            GTValues.RA.stdBuilder().circuit(i + 1)
                    .itemOutputs(OreDictionary.getOres("cropTcetiESeaweed").get(i).copy().splitStack(64))
                    .fluidInputs(new FluidStack(BIOFLUIDS[3], 1000)).duration(2 * SECONDS).eut(TierEU.RECIPE_UV)
                    .addTo(centrifugeRecipes);
        }

        GTValues.RA.stdBuilder().itemInputs(getModItem(PamsHarvestCraft.ID, "flourItem", 1, 0))
                .fluidInputs(Materials.HydrochloricAcid.getFluid(1000))
                .fluidOutputs(Materials.Glucose.getFluid(1000), Materials.DilutedHydrochloricAcid.getFluid(1000))
                .duration(1 * SECONDS).eut(TierEU.RECIPE_EV).addTo(multiblockChemicalReactorRecipes);

        GTValues.RA.stdBuilder().circuit(4)
                .fluidInputs(Materials.Hydrogen.getGas(12000), Materials.CarbonDioxide.getGas(6000))
                .fluidOutputs(Materials.Glucose.getFluid(1000), Materials.Water.getFluid(6000)).duration(1 * SECONDS)
                .eut(TierEU.RECIPE_UV).addTo(multiblockChemicalReactorRecipes);

        GTValues.RA.stdBuilder().circuit(2).fluidInputs(new FluidStack(BioCultureLoader.CommonYeast.getFluid(), 1000))
                .fluidOutputs(new FluidStack(BIOFLUIDS[4], 1000)).duration(5 * SECONDS).eut(TierEU.RECIPE_LuV)
                .addTo(centrifugeRecipes);

        GTValues.RA.stdBuilder().circuit(2).fluidInputs(new FluidStack(BioCultureLoader.PenicilliumYeast.getFluid(), 1000))
                .fluidOutputs(new FluidStack(BIOFLUIDS[4], 1000)).duration(5 * SECONDS).eut(TierEU.RECIPE_LuV)
                .addTo(centrifugeRecipes);

        GTValues.RA.stdBuilder().itemInputs(ItemList.Pancrea.get(1)).fluidOutputs(new FluidStack(BIOFLUIDS[5], 1000))
                .duration(20 * SECONDS).eut(TierEU.RECIPE_EV).addTo(fluidExtractionRecipes);

        GTValues.RA.stdBuilder()
                .fluidInputs(new FluidStack(BIOFLUIDS[5], 1000), WerkstoffLoader.AmmoniumSulfate.getFluidOrGas(3000))
                .fluidOutputs(new FluidStack(BIOFLUIDS[6], 500)).duration(30 * SECONDS).eut(TierEU.RECIPE_EV)
                .addTo(multiblockChemicalReactorRecipes);

        GTValues.RA.stdBuilder().itemInputs(new ItemStack(BIOTEMS, 1, 1)).fluidInputs(new FluidStack(BIOFLUIDS[6], 10))
                .itemOutputs(new ItemStack(BIOTEMS, 1, 3)).duration(30 * SECONDS).eut(TierEU.RECIPE_HV)
                .addTo(multiblockChemicalReactorRecipes);

        GTValues.RA.stdBuilder().itemInputs(new ItemStack(BIOTEMS, 2, 3))
                .fluidInputs(
                        Materials.Glucose.getFluid(2000),
                        new FluidStack(BIOFLUIDS[4], 1000),
                        GTModHandler.getDistilledWater(7000))
                .fluidOutputs(new FluidStack(BIOFLUIDS[7], 10000)).duration(5 * SECONDS).eut(TierEU.RECIPE_EV)
                .addTo(mixerNonCellRecipes);

        GTValues.RA.stdBuilder().special(BioCultureEnum.getPetriDish(BioCultureEnum.SaccharomycesCerevisiae.bioCulture))
                .circuit(2).fluidInputs(new FluidStack(BIOFLUIDS[7], 1))
                .fluidOutputs(new FluidStack(BioCultureLoader.CommonYeast.getFluid(), 1)).metadata(GLASS, 4)
                .duration(20 * SECONDS).eut(TierEU.RECIPE_HV).addTo(bacterialVatRecipes);

        GTValues.RA.stdBuilder()
                .special(BioCultureEnum.getPetriDish(BioCultureEnum.SaccharomycesCerevisiaeVarPenicillium.bioCulture))
                .circuit(2).fluidInputs(new FluidStack(BIOFLUIDS[7], 1))
                .fluidOutputs(new FluidStack(BioCultureLoader.PenicilliumYeast.getFluid(), 1)).metadata(GLASS, 4)
                .duration(20 * SECONDS).eut(TierEU.RECIPE_HV).addTo(bacterialVatRecipes);

        GTValues.RA.stdBuilder()
                .itemInputs(GregtechItemList.RedAlgaeBiomass.get(16), Materials.SodiumHydroxide.getDust(3))
                .fluidInputs(Materials.Water.getFluid(1000)).fluidOutputs(new FluidStack(BIOFLUIDS[8], 1000))
                .duration(10 * SECONDS).eut(TierEU.RECIPE_HV).addTo(chemicalBathRecipes);

        if (GalaxySpace.isModLoaded() && SGCraft.isModLoaded()) {
            for (int i = 0; i < 6; ++i) {
                GTValues.RA.stdBuilder()
                        .itemInputs(
                                getModItem(GalaxySpace.ID, "tcetiedandelions", 1, i),
                                Materials.SodiumHydroxide.getDust(3))
                        .fluidInputs(Materials.Water.getFluid(4000)).fluidOutputs(new FluidStack(BIOFLUIDS[8], 4000))
                        .duration(10 * SECONDS).eut(TierEU.RECIPE_EV).addTo(chemicalBathRecipes);
            }
        }

        GTValues.RA.stdBuilder().itemInputs(Materials.Calcium.getDust(1))
                .itemOutputs(new ItemStack(BIOTEMS, 1, 2), WerkstoffMaterialPool.SeaweedAsh.get(OrePrefixes.dust, 1))
                .outputChances(10000, 2000).fluidInputs(new FluidStack(BIOFLUIDS[8], 1000)).duration(100 * SECONDS)
                .eut(TierEU.RECIPE_LV).addTo(autoclaveRecipes);

        GTValues.RA.stdBuilder()
                .itemInputs(
                        new ItemStack(BIOTEMS, 2, 3),
                        Materials.Salt.getDust(2),
                        new ItemStack(BIOTEMS, 4, 2),
                        Materials.MeatRaw.getDust(1))
                .fluidInputs(new FluidStack(BIOFLUIDS[4], 1000)).itemOutputs(new ItemStack(BIOTEMS, 10, 4))
                .duration(10 * SECONDS).eut(TierEU.RECIPE_EV).addTo(mixerRecipes);

        GTValues.RA.stdBuilder().itemInputs(new ItemStack(BIOTEMS, 16, 4))
                .special(BioCultureEnum.getPetriDish(BioCultureEnum.OvaEvolutionis.bioCulture))
                .fluidInputs(FluidRegistry.getFluidStack("binnie.bacteria", 4))
                .fluidOutputs(new FluidStack(BIOFLUIDS[9], 1)).duration(1 * MINUTES).eut(TierEU.RECIPE_IV)
                .metadata(GLASS, 5).metadata(SIEVERT, new Sievert(BWUtil.calculateSv(Uranium), false))
                .addTo(bacterialVatRecipes);

        GTValues.RA.stdBuilder().itemInputs(new ItemStack(BIOTEMS, 16, 4))
                .special(BioCultureEnum.getPetriDish(BioCultureEnum.OvaEvolutionis.bioCulture))
                .fluidInputs(FluidRegistry.getFluidStack("bacterialsludge", 4))
                .fluidOutputs(new FluidStack(BIOFLUIDS[9], 2)).duration(1 * MINUTES).eut(TierEU.RECIPE_LuV)
                .metadata(GLASS, 6).metadata(SIEVERT, new Sievert(BWUtil.calculateSv(Plutonium), false))
                .addTo(bacterialVatRecipes);

        GTValues.RA.stdBuilder().itemInputs(new ItemStack(BIOTEMS, 16, 4))
                .special(BioCultureEnum.getPetriDish(BioCultureEnum.OvaEvolutionis.bioCulture))
                .fluidInputs(FluidRegistry.getFluidStack("mutagen", 4)).fluidOutputs(new FluidStack(BIOFLUIDS[9], 4))
                .duration(1 * MINUTES).eut(TierEU.RECIPE_ZPM).metadata(GLASS, 7)
                .metadata(SIEVERT, new Sievert(BWUtil.calculateSv(NaquadahEnriched), true)).addTo(bacterialVatRecipes);

        GTValues.RA.stdBuilder().itemInputs(Materials.PotassiumHydroxide.getDust(3))
                .fluidInputs(Materials.PhosphoricAcid.getFluid(1500)).fluidOutputs(new FluidStack(BIOFLUIDS[10], 1500))
                .duration(10 * SECONDS).eut(TierEU.RECIPE_HV).addTo(multiblockChemicalReactorRecipes);

        GTValues.RA.stdBuilder().itemOutputs(getModItem(TinkerConstruct.ID, "strangeFood", 1, 1))
                .fluidInputs(new FluidStack(FluidRegistry.getFluid("blood"), 300))
                .fluidOutputs(new FluidStack(BIOFLUIDS[11], 100)).duration(1 * MINUTES).eut(TierEU.RECIPE_LV)
                .addTo(centrifugeRecipes);

        GTValues.RA.stdBuilder().itemInputs(WerkstoffLoader.CalciumChloride.get(OrePrefixes.dust, 1)).circuit(2)
                .fluidInputs(
                        Materials.Glucose.getFluid(3000),
                        new FluidStack(BIOFLUIDS[9], 1000),
                        new FluidStack(BIOFLUIDS[10], 100),
                        new FluidStack(BIOFLUIDS[11], 200),
                        new FluidStack(FluidLoader.BioLabFluidMaterials[2], 50))
                .fluidOutputs(Materials.GrowthMediumRaw.getFluid(5000)).duration(10 * SECONDS).eut(TierEU.RECIPE_IV)
                .addTo(mixerNonCellRecipes);
    }
}
